### ISSUE TITLE
[bug]为什么admin用户名登录不了

### ISSUE THREAD

**Issue by shalimujiang** [OpenBMB/XAgent#10]
邮件：admin
token：xagent-admin

**Comment by shalimujiang** [comment]
![2023-10-18_04-14](https://github.com/OpenBMB/XAgent/assets/75249643/2807e2a8-5068-4885-8322-e0ca76b1ef1e)

**Comment by ChengFai** [comment]
稍等马上改，

**Comment by iamlockelightning** [comment]
https://github.com/OpenBMB/XAgent/issues/9#issuecomment-1766282557

**Comment by sailaoda** [comment]
Thanks for your advice, it will work now.
