### ISSUE TITLE
如何正确填写config.yml

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/XAgent#100]
现在我有一个openai的gpt key，当时我填写上去以后并不能正确运行，如何填写这个config.yml

![image](https://github.com/OpenBMB/XAgent/assets/87591236/1ef956ba-bff3-4214-a8c7-68cbeeca0913)
![image](https://github.com/OpenBMB/XAgent/assets/87591236/4d8f8a09-a65a-4f82-9052-f37b30cd07de)

**Comment by luyaxi** [comment]
如果没有organization，请删除该字段

**Comment by luyaxi** [comment]
你已经正确启动的程序，但是由于你未指定task，导致XAgent尝试在其工作区内寻找任务。这是预期正确的行为，请提供你的真实任务。

**Comment by luyaxi** [comment]
请查看`XAgentServer`容器的日志中是否有报错信息，并重新开启一个issue提问。如果有，请在新issue中附上日志；如果没有，请检查8090端口是否可连接，使用浏览器开发者工具来检查是否有关于8090端口的错误请求
