### ISSUE TITLE
引用大语言模型能否改为国内的模型呢？

### ISSUE THREAD

**Issue by simon7238** [OpenBMB/XAgent#101]
## Feature Description / 功能描述
当前的XAgent使用的后台大语言模型为OpenAI的ChatGPT模型，在国内使用不方便。

## Goal / 目标
能让XAgent的使用人员可以选择不同大厂的大语言模型。

## Expected Behavior / 预期行为
让国内使用人员更友好。

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。

## Additional Notes / 其他备注
无

**Comment by simon7238** [comment]
谢谢，非常期待该功能的更新！

**Comment by Umpire2018** [comment]
@simon7238 #5

**Comment by marioluan** [comment]
Any plans to support integrating with external models via TGI (HuggingFace's inference library)?
