### ISSUE TITLE
google palm 2 api key

### ISSUE THREAD

**Issue by SmellyBones** [OpenBMB/XAgent#102]
how do i edit the code to make xagent accept google bard or google palm api key rather then using open ai api key?

**Comment by thuqinyj16** [comment]
It's not just replacing the key. We use openai API's function call feature, but currently bard / palm does not support such a feature (of course you can implement it yourself thru prompting). BTW, we'll support local model for XAgent in two weeks, stay tuned!

**Comment by RafiullahOmar** [comment]
@thuqinyj16  does XAgent support local models now?
