### ISSUE TITLE
Connecting to locally hosted model which is exposed via LM Studio Local Server

### ISSUE THREAD

**Issue by RustyRSR** [OpenBMB/XAgent#104]
## Feature Description / 功能描述
Would it be possible to connect to a locally hosted model which is exposed via LM Studio Local Server

## Goal / 目标
This will enable testing without incurring the token costs 

## Expected Behavior / 预期行为
Tasks should be sent to the locally hosted LLM 

## Alternative Solutions / 其他解决方案
N/A

## Additional Notes / 其他备注
Integration details can be found at https://github.com/lmstudio-ai/examples

**Comment by Umpire2018** [comment]
We'll definitely think about it.

**Comment by shiloh92** [comment]
Why is this NOT planned? Open Source is an absolute must - one of the easiest integrations would be LM Studio. It serves an endpoint just like OpenAI's.

**Comment by Umpire2018** [comment]
@shiloh92 
1. **Core Mission**: Our primary focus is ensuring the high efficiency and performance of XAgent. While we understand the importance and convenience of open-source integrations, our mission dictates our priorities.

2. **Our Own Model**: Currently, we are utilizing our own proprietary model - [Xagentllm](https://huggingface.co/collections/XAgentTeam/xagentllm-655ae4091c419bb072940e74). This has been tailored to meet our specific needs and offers us a level of customization and control that is essential for our service and user experience.

3. **Open to Innovation**: We recognize the value of open-source solutions like LM Studio in certain contexts. However, our in-house development gives us greater flexibility and control, which is crucial for our application. We remain open to technological advancements and potential integrations that could enhance our product in the future.

Additionally, we highly value and welcome contributions from the open-source community. Collaborative efforts and shared knowledge can lead to innovative solutions that benefit everyone.
