### ISSUE TITLE
docker-compose build fail

### ISSUE THREAD

**Issue by yuanzhiyong1999** [OpenBMB/XAgent#105]
![image](https://github.com/OpenBMB/XAgent/assets/94682439/c452707f-acf1-4c69-93cb-3cef78b61d8f)
![image](https://github.com/OpenBMB/XAgent/assets/94682439/5af3b544-723a-46e3-8741-b6becbf54c80)

**Comment by Leopold-Fitz-AI** [comment]
我也出现这个情况，这些包都安装了也无法解决。

**Comment by yuanzhiyong1999** [comment]
![image](https://github.com/OpenBMB/XAgent/assets/94682439/15d45892-8177-4370-b0ba-468e411ffe25)
我现在的问题是会一直卡在这里 安装不了npm

**Comment by Umpire2018** [comment]
@yuanzhiyong1999 图中有两个问题，
一是相关变量未存在，检查项目根目录是否存在 `.env` 文件，文件中是否存在相关变量。
二是无法连接到 npm registry
请尝试改善网络环境，或更改镜像
在 `dockerfiles\XAgentServer\Dockerfile` 中进行修改
![image](https://github.com/OpenBMB/XAgent/assets/138990495/4f0e7c13-f581-4dee-a569-7c587394836c)

**Comment by Umpire2018** [comment]
@Leopold-Fitz-AI 请贴出报错截图，但首先请改善本地网络环境。
