### ISSUE TITLE
尝试体验，但进入的死循环

### ISSUE THREAD

**Issue by Cuiunbo** [OpenBMB/XAgent#106]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
我在尝试体验您们的工作时候遇到了死循环，一直如下
FunctionCallSchemaError: No function call found in the response 
  chatcompletion: using gpt-3.5-turbo-16k
## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
```bash
 python run.py --task "Here is a file that roughly contains two parts: data and rules for data processing. I plan to input this file into GPT-4 and ask it to help me generate visual question-and-answer pairs according to my rules. However, the prompts I designed myself clearly have many flaws and cannot generate questions and answers well. I hope you can try self-questioning and self-answering to test the effect and optimize my prompt. Eventually, I want to be able to use commands to generate three sets of questions. The first set should generate simple visual question-and-answer pairs. The second set should generate complex visual question-and-answer pairs that will include a lot of premises and assumptions in the questions (such as what I am doing now and what kind of information I hope to obtain). The third set should construct more complex visual question-and-answer pairs that require rounds of dialogue. You can write the specific rules. In the end, you need to return to me a well-debugged command. Then, I can use it to generate these three parts of data in three times." --model "gpt-3.5-turbo-16k" --config_file "assets/config.yml" --upload_files 'data/ori_prompt.txt'
```
## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
本来是想代替我去把sft数据构造时用的prompt调整完美，但是现在卡在了第一步
## Environment / 环境信息
- Operating System / 操作系统：mac
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
这是第一份输出以后类似
{
  "input": {
    "messages": [
      {
        "role": "system",
        "content": "You are an efficient plan-generation agent, your task is to decompose a query into several subtasks that describe must achieved goals for the query.\n--- Background Information ---\nPLAN AND SUBTASK:\nA plan has a tree manner of subtasks: task 1 contatins subtasks task 1.1, task 1.2, task 1.3, ... and task 1.2 contains subtasks 1.2.1, 1.2.2, ...\n\nA subtask-structure has the following json component:\n{\n\"subtask name\": string, name of the subtask\n\"goal.goal\": string, the main purpose of the subtask, and what will you do to reach this goal?\n\"goal.criticism\": string, what potential problems may the current subtask and goal have?\n\"milestones\": list[string]. what milestones should be achieved to ensure the subtask is done? Make it detailed and specific.\n}\nSUBTASK HANDLE:\nA task-handling agent will handle all the subtasks as the inorder-traversal. For example:\n1. it will handle subtask 1 first.\n2. if solved, handle subtask 2. If failed, split subtask 1 as subtask 1.1 1.2 1.3... Then handle subtask 1.1 1.2 1.3...\n3. Handle subtasks recurrsively, until all subtasks are soloved. Do not make the task queue too complex, make it efficiently solve the original task.\n4. It is powered by a state-of-the-art LLM, so it can handle many subtasks without using external tools or execute codes.\n\nRESOURCES:\n1. Internet access for searches and information gathering, seach engine and web browsing.\n2. A FileSystemEnv to read and write files (txt, code, markdown, latex...)\n3. A python notebook to execute python code. Always follow python coding rules.\n4. A ShellEnv to execute bash or zsh command to further achieve complex goals. \n--- Task Description ---\nGenerate the plan for query with operation SUBTASK_SPLIT, make sure all must reach goals are included in the plan.\n\n*** Important Notice ***\n- Always make fesible and efficient plans that can lead to successful task solving. Never create new subtasks that similar or same as the exisiting subtasks.\n- For subtasks with similar goals, try to do them together in one subtask with a list of subgoals, rather than split them into multiple subtasks.\n- Do not waste time on making irrelevant or unnecessary plans.\n- The task handler is powered by sota LLM, which can directly answer many questions. So make sure your plan can fully utilze its ability and reduce the complexity of the subtasks tree.\n- You can plan multiple subtasks if you want.\n- Minimize the number of subtasks, but make sure all must reach goals are included in the plan.\n"
      },
      {
        "role": "user",
        "content": "This is the the first time you are handling the task, so you should give a initial plan. Here is the query:\n\"\"\"\n{\n  \"name\": \"act as Assistant\",\n  \"goal\": \"Here is a file that roughly contains two parts: data and rules for data processing. I plan to input this file into GPT-4 and ask it to help me generate visual question-and-answer pairs according to my rules. However, the prompts I designed myself clearly have many flaws and cannot generate questions and answers well. I hope you can try self-questioning and self-answering to test the effect and optimize my prompt. Eventually, I want to be able to use commands to generate three sets of questions. The first set should generate simple visual question-and-answer pairs. The second set should generate complex visual question-and-answer pairs that will include a lot of premises and assumptions in the questions (such as what I am doing now and what kind of information I hope to obtain). The third set should construct more complex visual question-and-answer pairs that require rounds of dialogue. You can write the specific rules. In the end, you need to return to me a well-debugged command. Then, I can use it to generate these three parts of data in three times.\",\n  \"prior_plan_criticsim\": \"\",\n  \"milestones\": [],\n  \"exceute_status\": \"TODO\"\n}\n\"\"\"\nYou will use operation SUBTASK_SPLIT to split the query into 2-4 subtasks and then commit."
      }
    ],
    "functions": [
      {
        "name": "subtask_split_operation",
        "description": "further split the target subtask into subtasks. You can only split a status==FAIL task",
        "parameters": {
          "type": "object",
          "properties": {
            "target_subtask_id": {
              "type": "string",
              "description": "Which subtask do you want to modify. This must be a inter split by '.', like '1.2' '2.3.3' or '4'. You must ensure this subtask exists and is a FAIL task"
            },
            "subtasks": {
              "type": "array",
              "description": "Max 4 items, min 2 items. Array of the splited subtasks, length of 2-4",
              "items": {
                "type": "object",
                "properties": {
                  "subtask name": {
                    "type": "string"
                  },
                  "goal": {
                    "type": "object",
                    "properties": {
                      "goal": {
                        "type": "string",
                        "description": "the main purpose of what the sub-task should handle, and what will you do(tool calls) to reach this goal"
                      },
                      "criticism": {
                        "type": "string",
                        "description": "What problems may the current subtask and goal have?"
                      }
                    }
                  },
                  "milestones": {
                    "type": "array",
                    "description": "How to automatically check the subtask is done? The subtasks after this subtask will consider all the milestones are done.",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "subtask name",
                  "goal",
                  "milestones"
                ]
              }
            },
            "thought": {
              "description": "Why you choose this operation, and what you want to do next?",
              "type": "string"
            }
          },
          "required": [
            "target_subtask_id",
            "subtasks",
            "thought"
          ]
        }
      }
    ],
    "function_call": {
      "name": "subtask_split_operation"
    },
    "model": null,
    "stop": null,
    "other_args": {}
  },
  "output": {
    "choices": [
      {
        "finish_reason": "stop",
        "index": 0,
        "message": {
          "content": "Based on the query provided, here is an initial plan to achieve the desired goals:\n\n1. Subtask 1: Understand the Data and Rules File\n  * Goal: Understand the data and rules file provided, and determine how it can be input into GPT-4.\n  * Criticism: The file may be in an unfamiliar format, or may not contain all the necessary information to input into GPT-4.\n  * Milestones:\n    - Read the data and rules file.\n    - Determine the format and structure of the file, as well as any necessary preprocessing steps.\n    - Determine how to input the file into GPT-4.\n    - Validate that the input format works correctly with GPT-4.\n\n2. Subtask 2: Optimize Prompts and Self-Questioning\n  * Goal: Test the effect of self-questioning and self-answering on the prompts provided, and optimize the prompt as necessary.\n  * Criticism: The prompts may not generate effective visual question-and-answer pairs, or may require significant optimization to generate quality pairs.\n  * Milestones:\n    - Develop self-questioning and self-answering techniques to test the prompts.\n    - Test the prompts and identify any flaws or issues in generating visual question-and-answer pairs.\n    - Optimize the prompts as necessary to improve the quality of the generated pairs.\n    - Validate that the optimized prompts generate quality visual question-and-answer pairs.\n\n3. Subtask 3: Generate Three Sets of Questions\n  * Goal: Generate three sets of questions using the optimized prompts that meet the requirements specified in the query.\n  * Criticism: The generated questions may not meet the required complexity levels, or the dialogue-based questions may be difficult to generate.\n  * Milestones:\n    - Develop rules for generating the three sets of questions.\n    - Generate the first set of simple visual question-and-answer pairs.\n    - Generate the second set of complex visual question-and-answer pairs with multiple premises and assumptions in the questions.\n    - Generate the third set of visual question-and-answer pairs that require rounds of dialogue.\n    - Validate that the generated questions meet the required complexity levels and are of high quality.\n\n4. Subtask 4 (optional): Create a Well-Debugged Command\n  * Goal: Create a well-debugged command that can be used to generate the three sets of questions.\n  * Criticism: The command may be complex or difficult to use, which could limit its usefulness.\n  * Milestones:\n    - Develop the command to generate the three sets of questions.\n    - Debug the command to ensure that it works correctly.\n    - Validate that the command can be used to generate the three sets of questions easily and efficiently.\n\nNote: Subtask 4 is marked as optional because it may not be necessary depending on the specifics of the project. If the command is not complex or difficult to use, it may not be necessary to create a separate subtask for it.",
          "role": "assistant"
        }
      }
    ],
    "created": 1698230205,
    "id": "chatcmpl-8DVXhyOmjh26j2rmwbnfQSPuEW3IJ",
    "usage": {
      "completion_tokens": 605,
      "prompt_tokens": 965,
      "total_tokens": 1570
    }
  },
  "llm_interface_id": 0
}
## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。
可能原因是因为我是用的是国内包装好的openai apikey，但是不确定

**Comment by luyaxi** [comment]
请确保该API支持function call，XAgent依赖function call功能。部分国内旧openai服务并不支持该功能

**Comment by zhiyuanc2001** [comment]
您好，请问 --upload_files里面具体要传入什么内容？是in context learning example吗？:-)

**Comment by virtualmemorys** [comment]
遇到同样的问题：
ChatCompletionMessage(content='Hello! How can I assist you today?', role='assistant', function_call=None, tool_calls=None),我也用的国内包装好的api，从返回结果上看支持function_call，但xagent还是提示：
Constructing an Agent:  PlanGenerateAgent
  chatcompletion: using gpt-4-32k
FunctionCallSchemaError: No function call found in the response 
  chatcompletion: using gpt-4-32k
FunctionCallSchemaError: No function call found in the response 
  chatcompletion: using gpt-4-32k
FunctionCallSchemaError: No function call found in the response
