### ISSUE TITLE
WebEnv_search_and_browse 搜索的时候总是出错

### ISSUE THREAD

**Issue by ahkimkoo** [OpenBMB/XAgent#107]
Command Status:
"TOOL_CALL_FAILED"

···
{"detail":"Traceback (most recent call last):\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 10, in map_exceptions\n yield\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py\", line 212, in connect_tcp\n sock = socket.create_connection(\n File \"/usr/local/lib/python3.10/socket.py\", line 845, in create_connection\n raise err\n File \"/usr/local/lib/python3.10/socket.py\", line 833, in create_connection\n sock.connect(sa)\nOSError: [Errno 99] Cannot assign requested address\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 66, in map_httpcore_exceptions\n yield\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 228, in handle_request\n resp = self._pool.handle_request(req)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 262, in handle_request\n raise exc\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 245, in handle_request\n response = connection.handle_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 99, in handle_request\n raise exc\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 76, in handle_request\n stream = self._connect(request)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 124, in _connect\n stream = self._network_backend.connect_tcp(**kwargs)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py\", line 211, in connect_tcp\n with map_exceptions(exc_map):\n File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n self.gen.throw(typ, value, traceback)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n raise to_exc(exc) from exc\nhttpcore.ConnectError: [Errno 99] Cannot assign requested address\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File \"/app/main.py\", line 173, in execute_tool\n result = await result\n File \"/app/core/envs/web.py\", line 62, in search_and_browse\n pages = [{\n File \"/app/core/envs/web.py\", line 62, in <listcomp>\n pages = [{\n File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 95, in text\n for i, result in enumerate(results, start=1):\n File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 123, in _text_api\n vqd = self._get_vqd(keywords)\n File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 59, in _get_vqd\n resp = self._get_url(\"POST\", \"https://duckduckgo.com\", data={\"q\": keywords})\n File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 54, in _get_url\n raise ex\n File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 45, in _get_url\n resp = self._client.request(method, url, follow_redirects=True, **kwargs)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 814, in request\n return self.send(request, auth=auth, follow_redirects=follow_redirects)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 901, in send\n response = self._send_handling_auth(\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 929, in _send_handling_auth\n response = self._send_handling_redirects(\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 966, in _send_handling_redirects\n response = self._send_single_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1002, in _send_single_request\n response = transport.handle_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 227, in handle_request\n with map_httpcore_exceptions():\n File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n self.gen.throw(typ, value, traceback)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 83, in map_httpcore_exceptions\n raise mapped_exc(message) from exc\nhttpx.ConnectError: [Errno 99] Cannot assign requested address\n"}
···

**Comment by luyaxi** [comment]
请检查网络连接，该错误并非bug。或者，你可以申请bing api key并使用bing搜索引擎

**Comment by ahkimkoo** [comment]
补充一下，bing搜索确实可以了。但是遇到搜索结果的页面有404的状况就卡住了。
```
{"detail":"Traceback (most recent call last):\n File \"/app/main.py\", line 173, in execute_tool\n result = await result\n File \"/app/core/envs/web.py\", line 108, in browse_website\n res.raise_for_status()\n File \"/usr/local/lib/python3.10/site-packages/httpx/_models.py\", line 749, in raise_for_status\n raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '404 Not Found' for url 'https://www.usnews.com/news/technology-news'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n"}
```

**Comment by luyaxi** [comment]
能否提供更详细的日志信息来帮助定位错误？

**Comment by TITC** [comment]
@ahkimkoo  @luyaxi 

```
{"detail":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 10, in map_exceptions\n    yield\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py\", line 212, in connect_tcp\n    sock = socket.create_connection(\n  File \"/usr/local/lib/python3.10/socket.py\", line 845, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.10/socket.py\", line 833, in create_connection\n    sock.connect(sa)\nOSError: [Errno 99] Cannot assign requested address\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 66, in map_httpcore_exceptions\n    yield\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 228, in handle_request\n    resp = self._pool.handle_request(req)\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 262, in handle_request\n    raise exc\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py\", line 245, in handle_request\n    response = connection.handle_request(request)\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 99, in handle_request\n    raise exc\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 76, in handle_request\n    stream = self._connect(request)\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py\", line 124, in _connect\n    stream = self._network_backend.connect_tcp(**kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py\", line 211, in connect_tcp\n    with map_exceptions(exc_map):\n  File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n    raise to_exc(exc) from exc\nhttpcore.ConnectError: [Errno 99] Cannot assign requested address\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/app/main.py\", line 173, in execute_tool\n    result = await result\n  File \"/app/core/envs/web.py\", line 62, in search_and_browse\n    pages = [{\n  File \"/app/core/envs/web.py\", line 62, in <listcomp>\n    pages = [{\n  File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 95, in text\n    for i, result in enumerate(results, start=1):\n  File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 123, in _text_api\n    vqd = self._get_vqd(keywords)\n  File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 59, in _get_vqd\n    resp = self._get_url(\"POST\", \"https://duckduckgo.com\", data={\"q\": keywords})\n  File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 54, in _get_url\n    raise ex\n  File \"/usr/local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py\", line 45, in _get_url\n    resp = self._client.request(method, url, follow_redirects=True, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 814, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 901, in send\n    response = self._send_handling_auth(\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 929, in _send_handling_auth\n    response = self._send_handling_redirects(\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 966, in _send_handling_redirects\n    response = self._send_single_request(request)\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1002, in _send_single_request\n    response = transport.handle_request(request)\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 227, in handle_request\n    with map_httpcore_exceptions():\n  File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n    self.gen.throw(typ, value, traceback)\n  File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 83, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ConnectError: [Errno 99] Cannot assign requested address\n"}
```

遇到类似的问题，一直尝试访问web失败。
> 请检查网络连接，该错误并非bug。或者，你可以申请bing api key并使用bing搜索引擎

这里所说的网络连接是指需要进行网络代理么？

bing的配置有看到位于node.yml中
```yaml
bing:
  api_key:  # fill your own key here
  endpoint: https://api.bing.microsoft.com/v7.0/search

```

![image](https://github.com/OpenBMB/XAgent/assets/35098797/26d78c9f-16e9-47dd-8412-b60eba5f8c18)

**Comment by dontlove14** [comment]
同问作者，该bing请求超时的问题是否解决。我在中国大陆也请求不到，我尝试给容器配置DNS但是依旧没有效果。让你感到意外的是，我在我的电脑上可以正常请求bing的api

**Comment by TITC** [comment]
> 同问作者，该bing请求超时的问题是否解决。我在中国大陆也请求不到，我尝试给容器配置DNS但是依旧没有效果。让你感到意外的是，我在我的电脑上可以正常请求bing的api

![image](https://github.com/OpenBMB/XAgent/assets/35098797/f82b8c86-cc35-48a7-bb95-f495bc27f25c)

电脑上翻墙了吧

**Comment by dontlove14** [comment]
并没有，我是国内的IP。所以我不是很清楚问题出在哪里。但是他却一直在超时，除了配置文件外，我还修改过web.py的关于请求bing的具体执行方法（search_and_browse）中的region参数，将其默认改为zh-CN。不过我确定的是这么改接口可以正常请求，因为我用同样的代码在本地完成了测试，但是通过tool就超时了，很奇怪
![image](https://github.com/OpenBMB/XAgent/assets/54974888/1dd7ed61-4e49-4179-a21d-5c78e7b01bf5)

![image](https://github.com/OpenBMB/XAgent/assets/54974888/f5d15611-61d1-40d6-bb54-c8973ec502e9)

**Comment by dontlove14** [comment]
是否是因为缺少除了bing的配置外的其他配置信息没有补全导致的?但是这里我已经写了，并且确认api-key为可用的值
![image](https://github.com/OpenBMB/XAgent/assets/54974888/6a839783-2c53-4275-a3c7-8893241e4f10)

**Comment by LOGIC-10** [comment]
Please assign to me

**Comment by LOGIC-10** [comment]
这个报错属于网络问题，建议先在github codespace上部署项目，并再次尝试使用bing搜索能力。
关于github codespace以及详细的部署全流程，我们很快会出一个教程视频，欢迎持续关注
