### ISSUE TITLE
tried reproducing a previous run

### ISSUE THREAD

**Issue by SmellyBones** [OpenBMB/XAgent#108]
## Issue Description / 
i tried to load a record, i added the path in the config to a previous run

## Steps to Reproduce / 
added path to record_dir then tried loading a prompt

## Expected Behavior / 
i expected it to pick up where it left off on a previous run.

## Environment /
- Operating System / windows 11
- Python Version / Python 版本：3.11
- Other Relevant Information / 

## Error Screenshots or Logs / 
C:\Users\deadb\XAgent>python run.py --task "where did you leave off? can you finish your web search?" --model gpt-4 --config_file assets/config.yml
XAgentServer is running on cmd mode
XAgentServer log:  XAgentServer\localstorage\interact_records\2023-10-25\2bdf41bf6f2c4355b8d1284784b06e8b
  init localstorage connection: interaction.json
-=-=--=-=-=-=-=-=-= Current Instruction =-=-=-=-=-=-=-=-=-=-=-=-=-=-
where did you leave off? can you finish your web search?
Receive args from 2bdf41bf6f2c4355b8d1284784b06e8b:   user_id: admin, token: xagent-admin, description: XAgent-Test
Receive data from 2bdf41bf6f2c4355b8d1284784b06e8b:   where did you leave off? can you finish your web search?
  Register parameter: {'interaction_id': '2bdf41bf6f2c4355b8d1284784b06e8b', 'parameter_id': '22661e8c21734bc9b14dc8e63f5e0ff2', 'args': {'description': 'XAgent-Test', 'role_name': 'Assistant', 'download_files': [], 'file_list': None, 'record_dir': 'C:\\Users\\deadb\\XAgent\\running_records\\2023_10_25_03_47_3124609a7d', 'goal': 'where did you leave off? can you finish your web search?', 'mode': 'auto', 'plan': [], 'max_wait_seconds': 600}} into interaction of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
  init interaction: 2bdf41bf6f2c4355b8d1284784b06e8b
  Register logger into interaction of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
  Register io into interaction of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
  Register db into interaction of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
  Register logger into XAgentServer of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
  Start a new thread to run interaction of 2bdf41bf6f2c4355b8d1284784b06e8b, done!
Constructing an AgentDispatcher:  XAgentDispatcher
---config file---
assets/config.yml
---args---
{'record_dir': 'C:\\Users\\deadb\\XAgent\\running_records\\2023_10_25_03_47_3124609a7d', 'default_completion_kwargs': {'model': 'gpt-4', 'temperature': 0.2, 'request_timeout': 60}, 'enable_ask_human_for_help': True, 'max_subtask_chain_length': 15, 'max_plan_refine_chain_length': 3, 'max_plan_tree_depth': 3, 'max_plan_tree_width': 5, 'max_retry_times': 5}
load from a disk record, overwrite all the existing config-info  C:\Users\deadb\XAgent\running_records\2023_10_25_03_47_3124609a7d
---config file---
assets/config.yml
---args---
{'record_dir': 'C:\\Users\\deadb\\XAgent\\running_records\\2023_10_25_03_47_3124609a7d', 'default_completion_kwargs': {'model': 'gpt-4', 'temperature': 0.2, 'request_timeout': 60}, 'enable_ask_human_for_help': True, 'max_subtask_chain_length': 15, 'max_plan_refine_chain_length': 3, 'max_plan_tree_depth': 3, 'max_plan_tree_width': 5, 'max_retry_times': 5}
Traceback (most recent call last):
  File "C:\Users\deadb\XAgent\run.py", line 53, in <module>
    cmd.start(
  File "C:\Users\deadb\XAgent\command.py", line 163, in start
    self.run({
  File "C:\Users\deadb\XAgent\command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\deadb\XAgent\XAgentServer\server.py", line 40, in interact
    recorder.load_from_disk(interaction.base.recorder_root_dir)
  File "C:\Users\deadb\XAgent\XAgent\running_recorder.py", line 222, in load_from_disk
    self.llm_server_cache[inout_id] = llm_pair
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list assignment index out of range

**Comment by Umpire2018** [comment]
```
It doesn't seem to be implemented yet?

  init interaction: 1e7a574ca40c4bfc907407bf01f92d88
  Register logger into interaction of 1e7a574ca40c4bfc907407bf01f92d88, done!
  Register io into interaction of 1e7a574ca40c4bfc907407bf01f92d88, done!
  Register db into interaction of 1e7a574ca40c4bfc907407bf01f92d88, done!
  Register logger into XAgentServer of 1e7a574ca40c4bfc907407bf01f92d88, done!
  Start a new thread to run interaction of 1e7a574ca40c4bfc907407bf01f92d88, done!
Constructing an AgentDispatcher:  XAgentDispatcher
---config file---
assets/config_gpt4_8k.yml
---args---
{'record_dir': 'finance_manager_records', 'default_completion_kwargs': {'model': 'gpt-4', 'temperature': 0.2, 'request_timeout': 60}, 'enable_ask_human_for_help': True, 'max_subtask_chain_length': 7, 'max_plan_refine_chain_length': 3, 'max_plan_tree_depth': 3, 'max_plan_tree_width': 5, 'max_retry_times': 3}
load from a disk record, overwrite all the existing config-info  finance_manager_records
Traceback (most recent call last):
  File "/Users/fredrikbranstrom/Dropbox/Code/XAgent/run.py", line 53, in <module>
    cmd.start(
  File "/Users/fredrikbranstrom/Dropbox/Code/XAgent/command.py", line 163, in start
    self.run({
  File "/Users/fredrikbranstrom/Dropbox/Code/XAgent/command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/Users/fredrikbranstrom/miniconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/fredrikbranstrom/miniconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fredrikbranstrom/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/fredrikbranstrom/Dropbox/Code/XAgent/XAgentServer/server.py", line 40, in interact
    recorder.load_from_disk(interaction.base.recorder_root_dir)
  File "/Users/fredrikbranstrom/Dropbox/Code/XAgent/XAgent/running_recorder.py", line 250, in load_from_disk
    raise NotImplementedError
NotImplementedError
 ~code/XAgent ⚡️
```

User in discord also report that.

**Comment by luyaxi** [comment]
Please make sure you use the latest code to generate the records and load it, the old code has broken record loader.

**Comment by luyaxi** [comment]
We've update the logic in loading records, now it should be able to reload correctly! Thank you for your comments!

**Comment by SmellyBones** [comment]
@luyaxi i updated my code 2x because i saw you commented that a change was made. after deleteing my xagent folder and doing another git clone command. i copied the path into the record_dir. i tried on just the config.yml at first then added the path into gpt4 config and gpt3.5 config. i added the path to all 3 as a final attempt but it didnt work. heres the error i got.           

C:\Users\deadb\XAgent>python run.py --task "did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?" --model gpt-4 --config_file assets/config.yml
XAgentServer is running on cmd mode
XAgentServer log:  XAgentServer\localstorage\interact_records\2023-10-25\f9ce94add4584a30add147faa298fb97
  init localstorage connection: interaction.json
-=-=--=-=-=-=-=-=-= Current Instruction =-=-=-=-=-=-=-=-=-=-=-=-=-=-
did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?
Receive args from f9ce94add4584a30add147faa298fb97:   user_id: admin, token: xagent-admin, description: XAgent-Test
Receive data from f9ce94add4584a30add147faa298fb97:   did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?
  Register parameter: {'interaction_id': 'f9ce94add4584a30add147faa298fb97', 'parameter_id': 'c11d591b5c9c43d1865bb36514eeaac3', 'args': {'description': 'XAgent-Test', 'role_name': 'Assistant', 'download_files': [], 'file_list': None, 'record_dir': None, 'goal': 'did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?', 'mode': 'auto', 'plan': [], 'max_wait_seconds': 600}} into interaction of f9ce94add4584a30add147faa298fb97, done!
  init interaction: f9ce94add4584a30add147faa298fb97
  Register logger into interaction of f9ce94add4584a30add147faa298fb97, done!
  Register io into interaction of f9ce94add4584a30add147faa298fb97, done!
  Register db into interaction of f9ce94add4584a30add147faa298fb97, done!
  Register logger into XAgentServer of f9ce94add4584a30add147faa298fb97, done!
  Start a new thread to run interaction of f9ce94add4584a30add147faa298fb97, done!
Constructing an AgentDispatcher:  XAgentDispatcher
---config file---
assets/config.yml
---args---
{'task': 'did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?', 'default_completion_kwargs': {'model': 'gpt-4', 'temperature': 0.2, 'request_timeout': 60}, 'mode': 'auto', 'quiet': False, 'enable_ask_human_for_help': False, 'config_file': 'assets/config.yml'}
load from a disk record, overwrite all the existing config-info  C:\Users\deadb\OneDrive\Desktop\running_records\2023_10_25_19_07_364e5981a0
---config file---
assets/config.yml
---args---
{'task': 'did you finish the request i asked for? did you find the waether in the place i asked about? what was the weather there?', 'default_completion_kwargs': {'model': 'gpt-4', 'temperature': 0.2, 'request_timeout': 60}, 'mode': 'auto', 'quiet': False, 'enable_ask_human_for_help': False, 'config_file': 'assets/config.yml'}
Traceback (most recent call last):
  File "C:\Users\deadb\XAgent\run.py", line 52, in <module>
    cmd.start(
  File "C:\Users\deadb\XAgent\command.py", line 163, in start
    self.run({
  File "C:\Users\deadb\XAgent\command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\deadb\XAgent\XAgentServer\server.py", line 41, in interact
    recorder.load_from_disk(interaction.base.recorder_root_dir)
  File "C:\Users\deadb\XAgent\XAgent\running_recorder.py", line 222, in load_from_disk
    self.llm_server_cache[inout_id] = llm_pair
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list assignment index out of range

**Comment by luyaxi** [comment]
It seems that you have a broken running records, can you remove all sensitive info in the records and upload the records? By the way, the records is used to replay actions, not start new task from a old running.

**Comment by SmellyBones** [comment]
![Screenshot 2023-10-25 202856](https://github.com/OpenBMB/XAgent/assets/148628888/13df9d2c-f9c1-481f-b55b-117158a94ed9)
 
i might have a misunderstanding of how it worked then. heres a screen shot of what was loaded in the  from the run. the this-is-a-reload-run.yml only has the path to the file i gave it. i will send you what is needed, im not sure what to send you though.

**Comment by luyaxi** [comment]
Try to use your origin running records rather than reload running records (as your screenshot shows, you are trying to load a reloaded running records). The reloaded running records is not ready for reload again yet.

**Comment by semikolon** [comment]
@luyaxi Hmm

"the records is used to replay actions, not start new task from a old running"

I wonder if I misunderstood then as well...

I have the following problem: I tested XAgent two days ago with a task of creating a "finance manager" Vue application based on a Ruby script I had been using in the past, which I uploaded. I had input my API keys for GPT-4 (8k) and GPT-3.5 (16k). I set the default model to GPT-4. But didn't realize I had to remove the config section where it had example API keys for GPT-4 32k which are irrelevant because I don't have access to 32k.

So when it ran, it finished a few subtasks, installed node and npm and vue-cli etc and created a bunch of Vue components, but then eventually it failed due to running out of tokens. Having read the code now, I see that it will try to use the (non-default) 32k GPT-4 when that happens, or if that API key doesn't seem to be available, it will try to use the 16k GPT-3.5 to be able to work with the larger context.

I had mistakenly left the config example for 32k GPT-4 so it tried to use that but ultimately failed.

Now, yesterday I was able to figure out how to replay an old record. I copied a datetime-marked subdirectory (cp -r) from inside running_records and put it in a separate directory named finance_manager_records and referenced that.

It was able to go forward with the replay, except when it came to accessing the workspace. As you can see by the logs, when it finishes replaying the recorded steps and resumes making actual calls, there's something wrong with the workspace writing/reading:

[Some of the logs from the replay run](https://github.com/OpenBMB/XAgent/files/13174974/message.3.txt)

I think this is the primary type of error occurring:

```
NEXT ACTION:  COMMAND: FileSystemEnv_write_to_file ARGUMENTS: {'filepath': 'finance-manager/src/components/DisplayFinance.vue', 'content': 'mock content', 'line_number': 25, 'overwrite': True}
SYSTEM:  Command FileSystemEnv_write_to_file returned: {"detail":"Traceback (most recent call last):\n File \"/app/main.py\", line 171, in execute_tool\n result = tool(**arguments)\n File \"/app/core/envs/filesystem.py\", line 176, in write_to_file\n raise FileNotFoundError(f\"File {filepath} not found in workspace.\")\nFileNotFoundError: File finance-manager/src/components/DisplayFinance.vue not found in workspace.\n"}
TOOL STATUS CODE:  TOOL_CALL_FAILED
```

**Comment by luyaxi** [comment]
Y、

> @luyaxi Hmm
> 
> "the records is used to replay actions, not start new task from a old running"
> 
> I wonder if I misunderstood then as well...
> 
> I have the following problem: I tested XAgent two days ago with a task of creating a "finance manager" Vue application based on a Ruby script I had been using in the past, which I uploaded. I had input my API keys for GPT-4 (8k) and GPT-3.5 (16k). I set the default model to GPT-4. But didn't realize I had to remove the config section where it had example API keys for GPT-4 32k which are irrelevant because I don't have access to 32k.
> 
> So when it ran, it finished a few subtasks, installed node and npm and vue-cli etc and created a bunch of Vue components, but then eventually it failed due to running out of tokens. Having read the code now, I see that it will try to use the (non-default) 32k GPT-4 when that happens, or if that API key doesn't seem to be available, it will try to use the 16k GPT-3.5 to be able to work with the larger context.
> 
> I had mistakenly left the config example for 32k GPT-4 so it tried to use that but ultimately failed.
> 
> Now, yesterday I was able to figure out how to replay an old record. I copied a datetime-marked subdirectory (cp -r) from inside running_records and put it in a separate directory named finance_manager_records and referenced that.
> 
> It was able to go forward with the replay, except when it came to accessing the workspace. As you can see by the logs, when it finishes replaying the recorded steps and resumes making actual calls, there's something wrong with the workspace writing/reading:
> 
> [Some of the logs from the replay run](https://github.com/OpenBMB/XAgent/files/13174974/message.3.txt)
> 
> I think this is the primary type of error occurring:
> 
> ```
> NEXT ACTION:  COMMAND: FileSystemEnv_write_to_file ARGUMENTS: {'filepath': 'finance-manager/src/components/DisplayFinance.vue', 'content': 'mock content', 'line_number': 25, 'overwrite': True}
> SYSTEM:  Command FileSystemEnv_write_to_file returned: {"detail":"Traceback (most recent call last):\n File \"/app/main.py\", line 171, in execute_tool\n result = tool(**arguments)\n File \"/app/core/envs/filesystem.py\", line 176, in write_to_file\n raise FileNotFoundError(f\"File {filepath} not found in workspace.\")\nFileNotFoundError: File finance-manager/src/components/DisplayFinance.vue not found in workspace.\n"}
> TOOL STATUS CODE:  TOOL_CALL_FAILED
> ```

Currently the replay does not regain the workspace, we will add a feature to replay the actions in the `toolservernode` to ensure the workspace is same.

**Comment by semikolon** [comment]
Ok. Can I just copy them into the workspace, or upload them? Is there a workaround so I can continue the work on this project, with the state of the workspace as it was right before the last run failed?

**Comment by semikolon** [comment]
Cool, I'll try it.

Also another thing: I had trouble using a custom config path. It seems to me (after reading the code of run.py) that you might be loading the config from the default path before loading the custom config?

**Comment by luyaxi** [comment]
> Cool, I'll try it.
> 
> Also another thing: I had trouble using a custom config path. It seems to me (after reading the code of run.py) that you might be loading the config from the default path before loading the custom config?

Can you provide more specific description with your run's arguments and your config file in a new issue? Please remove sensitive information before you submit the issue.
