### ISSUE TITLE
How to access local files in XAgent?

### ISSUE THREAD

**Issue by iamlockelightning** [OpenBMB/XAgent#11]
I want XAgent to read a local file (given a related path) and process it. Where should I place the file? 

(Is this a supported feature?)

(I tried to place it in `local_workspace`, but XAgent can't find it and downloaded a weird one from the Internet)

**Comment by luyaxi** [comment]
You can use argument `--upload_files` to upload your files to XAgent. You can check the detailed usage of `run.py` with `python run.py --help`
