### ISSUE TITLE
docker-compose up运行后身份验证有误，monitor容器运行不起来

### ISSUE THREAD

**Issue by shalimujiang** [OpenBMB/XAgent#111]
## Issue Description / 问题描述
docker-compose up运行后身份验证有误，monitor容器运行不起来

## Steps to Reproduce / 复现步骤
无

## Expected Behavior / 预期行为
无

## Environment / 环境信息
- Operating System / 操作系统：ubuntu20.04
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：
Docker version 24.0.6, build ed223bc
docker-compose --version
docker-compose version 1.29.2, build unknown

## Error Screenshots or Logs / 错误截图或日志
![image](https://github.com/OpenBMB/XAgent/assets/75249643/6b8cefcb-4735-4d44-b0f0-360399dc525c)

docker-compose up
Pulling db (mongo:)...
latest: Pulling from library/mongo
43f89b94cd7d: Downloading [==================================================>]  30.44MB/30.44MB
43f89b94cd7d: Pull complete
54a7480baa9d: Pull complete
7f9301fbd7df: Pull complete
5e4470f2e90f: Pull complete
40d046ff8fd3: Pull complete
e062d62b861e: Pull complete
72919e34fde8: Pull complete
ab22810dfc64: Pull complete
fb05c29fbdf5: Pull complete
Digest: sha256:d341a86584b96eb665345a8f5b35fba8695ee1d0618fd012ec4696223a3d6c62
Status: Downloaded newer image for mongo:latest
Creating XAgent-Server              ... done
Creating xagent_db_1             ... done
Creating xagent_ToolServerNode_1    ... done
Creating xagent_ToolServerManager_1 ... done
Creating xagent_ToolServerMonitor_1 ... done
Attaching to XAgent-Server, xagent_ToolServerNode_1, xagent_ToolServerMonitor_1, xagent_ToolServerManager_1
XAgent-Server        | INFO:     Will watch for changes in these directories: ['/app']
XAgent-Server        | INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
XAgent-Server        | INFO:     Started reloader process [1] using StatReload
ToolServerNode_1     | Build complete. Exiting...
xagent_ToolServerNode_1 exited with code 0
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [1] [INFO] Starting gunicorn 21.2.0
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [7] [INFO] Booting worker with pid: 7
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [8] [INFO] Booting worker with pid: 8
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [9] [INFO] Booting worker with pid: 9
ToolServerMonitor_1  | INFO:     Database connected
ToolServerMonitor_1  | INFO:     Docker client connected
ToolServerManager_1  | [2023-10-25 15:40:05 +0000] [10] [INFO] Booting worker with pid: 10
ToolServerMonitor_1  | Traceback (most recent call last):
ToolServerMonitor_1  |   File "/app/main.py", line 46, in <module>
ToolServerMonitor_1  |     asyncio.run(check_nodes_status_loop())
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
ToolServerMonitor_1  |     return loop.run_until_complete(main)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
ToolServerMonitor_1  |     return future.result()
ToolServerMonitor_1  |   File "/app/main.py", line 42, in check_nodes_status_loop
ToolServerMonitor_1  |     await check_nodes_status()
ToolServerMonitor_1  |   File "/app/main.py", line 12, in check_nodes_status
ToolServerMonitor_1  |     async for node in nodes:
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 1390, in next
ToolServerMonitor_1  |     if self.alive and (self._buffer_size() or await self._get_more()):
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ToolServerMonitor_1  |     result = self.fn(*self.args, **self.kwargs)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1179, in _refresh
ToolServerMonitor_1  |     self.__send_message(q)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1060, in __send_message
ToolServerMonitor_1  |     response = client._run_operation(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
ToolServerMonitor_1  |     return func(self, *args, **kwargs)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation
ToolServerMonitor_1  |     return self._retryable_read(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
ToolServerMonitor_1  |     return func(self, *args, **kwargs)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1526, in _retryable_read
ToolServerMonitor_1  |     with self._conn_from_server(read_pref, server, session) as (
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
ToolServerMonitor_1  |     return next(self.gen)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1324, in _conn_from_server
ToolServerMonitor_1  |     with self._checkout(server, session) as conn:
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
ToolServerMonitor_1  |     return next(self.gen)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1246, in _checkout
ToolServerMonitor_1  |     with server.checkout(handler=err_handler) as conn:
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
ToolServerMonitor_1  |     return next(self.gen)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1598, in checkout
ToolServerMonitor_1  |     conn = self._get_conn(handler=handler)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1714, in _get_conn
ToolServerMonitor_1  |     conn = self.connect(handler=handler)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1568, in connect
ToolServerMonitor_1  |     conn.authenticate()
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1042, in authenticate
ToolServerMonitor_1  |     auth.authenticate(creds, self, reauthenticate=reauthenticate)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 616, in authenticate
ToolServerMonitor_1  |     auth_func(credentials, conn)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 521, in _authenticate_default
ToolServerMonitor_1  |     return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 248, in _authenticate_scram
ToolServerMonitor_1  |     res = conn.command(source, cmd)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 315, in inner
ToolServerMonitor_1  |     return func(*args, **kwargs)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 932, in command
ToolServerMonitor_1  |     return command(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/network.py", line 191, in command
ToolServerMonitor_1  |     helpers._check_command_response(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 223, in _check_command_response
ToolServerMonitor_1  |     raise OperationFailure(errmsg, code, response, max_wire_version)
ToolServerMonitor_1  | pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
XAgent-Server        | INFO:     Started server process [8]
XAgent-Server        | INFO:     Waiting for application startup.
XAgent-Server        | INFO:     Application startup complete.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [8] [INFO] Started server process [8]
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [8] [INFO] Waiting for application startup.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [7] [INFO] Started server process [7]
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [7] [INFO] Waiting for application startup.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [8] [INFO] Application startup complete.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [7] [INFO] Application startup complete.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [10] [INFO] Started server process [10]
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [10] [INFO] Waiting for application startup.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [10] [INFO] Application startup complete.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [9] [INFO] Started server process [9]
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [9] [INFO] Waiting for application startup.
ToolServerManager_1  | [2023-10-25 15:40:06 +0000] [9] [INFO] Application startup complete.
xagent_ToolServerMonitor_1 exited with code 1

## Additional Notes / 其他备注
无

**Comment by luyaxi** [comment]
Make sure the password you configured for database does not include special tokens

**Comment by yuanzhiyong1999** [comment]
我也是这个问题

**Comment by shalimujiang** [comment]
> 我也是这个问题

等你解决，加油

**Comment by Arcane-Mage** [comment]
> 我也是这个问题

可能是之前用错误的用户名和密码创建了数据库，后续再怎么修改都不行。
试一下删除创建好的 mongodb 数据库文件，导入.env 文件，然后重新build

**Comment by sjqgogogo** [comment]
我遇到了同样的问题，我是通过进入mongo db容器并手动创建用户来解决的问题。

启动服务
docker compose up

查看容器
docker ps | grep mongo 

进入容器
docker exec -it 容器id bash 

创建用户
mongosh
use admin
db.createUser({
  user: "admin",
  pwd: "xagentmongodb",
  roles: ["root" ]
})

然后重新启动服务即可
docker compose up
