### ISSUE TITLE
是否可以补充一个整体的架构图

### ISSUE THREAD

**Issue by ticoAg** [OpenBMB/XAgent#113]
如题，是否可以在README里添加一个整体架构图，清晰的展示，类似
![image](https://github.com/OpenBMB/XAgent/assets/73207855/ed27bcb7-c85c-46a0-8b67-a847d91a0784)

**Comment by Kunlun-Zhu** [comment]
感谢您的建议，已在Readme中补充相关设计图描述

**Comment by Umpire2018** [comment]
The inner loop and outer loop mechanism of XAgent may fit with your requirement.

**Comment by wangwangzuge** [comment]
@Kunlun-Zhu  这个图是用什么工具画的
![image](https://github.com/OpenBMB/XAgent/assets/138180816/457bc02f-90b4-4dd3-8df1-92b60489444b)

**Comment by Kunlun-Zhu** [comment]
> @Kunlun-Zhu 这个图是用什么工具画的 ![image](https://user-images.githubusercontent.com/138180816/279335680-457bc02f-90b4-4dd3-8df1-92b60489444b.png)

这张图由用户：”imclumsypanda“绘制；具体工具不太清楚
