### ISSUE TITLE
if run it with docker,how to run it with gpt-3.5 

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [OpenBMB/XAgent#115]
现在我使用docker进行启动，
在 config.yml中配置有3.5，4的key
![image](https://github.com/OpenBMB/XAgent/assets/87591236/e622e960-f04f-4fbc-afbc-27232e2b3a9e)
![image](https://github.com/OpenBMB/XAgent/assets/87591236/33e02cb8-5559-4737-8721-dc6fc17a464f)
但是现在我要用3.5的模型来运行，
所以在sudo docker-compose up 之前，我只需要填写3.5的key，就可以了吗

**Comment by shalimujiang** [comment]
![image](https://github.com/OpenBMB/XAgent/assets/75249643/90443710-e853-4f38-b8f4-0c3e68131904)
