### ISSUE TITLE
如果用一个apikey来完成某一个任务，openai官方因为请求过多而进行限制访问，是否增加一个多个apikey轮训访问

### ISSUE THREAD

**Issue by shalimujiang** [OpenBMB/XAgent#116]
## Feature Description / 功能描述
**原因如下图：**
![2023-10-26_14-02-08](https://github.com/OpenBMB/XAgent/assets/75249643/71031ead-b24e-4bb9-a597-4dd2253917df)

## Goal / 目标
1，多个apikey解决一个XAgent完成任务时间过长的问题,

## Expected Behavior / 预期行为
1，一个号多次请求肯定会被官方限制，希望增加apikey请求限制，达到次数了换另一个apikey。如果是多个号，轮训。

## Alternative Solutions / 其他解决方案
解决方案参考资源池，并行任务之类的？

## Additional Notes / 其他备注
**这样做有几个缺点：**
1，费用问题：每个API密钥都与一定的费用相关联。同时使用多个API密钥会增加总体费用。如果需求者考虑XAgent响应时间短的话，应该不会考虑这方面的问题。
2，数据一致性：如果多个API密钥同时进行相同的任务，由于每此请求的数据可能不同，它们的输出可能会稍有差异。因此，需要小心处理并合并来自不同API密钥的结果。
3，管理复杂性：同时使用多个API密钥会增加XAgent智能体的管理复杂性。

**Comment by luyaxi** [comment]
你可以在api_keys中为某个model添加任意数量的key，请按yaml的列表格式组织他们。初版程序已支持多API轮询功能。
