### ISSUE TITLE
package.json的scripts中没有server

### ISSUE THREAD

**Issue by LOGIC-10** [OpenBMB/XAgent#12]
运行这一步的时候：
cd ../XAgentWeb
npm install
npm run serve

遇到报错：

npm ERR! Missing script: "serve"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/logic/.npm/_logs/2023-10-18T03_07_41_621Z-debug-0.log

进入XAgentWeb/package.json查看代码，发现
![image](https://github.com/OpenBMB/XAgent/assets/62985169/fc58ee13-0ecb-4d0d-9846-e310929b7fab)
确实没有server健值对。

请问如何解决这个问题？谢谢！

**Comment by shalimujiang** [comment]
npm run dev?

**Comment by ChengFai** [comment]
npm run dev 可以自己在本地启动，其他的script会后续删除
