### ISSUE TITLE
docker compose failed <apt-get>

### ISSUE THREAD

**Issue by lionday** [OpenBMB/XAgent#125]
## Issue Description / 问题描述
docker compose up执行的过程中，在执行XAgentServer的dockerfile的时候报错。
错误：
 => ERROR [XAgentServer xagentserver  4/14] RUN apt-get install -y nginx systemctl
 ------
 > [XAgentServer xagentserver  4/14] RUN apt-get install -y nginx systemctl:
0.574 Reading package lists...
0.589 Building dependency tree...
0.591 Reading state information...
0.591 E: Unable to locate package nginx
0.591 E: Unable to locate package systemctl
------
failed to solve: process "/bin/sh -c apt-get install -y nginx systemctl" did not complete successfully: exit code: 100

## Steps to Reproduce / 复现步骤
docker compose up / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by sailaoda** [comment]
您好，这种情况可能是网络问题导致上一步apt update未更新，您可以清除已经走过的docker后重新build将会解决这个问题。

**Comment by lionday** [comment]
非常感谢！确实是上一步update的原因。我清除过几次，结果都是一样的，后来加了-y 选项就可以了。
