### ISSUE TITLE
gpt3.5 接口调用失败

### ISSUE THREAD

**Issue by ZSCDumin** [OpenBMB/XAgent#127]
![image](https://github.com/OpenBMB/XAgent/assets/19670365/25a91b1b-4111-4906-b1ea-1ab5cd755a1a)

openai.error.APIError: Invalid response object from API: '{"message":"ENDPOINT ERROR","type":"invalid_request_error","param":"endpoint","code":"invalid_request_error","endpoint":["/v1/chat/completions","/v1/completions","/v1/embeddings","/v1/moderations"]}\n' (HTTP response code was 404)
chatcompletion error: Invalid response object from API: '{"message":"ENDPOINT ERROR","type":"invalid_request_error","param":"endpoint","code":"invalid_request_error","endpoint":["/v1/chat/completions","/v1/completions","/v1/embeddings","/v1/moderations"]}\n' (HTTP response code was 404)

**Comment by Umpire2018** [comment]
试下使用 `api_base: http://api.openai-hk.com`

**Comment by Umpire2018** [comment]
该位置为 azure 使用，请将 `api_base` 与 `key` 配置在正确位置并参照以下
```
    - api_key: sk-xxxxx
      api_base: 
      model: gpt-3.5-turbo-16k
```

**Comment by ZSCDumin** [comment]
> 该位置为 azure 使用，请将 `api_base` 与 `key` 配置在正确位置并参照以下
> 
> ```
>     - api_key: sk-xxxxx
>       api_base: 
>       model: gpt-3.5-turbo-16k
> ```

香港的key不行吗？
