### ISSUE TITLE
github action CI

### ISSUE THREAD

**Issue by FlatMapIO** [OpenBMB/XAgent#131]
## Feature Description / 功能描述

因为网络原因，在本地构建 docker 镜像可能会有很多意外， 建议使用 github action 构建镜像并推送到 hub.docker.com

## Goal / 目标

- 通过 CI 提前发现 main 分支的集成问题
- 减少构建相关的问题
- 避免打开此类 issue

## Expected Behavior / 预期行为

`docker compose up` 可以通过拉取镜像启动而不是在本地构建

## Alternative Solutions / 其他解决方案
无

## Additional Notes / 其他备注

我在自己的[仓库](https://github.com/FlatMapIO/xagent-docker)中创建了 github action 构建，能正常启动但无法访问 UI

**Comment by Umpire2018** [comment]
https://github.com/OpenBMB/XAgent/issues/2#issuecomment-1766137117
