### ISSUE TITLE
typo in the readme

### ISSUE THREAD

**Issue by Lodaresole** [OpenBMB/XAgent#133]
## Issue Description / 问题描述

There is a typo in the readme

ToolServer/README.md

https://github.com/OpenBMB/XAgent/blob/main/ToolServer/README.md#%EF%B8%8F-build-and-setup-toolserver

## Error Screenshots or Logs / 错误截图或日志
![image](https://github.com/OpenBMB/XAgent/assets/91383072/1da39f44-ffd2-4be9-b695-d473e8b9a11f)

**Comment by Umpire2018** [comment]
Thanks for pointing out. Please open a pull request.
