### ISSUE TITLE
How can see log request to function execute_tool. I fail request at it

### ISSUE THREAD

**Issue by hungptit123** [OpenBMB/XAgent#135]
## Environment / 环境信息
- Operating System : Linux
- Python Version / Python 版本：3.10

THOUGHTS:  I will start by searching for articles and tutorials about chatbot development
REASONING:  By researching articles and tutorials, I can gain an understanding of the process and steps involved in developing a chatbot for a website
PLAN: 
-  Read articles and tutorials about chatbot development
-  Understand the different technologies used in chatbot development
-  Identify the steps involved in developing a chatbot for a website
-  Explore existing chatbot development platforms and frameworks
CRITICISM:  It is important to gather as much information as possible to ensure that I have a comprehensive understanding of chatbot development
NEXT ACTION:  COMMAND: WebEnv_search_and_browse ARGUMENTS: {'search_query': 'chatbot development articles and tutorials', 'goals_to_browse': 'Find resources to read about chatbot development'}
SYSTEM:  Command WebEnv_search_and_browse returned: {"detail":"Traceback (most recent call last):\n File \"/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py\", line 189, in connect_tcp\n addr_obj = ip_address(remote_host)\n File \"/usr/local/lib/python3.10/ipaddress.py\", line 54, in ip_address\n raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')\nValueError: 'api.bing.microsoft.com' does not appear to be an IPv4 or IPv6 address\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 10, in map_exceptions\n yield\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 114, in connect_tcp\n stream: anyio.abc.ByteStream = await anyio.connect_tcp(\n File \"/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py\", line 192, in connect_tcp\n gai_res = await getaddrinfo(\n File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n result = self.fn(*self.args, **self.kwargs)\n File \"/usr/local/lib/python3.10/socket.py\", line 955, in getaddrinfo\n for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 66, in map_httpcore_exceptions\n yield\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 366, in handle_async_request\n resp = await self._pool.handle_async_request(req)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 262, in handle_async_request\n raise exc\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 245, in handle_async_request\n response = await connection.handle_async_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 99, in handle_async_request\n raise exc\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 76, in handle_async_request\n stream = await self._connect(request)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 124, in _connect\n stream = await self._network_backend.connect_tcp(**kwargs)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py\", line 31, in connect_tcp\n return await self._backend.connect_tcp(\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 112, in connect_tcp\n with map_exceptions(exc_map):\n File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n self.gen.throw(typ, value, traceback)\n File \"/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py\", line 14, in map_exceptions\n raise to_exc(exc) from exc\nhttpcore.ConnectError: [Errno -3] Temporary failure in name resolution\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File \"/app/main.py\", line 173, in execute_tool\n result = await result\n File \"/app/core/envs/web.py\", line 69, in search_and_browse\n result = await self.client.get(endpoint,\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1757, in get\n return await self.request(\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1530, in request\n return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1617, in send\n response = await self._send_handling_auth(\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1645, in _send_handling_auth\n response = await self._send_handling_redirects(\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1682, in _send_handling_redirects\n response = await self._send_single_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_client.py\", line 1719, in _send_single_request\n response = await transport.handle_async_request(request)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 365, in handle_async_request\n with map_httpcore_exceptions():\n File \"/usr/local/lib/python3.10/contextlib.py\", line 153, in __exit__\n self.gen.throw(typ, value, traceback)\n File \"/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py\", line 83, in map_httpcore_exceptions\n raise mapped_exc(message) from exc\nhttpx.ConnectError: [Errno -3] Temporary failure in name resolution\n"}
TOOL STATUS CODE:  TOOL_CALL_FAILED

**Comment by hungptit123** [comment]
quizzical_engelbart                      | Traceback (most recent call last):
quizzical_engelbart                      |   File "/usr/local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
quizzical_engelbart                      |     addr_obj = ip_address(remote_host)
quizzical_engelbart                      |   File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
quizzical_engelbart                      |     raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
quizzical_engelbart                      | ValueError: 'api.bing.microsoft.com' does not appear to be an IPv4 or IPv6 address
quizzical_engelbart                      | 
quizzical_engelbart                      | During handling of the above exception, another exception occurred:
quizzical_engelbart                      |

**Comment by luyaxi** [comment]
Please check your network to utilize the `WebEnv_search_and_browse` tool, the log for tools is stored in the `running_records/20xx_xx_xxxxx/tool_server_pair`
