### ISSUE TITLE
Adding code-of-conduct to repo. 

### ISSUE THREAD

**Issue by mohitd404** [OpenBMB/XAgent#138]
## Feature Description / 功能描述
Code-Of-Conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure
 a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, 
and attracting a wider range of perspectives.

## Goal / 目标
Explain the goal you hope to achieve to ensure
 a safe, respectful, and inclusive environment for all contributors and users.

@Umpire2018 kindly assign this issue to me ! thank you !

**Comment by Umpire2018** [comment]
Thank you for proposing the addition of a Code of Conduct to our repository. Your initiative towards promoting a safe, respectful, and inclusive environment is commendable. However, we'll be carefully deliberating on this internally and make decisions based on our own considerations. Appreciate your understanding and input!
