### ISSUE TITLE
dev服务启动后在本地浏览器登录和注册报错

### ISSUE THREAD

**Issue by LOGIC-10** [OpenBMB/XAgent#14]
运行最后一部命令：npm run dev                                                               

> xagent@0.0.0 dev
> vite --host

                                                                                                                                                        13:48:15
  VITE v4.4.11  ready in 1384 ms

  ➜  Local:   http://localhost:5173/                                                                                                                    13:48:15
  ➜  Network: http://10.118.154.209:5173/                                                                                                               13:48:15
  ➜  press h to show help    

在网页点击登录或者注册引发报错：

ERROR  14:02:29 [vite] http proxy error at /api/login:                                                                                                 14:02:29
Error: connect ECONNREFUSED 127.0.0.1:16204
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) (x11)

 ERROR  14:03:08 [vite] http proxy error at /api/register:                                                                                              14:03:08
Error: connect ECONNREFUSED 127.0.0.1:16204
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

<img width="826" alt="image" src="https://github.com/OpenBMB/XAgent/assets/62985169/68a5bf1f-b8bc-468c-8319-f21c44638f86">
网页界面，点击没反应但是在命令行报错。
请问如何解决

**Comment by sailaoda** [comment]
Thanks for your advice, it will work now.

**Comment by destroy314** [comment]
没有[启动后端](https://github.com/OpenBMB/XAgent/blob/main/XAgentServer/README_zh.md#启动-xagent-server)时注册和登录遇到了同样的报错。

**Comment by sailaoda** [comment]
您好，本地部署是需要启动后端的。或者您想体验我们的演示环境可以在 x-agent.net 进行注册并登录。
