### ISSUE TITLE
Integration with MemGPT

### ISSUE THREAD

**Issue by Binaryxz** [OpenBMB/XAgent#140]
## Feature Description / 功能描述
Integrate the model with MemGPT for long-term memory.

## Goal / 目标
In addition to long-term memory, having the agent manage its own memory like an operating system can make it more efficient by remembering tasks already carried out a while ago and bringing aspects of them to new ones.

## Expected Behavior / 预期行为
The agent remembers and manages actions and task requests according to previous memory or during an interaction, reducing errors and increasing remembering capabilities similar to a human.

## Alternative Solutions / 其他解决方案
https://github.com/daveshap/SparsePrimingRepresentations/tree/main#sparse-priming-representations-spr

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
Please refer to #162
