### ISSUE TITLE
 docker-compose up 找不到moby/buildkit:buildx-stable-1

### ISSUE THREAD

**Issue by wilac-pv** [OpenBMB/XAgent#142]
## Environment / 环境信息
Linux VM-8-2-centos 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

## Error Screenshots or Logs / 错误截图或日志
docker-compose up
[+] Running 0/4
 ⠼ ToolServerMonitor Pulling                                                                                                     14.3s 
 ⠸ XAgentServer Pulling                                                                                                          14.3s 
 ⠸ ToolServerManager Pulling                                                                                                     14.3s 
 ⠸ ToolServerNode Pulling                                                                                                        14.3s 
[+] Building 10.0s (4/4) FINISHED                                                                             docker-container:default
 => CANCELED [XAgentServer internal] booting buildkit                                                                            10.0s
 => => pulling image moby/buildkit:buildx-stable-1                                                                               10.0s
 => ERROR [ToolServerManager internal] booting buildkit                                                                          10.0s
 => => pulling image moby/buildkit:buildx-stable-1                                                                               10.0s
 => => creating container buildx_buildkit_default                                                                                 0.0s
 => CANCELED [ToolServerMonitor internal] booting buildkit                                                                       10.0s
 => => pulling image moby/buildkit:buildx-stable-1                                                                               10.0s
 => CANCELED [ToolServerNode internal] booting buildkit                                                                          10.0s
 => => pulling image moby/buildkit:buildx-stable-1                                                                               10.0s
------
 > [ToolServerManager internal] booting buildkit:
------
Error response from daemon: No such image: moby/buildkit:buildx-stable-1

**Comment by Umpire2018** [comment]
Please use another environment like `Github-Codespace` and try again.
