### ISSUE TITLE
ToolServerNode容器无法启动

### ISSUE THREAD

**Issue by ALEX-X36** [OpenBMB/XAgent#143]
## Issue Description / 问题描述
构建的ToolServerNode无法启动，启动直接提示Build complete. Exiting...
docker compose up过程中可能有问题
第一次compose up时有一部分时间很长我直接ctrl + c停止过程序，之后在进行 up，报错了几次，docker compose build之后再进行up 没有报错，但是构建出来的note容器无法启动
## Steps to Reproduce / 复现步骤
不确定是怎么触发的，

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：Windows 11
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
这是正常的行为，因为此容器不会被使用。
