### ISSUE TITLE
上传文件会卡死以及在浏览器中交互无反馈

### ISSUE THREAD

**Issue by xiaog929** [OpenBMB/XAgent#144]
![image](https://github.com/OpenBMB/XAgent/assets/75246377/1fa4dda6-7832-4315-9d5b-62e6519dcfb0)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/946e3094-cfab-43fa-b97f-b1bd0c5b03af)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/d1b9c23b-a176-42ad-817a-9af9d20b0802)
1.第一个问题是页面加载后上传文件会直接导致页面卡死
2.第二个问题是提问的时候长时间无响应，F12查看也没有拒绝访问的端口，后台提示连接超时

**Comment by ChengFai** [comment]
针对问题2，请求对话使用的是websocket，点击调试工具 network -> ws查看连接和对话状态，您看看对话发出去了吗，后续会更新代码提供更多的报错详细信息。

**Comment by ChengFai** [comment]
针对问题1，请toolserver同学帮忙解答

**Comment by luyaxi** [comment]
请使用'docker composed build'构建最新镜像，并提供toolserver的log信息以明确上传文件时的异常。长久等待问题似乎是由于你的网络连接问题，你需要确定你的网络能够访问openai的服务

**Comment by xiaog929** [comment]
> 针对问题2，请求对话使用的是websocket，点击调试工具网络->ws查看连接和对话状态，您看看对话发出去了吗，后续会更新代码提供更多的报错详细信息。
![image](https://github.com/OpenBMB/XAgent/assets/75246377/be49d30d-1bc3-4cde-856d-e6e950fafbe9)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/91a43ca6-be07-4509-80fd-75dd531d1744)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/5c9a28a3-57ee-4a51-b774-2d8e2b90b0ac)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/cdd38ad1-2d16-4b0e-b438-3d92036af010)

然后上传文件卡死就是一选择文件，然后整个页面就卡死了，后台也没日志，甚至F12调试工具都嗯不出来

**Comment by Umpire2018** [comment]
Repeat: 长久等待问题似乎是由于你的网络连接问题，你需要确定你的网络能够访问openai的服务
