### ISSUE TITLE
ToolServer路径下执行 docker-compose up 在下载jdk17和jre17时连接失败

### ISSUE THREAD

**Issue by yanyvgongzuoshi** [OpenBMB/XAgent#146]
## Issue Description / 问题描述
ToolServer路径下执行 docker-compose up 在下载jdk17和jre17时连接失败，但在浏览器里访问链接可以下载

## Steps to Reproduce / 复现步骤
在ToolServer路径下执行 docker-compose up

## Environment / 环境信息
- Operating System / 操作系统：Windos11 22H2 ；Docker Desktop v4.25.0
- Python Version / Python 版本：3.10

## Error Screenshots or Logs / 错误截图或日志
 => [ToolServerNode  3/12] RUN apt update && apt install -y build-essential make openjdk-17-jdk-headless curl docker.io docker-compose psmisc sudo
...
235.7 Get:97 http://deb.debian.org/debian bookworm/main amd64 psmisc amd64 23.6-1 [259 kB]
244.9 Get:98 http://deb.debian.org/debian bookworm/main amd64 python3-json-pointer all 2.3-2 [15.1 kB]
245.0 Get:99 http://deb.debian.org/debian bookworm/main amd64 python3-rfc3987 all 1.3.8-2 [8816 B]
245.2 Get:100 http://deb.debian.org/debian bookworm/main amd64 python3-uritemplate all 4.1.1-2 [10.9 kB]
245.3 Get:101 http://deb.debian.org/debian bookworm/main amd64 python3-webcolors all 1.11.1-1 [12.7 kB]
**275.3 Ign:55 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jre-headless amd64 17.0.8+7-1~deb12u1
335.4 Ign:96 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jdk-headless amd64 17.0.8+7-1~deb12u1
395.5 Ign:55 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jre-headless amd64 17.0.8+7-1~deb12u1
455.7 Ign:96 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jdk-headless amd64 17.0.8+7-1~deb12u1
515.9 Ign:55 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jre-headless amd64 17.0.8+7-1~deb12u1
576.5 Ign:96 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jdk-headless amd64 17.0.8+7-1~deb12u1
636.6 Err:55 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jre-headless amd64 17.0.8+7-1~deb12u1
636.6   Connection failed [IP: 151.101.78.132 80]
696.7 Err:96 http://deb.debian.org/debian bookworm/main amd64 openjdk-17-jdk-headless amd64 17.0.8+7-1~deb12u1
696.7   Connection failed [IP: 151.101.78.132 80]
696.7 E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openjdk-17/openjdk-17-jre-headless_17.0.8%2b7-1%7edeb12u1_amd64.deb  Connection failed [IP: 151.101.78.132 80]
696.7 E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openjdk-17/openjdk-17-jdk-headless_17.0.8%2b7-1%7edeb12u1_amd64.deb  Connection failed [IP: 151.101.78.132 80]**
696.7 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
696.7 Fetched 84.0 MB in 10min 55s (128 kB/s)
------
failed to solve: process "/bin/sh -c apt update && apt install -y build-essential make openjdk-17-jdk-headless curl docker.io docker-compose psmisc sudo" did not complete successfully: exit code: 100

**Comment by Umpire2018** [comment]
请采取措施改善本地网络环境。

**Comment by Shiyao-Huang** [comment]
在RUN apt update 前加入
RUN sed -i '/Signed-By/d' /etc/apt/sources.list && sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list
