### ISSUE TITLE
Service 'ToolServerNode' failed to build : Build failed

### ISSUE THREAD

**Issue by menkeyi001** [OpenBMB/XAgent#147]
(base) root@lab:/data/app/XAgent/ToolServer# docker-compose up
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_COLLECTION variable is not set. Defaulting to a blank string.
Building ToolServerNode
[+] Building 332.9s (5/16)                                                                              
 => [internal] load .dockerignore                                                                  0.0s
 => => transferring context: 2B                                                                    0.0s
 => [internal] load build definition from Dockerfile                                               0.0s
 => => transferring dockerfile: 869B                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.10                                     6.5s
 => [internal] load build context                                                                  0.0s
 => => transferring context: 2.97kB                                                                0.0s
 => ERROR [ 1/12] FROM docker.io/library/python:3.10@sha256:85de714b205693782cc48408bc488153435  326.3s
 => => resolve docker.io/library/python:3.10@sha256:85de714b205693782cc48408bc48815343529987aae39  0.0s
 => => sha256:9d1f579451adcaffc6359f05606e5d915272916dd64ee907f796f5c9a0d08446 7.53kB / 7.53kB     0.0s
 => => sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92 0B / 24.05MB      326.4s
 => => sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342 64.13MB / 64.13MB  75.4s
 => => sha256:85de714b205693782cc48408bc48815343529987aae396b1adbbe05be5557cd7 1.65kB / 1.65kB     0.0s
 => => sha256:1c26c25390307b64e8ff73e7edf34b4fbeac59d41da41c08da28dc316a721899 2.01kB / 2.01kB     0.0s
 => => sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545 49.58MB / 49.58MB  63.9s
 => => sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e 211.06MB / 211.06MB  326.3s
 => => sha256:f9a1922eee8a7d8ea8d227102bf5b6671dd4f68a152a438c803c54092410bb28 6.39MB / 6.39MB    75.9s
 => => extracting sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545          3.6s
 => => sha256:b0fef9d6962c9c4b61e2e0bf03667a84d15346c6d8bfb206efe973384dcf3d34 17.15MB / 17.15MB  99.1s
 => => sha256:a8d4dcc5b9136e490e69eef208f4015ab4621638529d937e2e7ad076c8aae5a4 245B / 245B        76.0s
 => => sha256:285441070830e8a6311f822b3cc44adc2016f4067aa94862e8f0d9b537499d89 3.08MB / 3.08MB    76.8s
------
 > [ 1/12] FROM docker.io/library/python:3.10@sha256:85de714b205693782cc48408bc48815343529987aae396b1adbbe05be5557cd7:
------
Dockerfile:1
--------------------
   1 | >>> FROM python:3.10
   2 |     
   3 |     LABEL Role="toolserver.node"
--------------------
ERROR: failed to solve: failed to read expected number of bytes: unexpected EOF
ERROR: Service 'ToolServerNode' failed to build : Build failed

**Comment by luyaxi** [comment]
请检查你的网络能够正确的访问docker镜像源与debian官方源

**Comment by menkeyi001** [comment]
自己docker pull 就好了
