### ISSUE TITLE
Web UI is unresponsive. After a long time, the Terminal will also display “chatcompletion error: Request timed out”.

### ISSUE THREAD

**Issue by kuangxk2016** [OpenBMB/XAgent#148]
## Issue Description / 问题描述
1、Web UI is unresponsive.
2、When I execute the command "docker exec XAgent-Server systemctl start nginx", there is no output prompt on the terminal.
3、After ‘docker-compose up’ is executed, repeatedly print INFO: 127.0.0.1:56292 - ""GET / HTTP / 1.1" 200 OK. The output of XAgetn-Server | socket.send() raised exception will be interspersed in the middle.

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu20.04 
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
![卡住](https://github.com/OpenBMB/XAgent/assets/45114999/817cec8b-79e5-4887-98df-de7d50e0c86f)
![timeout](https://github.com/OpenBMB/XAgent/assets/45114999/eb2fa836-bc7f-4446-af00-b8e1798c36a6)
![200 OK](https://github.com/OpenBMB/XAgent/assets/45114999/b28cb399-c2ba-49e1-b837-30feb24d9eb3)
![start nginx没输出](https://github.com/OpenBMB/XAgent/assets/45114999/0bb5af5c-e8b1-42fd-ae48-e59e4d850896)

**Comment by kuangxk2016** [comment]
I found in other issues that I need to set port 8090 to be forwarded. How do I do this?
![image](https://github.com/OpenBMB/XAgent/assets/45114999/09a7b3bf-5c1b-45ba-a536-f4058355e6b5)

**Comment by sailaoda** [comment]
hello, about question 1 : as your error log, the openai key request is shown "time out",please check your openai api key whether if it`s available and your network is available and the assets/config.yml is set correctly;

about question 2 :  it`s normal that when you execute the command "docker exec XAgent-Server systemctl start nginx", there is no output prompt on the terminal. If you can visit "http://localhost:5173", it means that the command is taking effect.

about question 3 : maybe you could check the question 1 ,when question 1 has been solved, we check the question 3 again.

**Comment by kuangxk2016** [comment]
> hello, about question 1 : as your error log, the openai key request is shown "time out",please check your openai api key whether if it`s available and your network is available and the assets/config.yml is set correctly;
> 
> about question 2 : it`s normal that when you execute the command "docker exec XAgent-Server systemctl start nginx", there is no output prompt on the terminal. If you can visit "http://localhost:5173", it means that the command is taking effect.
> 
> about question 3 : maybe you could check the question 1 ,when question 1 has been solved, we check the question 3 again.

Thank you very much for your reply. I noticed that it is also related to the network. Do I need to go through a network proxy when reproducing your work?

**Comment by sailaoda** [comment]
Hello, firstly you could make sure that your network visit the openai website correctly, if you can`t visit, you need to go through a network proxy maybe. Look forward to your reply.

**Comment by kuangxk2016** [comment]
> Hello, firstly you could make sure that your network visit the openai website correctly, if you can`t visit, you need to go through a network proxy maybe. Look forward to your reply.

thank you very much for your help. Based on the suggestions you provided, I will continue debugging. I will give feedback if there are any results.

**Comment by ChengFai** [comment]
OK， Looking forward to your reply.  If you have any question about it, please reopen this issue
