### ISSUE TITLE
Authentication failed.

### ISSUE THREAD

**Issue by menkeyi001** [OpenBMB/XAgent#150]
## Issue Description / 问题描述
uthenticate_default                                                                                     
ToolServerMonitor_1  |     return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")                 
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 248, in _a
uthenticate_scram                                                                                       
ToolServerMonitor_1  |     res = conn.command(source, cmd)                                              
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 315, in
 inner                                                                                                  
ToolServerMonitor_1  |     return func(*args, **kwargs)
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 932, in co
mmand
ToolServerMonitor_1  |     return command(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/network.py", line 191, in
 command
ToolServerMonitor_1  |     helpers._check_command_response(
ToolServerMonitor_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 223, in
 _check_command_response
ToolServerMonitor_1  |     raise OperationFailure(errmsg, code, response, max_wire_version)
ToolServerMonitor_1  | pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 
'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
ToolServerManager_1  | [2023-10-31 10:22:11 +0000] [10] [INFO] Booting worker with pid: 10

**Comment by Umpire2018** [comment]
Please delete whole `XAgent` folder, re-clone the repo and retry.
