### ISSUE TITLE
web UI ，File write exception occurred at the end of task execution

### ISSUE THREAD

**Issue by dontlove14** [OpenBMB/XAgent#151]
## Issue Description / 问题描述
I deployed xAgent through Docker, and from the following logs, it can be seen that the operation is normal.
![1698840154003](https://github.com/OpenBMB/XAgent/assets/54974888/52392a9a-968e-4ec0-839b-4879f513031a)

Then I tested the basic functionality through webui
It can be seen that a step has been repeatedly executed, and upon reviewing the logs, two errors were reported.
One prompt request  /execute_tool 500. ERROR:  Temporary failure in name resolution  I don't quite understand what the problem is，How to handle it。This error should have caused  ** I will try using a Python notebook cell to ---compute the answer to '1+1'. ** 。 The error is as follows：
![image](https://github.com/OpenBMB/XAgent/assets/54974888/d7c09a6c-7711-426b-b899-bb727a1f9651)

一处为Exception in ASGI application。May I ask what is the reason for this? The error is as follows:
![image](https://github.com/OpenBMB/XAgent/assets/54974888/3b62b0f4-746e-4f26-81ba-e7beb9e6c7c7)

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu
- Python Version / Python 版本：3.1

**Comment by dontlove14** [comment]
It is worth noting that this issue is always present in any task being performed.At the same time, I found that one container in the Docker's container did not start, but when I checked the logs, I found no issues
![image](https://github.com/OpenBMB/XAgent/assets/54974888/28a43758-059c-48e5-a7d8-b734962b4940)
Here are the logs I checked through Docker Logs：
![image](https://github.com/OpenBMB/XAgent/assets/54974888/2e034fa5-fd91-4ff1-9337-cf35e8aa7613)
I want to know if the state of this container is normal

**Comment by Umpire2018** [comment]
That's expected behavior based on current `docker-compose.yml` and `ToolServerNode Dockerfile`.

In this case, even though the `Dockerfile` has an `ENTRYPOINT` that should keep the container running continuously by running a `uvicorn` server, the `entrypoint` in the `docker-compose.yml` overrides this, causing the container to exit after printing "Build complete. Exiting..."

Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/#entrypoint

For the error, can you upload `running_records` here and we will see.

**Comment by dontlove14** [comment]
/execute_tool 500. ERROR: Temporary failure in name resolution.
 Is it also caused by the ToolServerNode container startup failure?

**Comment by Umpire2018** [comment]
Like i said, it's not a failure which needs to worry about.
For `execute_tool`, it is in [here](https://github.com/OpenBMB/XAgent/tree/main/ToolServer#execute_tool)

**Comment by dontlove14** [comment]
Okay, thank you
