### ISSUE TITLE
ChatCompletion Error, but task can be split

### ISSUE THREAD

**Issue by WuYanJ** [OpenBMB/XAgent#152]
## Issue Description / 问题描述
出现ChatCompletion Error， 显示API返回404，但是task可以被拆分

## Environment / 环境信息
- Operating System / 操作系统：macos 13.3
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
<img width="873" alt="image" src="https://github.com/OpenBMB/XAgent/assets/46914823/d742ef3c-60ef-4f1c-9586-6abf20e31ca3">
<img width="872" alt="image" src="https://github.com/OpenBMB/XAgent/assets/46914823/a9aaad8f-92dd-41de-bb2b-40215559ce68">

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
您的配置是否正确?
程序是向您指定的Endpoint进行访问时发生了错误。
