### ISSUE TITLE
pymongo.errors.InvalidURI: The empty string is not valid username.

### ISSUE THREAD

**Issue by lifengyu2005** [OpenBMB/XAgent#153]
ToolServerManager_1  | [2023-11-02 05:55:03 +0000] [10] [INFO] Booting worker with pid: 10
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [7] [ERROR] Exception in worker process
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
ToolServerManager_1  |     worker.init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
ToolServerManager_1  |     super(UvicornWorker, self).init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
ToolServerManager_1  |     self.load_wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ToolServerManager_1  |     self.wsgi = self.app.wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
ToolServerManager_1  |     self.callable = self.load()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ToolServerManager_1  |     return self.load_wsgiapp()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ToolServerManager_1  |     return util.import_app(self.app_uri)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
ToolServerManager_1  |     mod = importlib.import_module(module)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ToolServerManager_1  |     return _bootstrap._gcd_import(name[level:], package, level)
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ToolServerManager_1  |   File "/app/main.py", line 13, in <module>
ToolServerManager_1  |     from connections import DB_TYPE,db,docker_client
ToolServerManager_1  |   File "/app/connections.py", line 18, in <module>
ToolServerManager_1  |     mongo_client = AsyncIOMotorClient(db_url)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
ToolServerManager_1  |     delegate = self.__delegate_class__(*args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in __init__
ToolServerManager_1  |     res = uri_parser.parse_uri(
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
ToolServerManager_1  |     user, passwd = parse_userinfo(userinfo)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 93, in parse_userinfo
ToolServerManager_1  |     raise InvalidURI("The empty string is not valid username.")
ToolServerManager_1  | pymongo.errors.InvalidURI: The empty string is not valid username.
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [7] [INFO] Worker exiting (pid: 7)
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [8] [ERROR] Exception in worker process
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
ToolServerManager_1  |     worker.init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
ToolServerManager_1  |     super(UvicornWorker, self).init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
ToolServerManager_1  |     self.load_wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ToolServerManager_1  |     self.wsgi = self.app.wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
ToolServerManager_1  |     self.callable = self.load()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ToolServerManager_1  |     return self.load_wsgiapp()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ToolServerManager_1  |     return util.import_app(self.app_uri)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
ToolServerManager_1  |     mod = importlib.import_module(module)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ToolServerManager_1  |     return _bootstrap._gcd_import(name[level:], package, level)
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ToolServerManager_1  |   File "/app/main.py", line 13, in <module>
ToolServerManager_1  |     from connections import DB_TYPE,db,docker_client
ToolServerManager_1  |   File "/app/connections.py", line 18, in <module>
ToolServerManager_1  |     mongo_client = AsyncIOMotorClient(db_url)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
ToolServerManager_1  |     delegate = self.__delegate_class__(*args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in __init__
ToolServerManager_1  |     res = uri_parser.parse_uri(
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
ToolServerManager_1  |     user, passwd = parse_userinfo(userinfo)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 93, in parse_userinfo
ToolServerManager_1  |     raise InvalidURI("The empty string is not valid username.")
ToolServerManager_1  | pymongo.errors.InvalidURI: The empty string is not valid username.
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [8] [INFO] Worker exiting (pid: 8)
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [9] [ERROR] Exception in worker process
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
ToolServerManager_1  |     worker.init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
ToolServerManager_1  |     super(UvicornWorker, self).init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
ToolServerManager_1  |     self.load_wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ToolServerManager_1  |     self.wsgi = self.app.wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
ToolServerManager_1  |     self.callable = self.load()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ToolServerManager_1  |     return self.load_wsgiapp()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ToolServerManager_1  |     return util.import_app(self.app_uri)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
ToolServerManager_1  |     mod = importlib.import_module(module)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ToolServerManager_1  |     return _bootstrap._gcd_import(name[level:], package, level)
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ToolServerManager_1  |   File "/app/main.py", line 13, in <module>
ToolServerManager_1  |     from connections import DB_TYPE,db,docker_client
ToolServerManager_1  |   File "/app/connections.py", line 18, in <module>
ToolServerManager_1  |     mongo_client = AsyncIOMotorClient(db_url)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
ToolServerManager_1  |     delegate = self.__delegate_class__(*args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in __init__
ToolServerManager_1  |     res = uri_parser.parse_uri(
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
ToolServerManager_1  |     user, passwd = parse_userinfo(userinfo)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 93, in parse_userinfo
ToolServerManager_1  |     raise InvalidURI("The empty string is not valid username.")
ToolServerManager_1  | pymongo.errors.InvalidURI: The empty string is not valid username.
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [9] [INFO] Worker exiting (pid: 9)
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [10] [ERROR] Exception in worker process
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
ToolServerManager_1  |     worker.init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
ToolServerManager_1  |     super(UvicornWorker, self).init_process()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
ToolServerManager_1  |     self.load_wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
ToolServerManager_1  |     self.wsgi = self.app.wsgi()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
ToolServerManager_1  |     self.callable = self.load()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
ToolServerManager_1  |     return self.load_wsgiapp()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ToolServerManager_1  |     return util.import_app(self.app_uri)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
ToolServerManager_1  |     mod = importlib.import_module(module)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ToolServerManager_1  |     return _bootstrap._gcd_import(name[level:], package, level)
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ToolServerManager_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ToolServerManager_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ToolServerManager_1  |   File "/app/main.py", line 13, in <module>
ToolServerManager_1  |     from connections import DB_TYPE,db,docker_client
ToolServerManager_1  |   File "/app/connections.py", line 18, in <module>
ToolServerManager_1  |     mongo_client = AsyncIOMotorClient(db_url)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 148, in __init__
ToolServerManager_1  |     delegate = self.__delegate_class__(*args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in __init__
ToolServerManager_1  |     res = uri_parser.parse_uri(
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
ToolServerManager_1  |     user, passwd = parse_userinfo(userinfo)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 93, in parse_userinfo
ToolServerManager_1  |     raise InvalidURI("The empty string is not valid username.")
ToolServerManager_1  | pymongo.errors.InvalidURI: The empty string is not valid username.
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [10] [INFO] Worker exiting (pid: 10)
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
ToolServerManager_1  | [2023-11-02 05:55:04 +0000] [1] [ERROR] Worker (pid:10) was sent SIGTERM!
ToolServerManager_1  | --- Logging error ---
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 209, in run
ToolServerManager_1  |     self.sleep()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 360, in sleep
ToolServerManager_1  |     ready = select.select([self.PIPE[0]], [], [], 1.0)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
ToolServerManager_1  |     self.reap_workers()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
ToolServerManager_1  |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
ToolServerManager_1  | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
ToolServerManager_1  |
ToolServerManager_1  | During handling of the above exception, another exception occurred:
ToolServerManager_1  |
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1103, in emit
ToolServerManager_1  |     stream.write(msg + self.terminator)
ToolServerManager_1  | RuntimeError
ToolServerManager_1  |
ToolServerManager_1  | During handling of the above exception, another exception occurred:
ToolServerManager_1  |
ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1103, in emit
ToolServerManager_1  |     stream.write(msg + self.terminator)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
ToolServerManager_1  |     self.reap_workers()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
ToolServerManager_1  |     self.log.error(msg)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/glogging.py", line 272, in error
ToolServerManager_1  |     self.error_log.error(msg, *args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
ToolServerManager_1  |     self._log(ERROR, msg, args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
ToolServerManager_1  |     self.handle(record)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
ToolServerManager_1  |     self.callHandlers(record)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
ToolServerManager_1  |     hdlr.handle(record)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
ToolServerManager_1  |     self.emit(record)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1108, in emit
ToolServerManager_1  |     self.handleError(record)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1021, in handleError
ToolServerManager_1  |     sys.stderr.write('--- Logging error ---\n')
ToolServerManager_1  | RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
ToolServerManager_1  | Call stack:
ToolServerManager_1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
ToolServerManager_1  |     sys.exit(run())
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
ToolServerManager_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run
ToolServerManager_1  |     super().run()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
ToolServerManager_1  |     Arbiter(self).run()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 229, in run
ToolServerManager_1  |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 342, in halt
ToolServerManager_1  |     self.stop()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 396, in stop
ToolServerManager_1  |     time.sleep(0.1)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
ToolServerManager_1  |     self.reap_workers()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
ToolServerManager_1  |     self.log.error(msg)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/glogging.py", line 272, in error
ToolServerManager_1  |     self.error_log.error(msg, *args, **kwargs)
ToolServerManager_1  | Message: 'Worker (pid:10) was sent SIGTERM!'
ToolServerManager_1  | Arguments: ()
XAgent-Server        | INFO:     Started server process [8]
XAgent-Server        | INFO:     Waiting for application startup.
XAgent-Server        | INFO:     Application startup complete.
ToolServerManager_1  | [2023-11-02 05:55:34 +0000] [1] [ERROR] Shutting down: Master
ToolServerManager_1  | [2023-11-02 05:55:34 +0000] [1] [ERROR] Reason: Worker failed to boot.

**Comment by lifengyu2005** [comment]
docker-compose up安装启动过程报错

**Comment by luyaxi** [comment]
请检查`.env`文件是否正确配置了数据库的用户名密码
