### ISSUE TITLE
bing 搜索引擎请求一直超时

### ISSUE THREAD

**Issue by dontlove14** [OpenBMB/XAgent#157]
## Issue Description / 问题描述
![image](https://github.com/OpenBMB/XAgent/assets/54974888/fb60130f-850d-40e0-a463-f50c3308f7b6)
我在中国大陆。我在配置文件中配置了bing的api_key，同时修改地区为香港，然后我执行任务，询问香港明日天气，在任务执行时一直报错ValueError: 'api.bing.microsoft.com' does not appear to be an IPv4 or IPv6 address。但是我在我的电脑通过接口测试工具测试请求https://api.bing.microsoft.com/v7.0/search，是可以请求通的，于是我进一步推断是否为容器的DNS配置问题，于是，我在尝试检查docker-compose文件时并没有找到相关信息，于是我自己添加了dns配置如下：
![image](https://github.com/OpenBMB/XAgent/assets/54974888/fbd32900-4ca5-400a-9340-a82038717c9e)
但是结果还是不尽如人意，依旧维持地址解析错误，
![image](https://github.com/OpenBMB/XAgent/assets/54974888/7b23afcf-7ba4-4eb2-93fc-9f5688886e9e)
所以请教一下，这个会是什么原因导致的又或是我的操作问题？
## Environment / 环境信息
- Operating System / 操作系统：Ubuntu
- Python Version / Python 版本：3.1

**Comment by luyaxi** [comment]
请attch到ToolServerNode容器中，测试是否可以在容器内发起网络请求

**Comment by dontlove14** [comment]
在ToolServerNode容器中可以请求到数据，真的很奇怪
![image](https://github.com/OpenBMB/XAgent/assets/54974888/e780bfb4-01fa-497d-b046-93e85c6c536f)

**Comment by luyaxi** [comment]
<img width="423" alt="截屏2023-11-03 18 44 35" src="https://github.com/OpenBMB/XAgent/assets/54500467/bd08c8bb-e13b-4a17-b1f8-fec7c94b662a">
请确认配置内容的endpoint是这样的格式，并尝试升级docker版本，拉取最新代码并重新build镜像，再次尝试。
