### ISSUE TITLE
每次任务执行到最后都会报错

### ISSUE THREAD

**Issue by dontlove14** [OpenBMB/XAgent#158]
## Issue Description / 问题描述
我通过docker部署的xAgent，通过web端执行任务。每次无论什么任务执行到最后时都会报错：
  File "/app/XAgent/agent/summarize.py", line 171, in recursive_summary
    plan_des.append(f'[Action Status] {"Success" if submission["result"]["success"] else "Fail"}')
KeyError: 'result'
INFO:     connection closed
![image](https://github.com/OpenBMB/XAgent/assets/54974888/18f25aab-d5c9-4396-b35c-8cd7a4fa93db)

请教一下这是什么原因导致的，应该如何处理？
## Environment / 环境信息
- Operating System / 操作系统：ubuntu
- Python Version / Python 版本：3.1

**Comment by luyaxi** [comment]
能否提供running records帮助定位问题？

**Comment by dontlove14** [comment]
这是完整的日志👇，麻烦帮忙看下原因在哪🙏
[log.log](https://github.com/OpenBMB/XAgent/files/13247541/log.log)

**Comment by luyaxi** [comment]
目前能定位到可能是openai function call功能的bug，没有按照预期生成指定的function call，请尝试执行有意义的task而非无意义对话以绕过该bug

**Comment by dontlove14** [comment]
我测试了官方的任务但是报错如下
![3f8c92509a6590a1535d89cbe687253](https://github.com/OpenBMB/XAgent/assets/54974888/5b403cd0-d4f3-4b89-b2e4-f0fc8389b05e)
这个是什么原因导致的？

**Comment by luyaxi** [comment]
请确认你在使用openai官方的api接口，第三方接口对于function call的支持可能并不完善。另外，你可以调整max_retry_times来获得更大的容错（同时也可能会增加token调用量）。

**Comment by dontlove14** [comment]
麻烦请教下max_retry_times具体的作用是什么？

**Comment by dontlove14** [comment]
我这个用的3.5的模型，我记得3.5-16k是不支持function call的吧。然后我尝试用gpt-3.5-turbo-0613测试，然后报错。因为我看到配置文件中3.5默认使用16k模型，所以我想确定16k模型也可以跑完任务？还是就得用gpt-3.5-turbo-0613或者GPT-4-0613。因为我记得openai官方说只有这两个才可以用function call。如果我需要用gpt-3.5-turbo-0613那么我通过哪个配置项可以控制上下文长度，来防止下面报错的出现
![87c3eeb8b89b9746b7f3a8d7f67cff0](https://github.com/OpenBMB/XAgent/assets/54974888/972d4303-bdd7-4dc0-a001-cae7b70b6a4b)

**Comment by luyaxi** [comment]
3.5-turbo-16k是支持function call的。4k context模型不能满足XAgent运行的基本需求，无法支持。

**Comment by dontlove14** [comment]
我更换了openai的代理地址为官方的，然后执行任务又报这个错。
![image](https://github.com/OpenBMB/XAgent/assets/54974888/8c6c41b2-3b02-4bea-8ee0-05ae54f57a4b)
我看这个FileSystemEnv_print_filesys_struture好像是本地的方法，但是从配置项来看应该被禁用掉的，请问这个应该如何处理？
![image](https://github.com/OpenBMB/XAgent/assets/54974888/541d940b-4305-41e6-ac17-cf4b73149457)

**Comment by luyaxi** [comment]
请不要使用dev分支的代码，目前dev分支已删除。请回到main分支并重新构建镜像
