### ISSUE TITLE
连接错误，请问这个是访问不到openai-api吗

### ISSUE THREAD

**Issue by iaoxuesheng** [OpenBMB/XAgent#161]
![2023-11-03 22-04-44 的屏幕截图](https://github.com/OpenBMB/XAgent/assets/94165844/c34f6a14-abd4-4874-a478-7123f4e15d39)
![2023-11-02 21-41-16 的屏幕截图](https://github.com/OpenBMB/XAgent/assets/94165844/ff2393c9-0462-46ab-b72b-255f9bf64316)

**Comment by iaoxuesheng** [comment]
只看下面的图就行，请问这个是jsondecoder失败是连接不上openai-api还是连不上tool，该怎么修改

**Comment by Umpire2018** [comment]
参见[状态码指引](https://help.openai.com/en/articles/6891839-api-error-code-guidance)：![image](https://github.com/OpenBMB/XAgent/assets/138990495/f80d0e1c-95b6-450f-b4f5-383d7e27fe49)
是否配置了错误的 `organization`, 此项可以删除，也可打码隐私内容后贴出配置进行查看。

**Comment by iaoxuesheng** [comment]
> 参见[状态码指引](https://help.openai.com/en/articles/6891839-api-error-code-guidance)：![image](https://user-images.githubusercontent.com/138990495/280321340-f80d0e1c-95b6-450f-b4f5-383d7e27fe49.png) 是否配置了错误的 `organization`, 此项可以删除，也可打码隐私内容后贴出配置进行查看。

我是把这项删除了
api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-2N05pCdQSP5qGBVUFMoBT3BlbkFJSrfWdT28oYZxfhgo
      api_base: https://example.com
      api_type: azure
      api_version: 2023-07-01-preview
      engine: GPT-35-Turbo-16k
      # you can use any kwargs supported by openai.ChatCompletion here
    - api_key: sk-2N05pCdQSP5qGBVUFMoBT3BlbkFJSrfWdT28oYZxfhgo
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4
  gpt-4-32k:
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4-32k
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4-32k


default_request_type: openai # or xagent
default_completion_kwargs:
  model: gpt-4-32k
  temperature: 0.2
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 2048
  max_return_length: 12384

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 5
max_subtask_chain_length: 15
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False

tool_blacklist:
  - FileSystemEnv_print_filesys_struture

record_dir:

experiment:
  redo_action: false

**Comment by Umpire2018** [comment]
@iaoxuesheng 看起来你将同一个Key同时设置在了 azure 与 opneai处，请确定 key 类型，仅保留一处, 如若为 openai key
```
api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-123456
      model: gpt-3.5-turbo-16k
```
