### ISSUE TITLE
服务启动成功，执行官网demo任务报错

### ISSUE THREAD

**Issue by dontlove14** [OpenBMB/XAgent#164]
## Issue Description / 问题描述
我测试了官网上的demo任务👇
![image](https://github.com/OpenBMB/XAgent/assets/54974888/71975663-be90-46a6-9d6d-9698f3388843)

，结果执行报错如下👇。请教一下引起这个问题的原因是什么以及我应该如何处理🙏？
![image](https://github.com/OpenBMB/XAgent/assets/54974888/64a2fd2a-afe3-434b-95f3-b2cb679a47a1)

**Comment by luyaxi** [comment]
请使用main分支代码
