### ISSUE TITLE
任务执行报错，提示 mode is not exist! Only auto and manual are allowed!

### ISSUE THREAD

**Issue by dontlove14** [OpenBMB/XAgent#166]
## Issue Description / 问题描述
我执行了一个算数任务，任务在最后步骤报错如下：
![image](https://github.com/OpenBMB/XAgent/assets/54974888/7db51225-e5d4-4d55-890c-5ebecea3a52e)

## Steps to Reproduce / 复现步骤
任务执行步骤如下，前台最后的右下角显示任务已完成：
![image](https://github.com/OpenBMB/XAgent/assets/54974888/623aee42-36b2-41f3-9e1b-b991bc01c3aa)

## Complete log file / 完整的日志文件
见[附件](https://github.com/OpenBMB/XAgent/files/13258578/log.txt)

**Comment by Umpire2018** [comment]
@sailaoda @thunlp-zp 
建议优先级为 紧急

已复现，操作环境为浏览器，任务已完成，但Server 输出日志为有报错，并导致未有log保存到本地，其余 container 日志为正常。

[log.txt](https://github.com/OpenBMB/XAgent/files/13258956/log.txt)

**Comment by thunlp-zp** [comment]
很抱歉，我没有复现出您的结果，但是根据代码来看，造成这个应该是您刷新了浏览器，发了一个空的请求，在这个请求中有一些参数没有传入。我们已经有新的代码正在做测试，也许不会再有这个问题，您可以在稍后的版本中再检查一下。
