### ISSUE TITLE
请问，是否能支持azure openai key

### ISSUE THREAD

**Issue by Moss-qc** [OpenBMB/XAgent#169]
在国内使用openai key比较麻烦，也申请不到GPT4的key。如果能支持azure openai key将会方便很多。实例如下，谢谢！

![image](https://github.com/OpenBMB/XAgent/assets/129234938/2d6584fe-1745-4952-b59f-3bca2a8d87fc)

**Comment by Umpire2018** [comment]
当前 `config.yml` 支持填入 azure 相关项。

**Comment by starlee822** [comment]
#165
