### ISSUE TITLE
Suggestions on config file

### ISSUE THREAD

**Issue by Guo-Zhang** [OpenBMB/XAgent#17]
It seems that the excellent package [dynaconf](https://www.dynaconf.com) can help you to provide a better config and secret management. 

An examples from us: https://github.com/quanttide/qcloud-sdk-py/blob/master/qcloud_sdk/config.py

I would like to help you on that if you guys needs.

**Comment by Guo-Zhang** [comment]
The secrets like API key from users should be ignored from the git repo. Dynaconf provides some tools to manage secrets towards files or Vault.

**Comment by ChengFai** [comment]
oh, we'll consider it.

**Comment by Guo-Zhang** [comment]
我已经加入了Discord群聊，我在里面详细说下
