### ISSUE TITLE
请问目前支持用开源大模型（例如：你们的ToolLLaMA-2-7b-v2）替换openai API吗

### ISSUE THREAD

**Issue by leehommlee** [OpenBMB/XAgent#170]
## Feature Description / 功能描述
Please describe the feature you would like to see added or improved. / 请描述您希望添加或改进的功能。

## Goal / 目标
Explain the goal you hope to achieve with this feature. / 请说明您希望通过这个功能实现的目标。

## Expected Behavior / 预期行为
Describe the behavior you expect from this feature. / 请描述您期望的功能行为。

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
您可以使用提供与 openai 相应一致接口的大模型， 如提到的 ToolBench，但项目仅推荐使用 Openai 提供的相关大模型。

**Comment by faker-bert** [comment]
有很多项目可以把LLM包装成openai的接口，随便搜都一堆

**Comment by miandai** [comment]
看看 [api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm) 支持不
