### ISSUE TITLE
Web UI增加“新问题”或者“新对话”的功能

### ISSUE THREAD

**Issue by starlee822** [OpenBMB/XAgent#177]
## Feature Description / 功能描述
当前的WebUI在执行完任务后无法继续下一个任务，只能退回或者重新打开Web UI。

## Goal / 目标
希望增加一个功能可以在上一个任务完成界面快捷的输入并启动下一个任务。

**Comment by thunlp-zp** [comment]
这个功能已经在我们的迭代中，会在下一次更新中体现，敬请期待。

**Comment by Guo-Zhang** [comment]
建议分类为”用户体验问题“。

这个问题对用户体验的影响不小，确实应该引起重视。

**Comment by ChengFai** [comment]
new talk 按钮之前因为某些原因暂时没放开而设为隐藏状态，您可以自行启动源代码发起对话。
