### ISSUE TITLE
太费$了，列一下2022最受欢迎的食物，花了29$，运行了好长时间，最后还没有给出结果来

### ISSUE THREAD

**Issue by ccdanpian** [OpenBMB/XAgent#180]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Guo-Zhang** [comment]
我尝试模拟了下你的提问。

Q: 
>  "列一下2022最受欢迎的食物"

Answered by GPT3.5-turbo:

> 以下是2022年最受欢迎的一些食物，这些食物在社交媒体上、餐馆和食品界引起了广泛的讨论和流行：
> 
> 1. 植物性肉类替代品：植物性肉类替代品在2022年继续蓬勃发展。产品如Beyond Meat和Impossible Foods等公司的植物性汉堡和香肠备受欢迎，因为它们提供了与传统肉类相似的口感和味道，同时减少了对环境的影响。
> 
> 2. 波卡切沙拉（Poke Bowl）：波卡切沙拉是一道源自夏威夷的菜肴，由新鲜的生鱼片、蔬菜、米饭和各种调味料组成。它的颜色丰富、味道多样，成为人们喜爱的健康餐选项。
> 
> 3. 有机食品：越来越多的人开始注重健康和环保，对有机食品的需求在2022年持续增长。有机食品指的是通过无化学农药、无合成肥料和无基因改造的方式生产的食品，被认为更加健康和营养丰富。
> 
> 4. 高蛋白质食品：随着健身和健康意识的兴起，高蛋白质食品在2022年变得非常流行。这些食品包括鸡胸肉、鱼、扁豆、蛋白质棒和蛋白质奶昔等，被认为有助于增加肌肉质量和提供长时间的饱腹感。
> 
> 5. 可持续海鲜：可持续海鲜在2022年受到了更多关注。人们越来越关注海洋生态系统的健康和保护，选择以可持续方式捕捞或养殖的海鲜，如有机鲑鱼和草饲牛油鱼。
> 
> 6. 螺狮粉：螺狮粉是一道来自中国广东省的传统美食，近年来在全球范围内越来越受欢迎。它由大米粉、新鲜螺肉和各种调味料组成，口感鲜美，成为许多人钟爱的亚洲美食。
> 
> 请注意，这只是对2022年最受欢迎食物的一些例子，食物流行趋势会因地域和个人口味偏好而有所不同。

Q: 
> ”你的知识库目前更新到了哪里？“

A: 
> 我的知识库截止到2021年9月。任何关于2022年以及之后的事件、发展和趋势的信息都不在我的知识范围之内。请记住，我只能提供在知识库截止日期之前的信息。如果您有关于过去的问题，我将尽力帮助您。


可以看到，如果不使用GPT4，以及不使用Agent，会出现一个很明显的幻觉问题。

为什么你的提问会得到如此糟糕的答案呢？如果不出现幻觉，AI解决这个步骤需要：
1. ”最受欢迎“的范围是什么？全球？中国？中国的某个地方？
2. 2022的知识库从哪里获取？这个可能是最麻烦的问题。
3. ”最受欢迎“的标准是什么？这也是一个很模糊且不好界定的问题。

当然，XAgent的工程上还有很多问题，我正在主导这方面的更新。主要计划：
1. 日志和监控：这里需要对Agent的状态做跟踪，像这样明显的异常情况应该被捕捉并且被查验原因。
2. 限额：这里可能需要考虑对单个任务的最大调用次数做必要的限制。

如果你有进一步的日志和监控数据欢迎分享。

**Comment by ccdanpian** [comment]
是的，您说的步骤没错，不过作为理论上一个智商比较高Agent，不应该要求使用者一次性补全信息。我建议做一下如下的改动：首先应该由AI去判断目前收到的信息是否全面，用于评估是否需要向使用者提问，要求使用者补全信息。

**Comment by ccdanpian** [comment]
@Guo-Zhang 强烈建议增加这项能力

**Comment by Guo-Zhang** [comment]
感谢建议，我去和社区同学了解下他们是否有在做UserProxyAgent一类的特性。

**Comment by thuqinyj16** [comment]
感谢您的建议，这项功能我们已经考虑在2期XAgent了，敬请期待

**Comment by Umpire2018** [comment]
PS: @ccdanpian 可以看下在 config 中开启 `enable_ask_human_for_help`.
