### ISSUE TITLE
gpt 4 turbo support

### ISSUE THREAD

**Issue by sfdrada** [OpenBMB/XAgent#192]
Feature Description / 功能描述
The integration of GPT-4 Turbo API into XAgent would be highly beneficial. The GPT-4 Turbo is designed to handle more complex and nuanced tasks with greater speed and efficiency. Its addition would significantly enhance XAgent's capabilities.

Goal / 目标
The goal is to enable XAgent to perform more advanced tasks with improved performance and reduced costs, leveraging the enhanced speed and efficiency of GPT-4 Turbo API for faster and more economical operations.

Expected Behavior / 预期行为
With the integration of GPT-4 Turbo, XAgent should be able to process tasks more rapidly, with lower latency and at a reduced cost. This feature should be easily configurable within the current setup and should not require extensive changes by the end-user.

Additional Notes / 其他备注
The addition of GPT-4 Turbo API support would align XAgent with the latest advancements in AI language models and maintain its competitive edge as a tool for complex task solving.

**Comment by Umpire2018** [comment]
Thank you for bringing this up. We are in the process of adapting to OpenAI 1.x, refer to [#187](https://github.com/OpenBMB/XAgent/pull/189)  and once that is complete, you will be able to use the latest services.

**Comment by Umpire2018** [comment]
Should be fixed in [Fix: openai v1 support&run.py fix](https://github.com/OpenBMB/XAgent/commit/fde4217942204e38a8be0da1be8db06c78c9ef2a)
