### ISSUE TITLE
only update .txt ?  upload more file extensions.

### ISSUE THREAD

**Issue by jihe520** [OpenBMB/XAgent#195]
## Feature Description / 功能描述
just be allowed to update .txt ,i want to update .csv. and i see dome which demonstrates more file extension
i try to analyse date .
i try by changing prompt.
**Can you help me to use python to analyze the given data?Must remember change .txt to .csv**
but get in error

## Goal / 目标
Explain the goal you hope to achieve with this feature. / 请说明您希望通过这个功能实现的目标。

## Expected Behavior / 预期行为
When will upload more file extensions be added? / 请描述您期望的功能行为。

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
Please share your error so that we can look into it.
