### ISSUE TITLE
可以对任务进行分解，但是经常陷入循环或超时。

### ISSUE THREAD

**Issue by lingfengchencn** [OpenBMB/XAgent#198]
## Issue Description / 问题描述
或者启动->端口被占用->kill->启动失败->端口被占用->kill
或者超时->测试失败->验证代码->启动超时->测试失败->验证代码
或者fastapi hello world测试成功，post测试失败，验证环境->端口占用->helloWorld测试成功->post测试失败->重新查看app.py代码，没问题->hello word 测试成功。

## Steps to Reproduce / 复现步骤
python run.py --task "帮我编写一个文件上传的项目，前端使用gradio，后段使用fastapi，实现用户上传文件（pdf,txt,ppt,md等），调用openai 翻译成指定语言（中文->英文,英文->中文），并下载该文件。"  --model "gpt-4-32k"

## Expected Behavior / 预期行为
分解任务、按步骤执行。不要无限循环操作。

## Environment / 环境信息
- Operating System / 操作系统：
mac
- Python Version / Python 版本：
python3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志

THOUGHTS:  Since the previous shell command to run the Gradio application timed out, we should try to execute the command again and verify the successful launch of the Gradio application.

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
请使用新版代码进行体验。
