### ISSUE TITLE
[feature]docker-compose.yaml一键部署支持 

### ISSUE THREAD

**Issue by VectorZhao** [OpenBMB/XAgent#2]
docker-compose.yaml一键部署支持 
前后端配置在docker-compose.yaml文件中，执行`docker compose up -d`进行部署。

**Comment by VectorZhao** [comment]
github action编译amd和arm镜像推送到dockerhub，然后利用docker compose一键部署前后端。

**Comment by luyaxi** [comment]
我们计划在正式推出第一个版本后发布镜像

**Comment by luyaxi** [comment]
v1.0.0版本已发布，正式支持了这一功能，细节内容请查阅我们发布[日志](https://github.com/OpenBMB/XAgent/releases/tag/v1.0.0)！感谢您的建议！
