### ISSUE TITLE
wrong port?

### ISSUE THREAD

**Issue by Jiaming-Liu** [OpenBMB/XAgent#20]
4a65517e5cb269f9ee332272f714bcc8239e31bc:

XAgent/XAgentServer/docker-compose.yml maps port 8000 but XAgent-Server listen to 16204

**Comment by Jiaming-Liu** [comment]
btw after fixing this, i still cannot login:

XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  |   XAgent Service Startup Param:
XAgent-Server  |             app: app:app
XAgent-Server  |             prod: False
XAgent-Server  |             base_dir: XAgentServer
XAgent-Server  |             use_redis: False
XAgent-Server  |             recorder_root_dir: running_records
XAgent-Server  |             default_login: True
XAgent-Server  |             check_running: False
XAgent-Server  |             host: localhost
XAgent-Server  |             port: 8090
XAgent-Server  |             debug: True
XAgent-Server  |             reload: True
XAgent-Server  |             workers: 1
XAgent-Server  |             DB: <class 'XAgentServer.envs.XAgentServerEnv.DB'>
XAgent-Server  |             Redis: <class 'XAgentServer.envs.XAgentServerEnv.Redis'>
XAgent-Server  |             Email: <class 'XAgentServer.envs.XAgentServerEnv.Email'>
XAgent-Server  |             Upload: <class 'XAgentServer.envs.XAgentServerEnv.Upload'>
XAgent-Server  |   init websocket_queue
XAgent-Server  | XAgentServer is running on localhost:8090
XAgent-Server  | Default user: admin, token: xagent-admin, you can use it to login
XAgent-Server  |   Create task for pong broadcast
XAgent-Server  | init a websocket manager
XAgent-Server  | init a thread pool executor, max_workers: 1
XAgent-Server  |   pong broadcast for active connections: 0
XAgent-Server  |   init localstorage connection: users.json
XAgent-Server  |   init localstorage connection: interaction.json
XAgent-Server  | INFO:     172.20.0.1:34098 - "POST /api/login HTTP/1.1" 404 Not Found

**Comment by sailaoda** [comment]
Thanks for your advice, it will work now.
