### ISSUE TITLE
可以支持文心一言吗？

### ISSUE THREAD

**Issue by CQxiaocaimi** [OpenBMB/XAgent#200]
我没有openai，不过文心一言现在也提供了Access Token，具体格式是erniebot.api_type = 'aistudio'
erniebot.access_token = '{YOUR-ACCESS-TOKEN}'，这样替换可以吗？

**Comment by Umpire2018** [comment]
您好，项目目前仅支持 Openai 系 LLM，其他大模型目前暂不支持接入。
