### ISSUE TITLE
function_call_refine: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Turingforce** [OpenBMB/XAgent#202]
### Issue Description / 问题描述
执行任务期间，在  
File "/workspace/XAgent/XAgent/ai_functions/request/obj_generator.py", line 120, in function_call_refine:
function_schema = list(filter(lambda x: x['name'] == response['choices'][0]['message']['function_call']['name'],req_kwargs['functions']))  
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

### Steps to Reproduce / 复现步骤
python run.py --task "write a 500 words chinese climate change report" --model "gpt-3.5-turbo-16k" --config_file "assets/config.yml"

### Environment / 环境信息
- Operating System / gitpod full workspace
- Python Version / Python3.11

### Error Screenshots or Logs / 错误截图或日志
```
-=-=-=-=-=-=-= BEGIN QUERY SOVLING -=-=-=-=-=-=-= 
Role  Assistant
Task  write a 500 words chinese climate change report
-=-=-=-=-=-=-= GENERATE INITIAL_PLAN -=-=-=-=-=-=-= 
Constructing an Agent:  PlanGenerateAgent
  chatcompletion: using gpt-3.5-turbo-16k
  Traceback (most recent call last):
  File "/workspace/XAgent/XAgentServer/server.py", line 105, in interact
    await task_handler.outer_loop_async()
    ......
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/workspace/XAgent/XAgent/ai_functions/request/obj_generator.py", line 51, in chatcompletion
    response = self.function_call_refine(kwargs,response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/XAgent/XAgent/ai_functions/request/obj_generator.py", line 120, in function_call_refine
    function_schema = list(filter(lambda x: x['name'] == response['choices'][0]['message']['function_call']['name'],req_kwargs['functions']))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/XAgent/XAgent/ai_functions/request/obj_generator.py", line 120, in <lambda>
    function_schema = list(filter(lambda x: x['name'] == response['choices'][0]['message']['function_call']['name'],req_kwargs['functions']))
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

## Additional Notes / 其他备注
会跟模型有关吗，毕竟使用了ChatGLM3封装的接口，但是使用GPT时也会出现，虽然GPT3.5不够智能循环许久67个json还不能完成，但是也会因为这个错误而终止输出。
![image](https://github.com/OpenBMB/XAgent/assets/82068701/1d86b171-cc29-4b21-a668-ae52298ab8c1)

**Comment by Umpire2018** [comment]
建议您采用 GPT-3.5-16K 以上的模型进行运行程序，若您在使用GPT时遇到了相关问题，请贴出相关日志。

**Comment by luyaxi** [comment]
ChatGLM3的function call不能满足xagent最低运行条件，请使用gpt-3.5-turbo-16k或gpt-4来运行
