### ISSUE TITLE
请问mongo连接遇到权限问题是为什么

### ISSUE THREAD

**Issue by isunfloweryg** [OpenBMB/XAgent#203]
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

**Comment by Umpire2018** [comment]
请尝试删除所有 container 与 image 重新build.

**Comment by isunfloweryg** [comment]
已经解决了，总之还挺诡异的，不用用户名和密码能连接，然后进去创建了一个admin

**Comment by Jinyi6** [comment]
> 已经解决了，总之还挺诡异的，不用用户名和密码能连接，然后进去创建了一个admin

怎么解决的呢？

**Comment by isunfloweryg** [comment]
mongosh -u -p --authenticationDatabase admin，不要用户名和密码可以连接上，连接到数据库之后create一个admin，设置好密码，然后再用 mongosh -u admin -p xagentmongodb --authenticationDatabase admin连接就不报权限错误了。很诡异，一开始用docker inspect看了db的容器，username和password绝对没有问题，但是mongosh -u admin -p xagentmongodb --authenticationDatabase admin连接就是报权限错误，然后就是上述的办法解决的
