### ISSUE TITLE
Submitted a question to the agent. It has been two hours and there is no information on the front-end interface. The back-end is constantly looping

### ISSUE THREAD

**Issue by miandai** [OpenBMB/XAgent#205]
It's been two hours now, and there's no prompt on the front-end. 

![image](https://github.com/OpenBMB/XAgent/assets/4371622/b6c928e7-739c-4671-95c8-c2a0bafca21c)

Although there are errors reported by the backend, there is no detailed information. I don't know where to investigate the cause. May I ask where to check the detail logs?

![image](https://github.com/OpenBMB/XAgent/assets/4371622/48fbab56-735c-4f91-914f-50b7bb228651)
![image](https://github.com/OpenBMB/XAgent/assets/4371622/070c90ee-2f0d-4d43-b929-7ca8da1b64b9)

Finally, there was some slightly more detailed exception information：

![image](https://github.com/OpenBMB/XAgent/assets/4371622/0c84e5e7-56d5-43bb-8333-313da7c4fe80)
![image](https://github.com/OpenBMB/XAgent/assets/4371622/2aab8128-480d-4ed7-a613-47b98105207c)

Never run through a case on Xagent. I have used [OpenAgents](https://github.com/xlang-ai/OpenAgents) and the effect is very impressive. Do someone have an online XAgent demo? Really hope to experience it.

**Comment by luyaxi** [comment]
Please give detailed config file

**Comment by miandai** [comment]
Thank you @luyaxi . Here is the config file（Note: The model pointed to by api_base is not chatgpt, but chatglm3 encapsulated and initiated by [api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)）:

api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-xxx
      api_base: http://x.x.x.x:y/v1
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: sk-xxx
      api_base: http://x.x.x.x:y/v1
      model: gpt-4
  gpt-4-32k:
    - api_key: sk-xxx
      api_base: http://x.x.x.x:y/v1
      model: gpt-4-32k

default_request_type: openai # or xagent
default_completion_kwargs:
  model: gpt-4-32k
  temperature: 0.2
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 2048
  max_return_length: 12384

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 5
max_subtask_chain_length: 15
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False

tool_blacklist:
  - FileSystemEnv_print_filesys_struture

record_dir:

experiment:
  redo_action: false

**Comment by luyaxi** [comment]
ChatGLM3 does not meet the minimal requirement of running XAgent, which requires a stronge Function Call ability, please use openai model instead.
