### ISSUE TITLE
在启动镜像时遇到了网络问题

### ISSUE THREAD

**Issue by heimen-zc** [OpenBMB/XAgent#206]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
执行docker-compose up --build报错，具体请看截图
![image](https://github.com/OpenBMB/XAgent/assets/72239990/8d2d6d2f-488d-4342-8668-41ec6b57137c)
看起来是通过linux包管理工具apt进行下载nginx，请问mac能安装吗？

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：MacOS
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by simplecellzg** [comment]
我也遇到了这个问题，我在win11的wsl+docker-todesk，ubuntu22.04分别试过，都在这步会报错，后来发现，凡是遇到apt的相关步骤都会非常慢，所以推断应该是软件源的问题，一般更换源的办法是替换docker中的 /etc/apt/sources.list文件就能实现，但是Dockerfile中的FROM python:3.10 采用的高版本的Debian，它的软件源位置发生变化了，如果只替换sources.list文件，虽然也会执行更改后的源，但是后面会继续执行默认源，导致安装缓慢甚至失败。可以通过以下方法进行修改：
1. 把Debian的镜像源文件sources.list放入有docker-compose.yml的文件夹下，否则可能会不识别
2. 在dockerfiles文件夹下的所有Dockerfile文件都更换源，在apt update之前加入COPY sources.list /etc/apt/sources.list
3. 移除 Debian新的源文件RUN rm -rf /etc/apt/sources.list.d/debian.sources
4. 重新docker-compose up --build
这个操作对我有用，希望能解决你的问题

**Comment by Umpire2018** [comment]
@simplecellzg @heimen-zc 
我则是使用了全局代理来改善本地网络环境就解决问题了。而若替换镜像源为国内地址有可能对国外用户不友好。

**Comment by simplecellzg** [comment]
在win11的wsl＋docker的环境下我即使使用全局代理依然很慢或者失败， 我觉得更换源能够提供一个选项，如果网络环境好或者在国外，就直接docker compose up --build，如果网络完全无法支持，把更换源的命令从注释改为执行就行了。另：Debian高版本的源比较坑的是，它的默认源位置发生了改变，这对于习惯ubuntu或其他系统的用户来说，自行更换源的方法在网上不那么好找（反正这个问题卡了我好久）


| |
张冠
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月18日 10:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [OpenBMB/XAgent] mac是否可以安装（docker-compose up --build报错） (Issue #206) |

@***@***.***
我则是使用了全局代理来改善本地网络环境就解决问题了。而若替换镜像源为国内地址有可能对国外用户不友好。

**Comment by Umpire2018** [comment]
@simplecellzg 多谢分享，我们会在新版本中增加 debian 镜像源，同时在考虑发布聚合镜像。

**Comment by Umpire2018** [comment]
此项在团队进行讨论后决定暂时搁置，有需要可在 dockerfile 中指定需要用的镜像。
