### ISSUE TITLE
运行结束后在本地没有找到生成的代码文件

### ISSUE THREAD

**Issue by zrainbowk** [OpenBMB/XAgent#207]
不仅local_workspace文件夹没有，整个XAgent的文件夹都没有生成的代码文件，这个需要怎么解决呢？还是在其他什么文件夹里

**Comment by Umpire2018** [comment]
一般情况下，生成的文件在 `running_records` 文件夹中。
请先查看 docker 日志检查程序运行过程中有无发生报错，若有，请贴出相关日志。我们会使用日志进行排障。

**Comment by zrainbowk** [comment]
用GUI运行本地不会生成任何新的文件，用命令行运行后才会在running_records里找到运行过程中的记录
