### ISSUE TITLE
云服务器上不能安装docker怎么办？

### ISSUE THREAD

**Issue by CQxiaocaimi** [OpenBMB/XAgent#208]
如题，我无法安装docker，然后在这种情况下启动start_server.py和run.py后遇到报错：requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2fe11b160>: Failed to establish a new connection: [Errno 111] Connection refused'))。
不知道是不是没有做之前的步骤导致的，还是其他原因。

**Comment by Umpire2018** [comment]
请问您使用的是什么云服务器，建议前往厂商处寻求帮助或更换云服务器。
