### ISSUE TITLE
请问我该如何上传指定的数据集与指定的代码？

### ISSUE THREAD

**Issue by AI-HEBUT** [OpenBMB/XAgent#213]
我想要上传某一数据集，让xagent使用我提供的代码进行测试，输出的某个指标如果不满足要求，希望xagent修改代码内某参数，直到指标ok。
希望可以得到大家的解读与帮助，万分感谢！！！

**Comment by Umpire2018** [comment]
你好，当前版本支持上传不同文件类型的文件，并在 `config.yml` 中将 `enable_ask_human_for_help` 设置为 `True` ，其功能为XAgent 会向人类寻求指引。请进行尝试。
