### ISSUE TITLE
Build failed  in Ubuntu 20.04, success  in MacOS

### ISSUE THREAD

**Issue by Shiyao-Huang** [OpenBMB/XAgent#218]
请在 ToolServerNode 的 dockerfile 中的 `RUN apt update` 前一行增加 ，后续会增加进去，参见 #206
```
RUN sed -i '/Signed-By/d' /etc/apt/sources.list.d/debian.sources && sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources
```

_Originally posted by @Umpire2018 in https://github.com/OpenBMB/XAgent/issues/212#issuecomment-1818168001_
            
            
在Mac中运行成功，但是在ubuntu 中出现了新的错误

0.174 sed: can't read /etc/apt/sources.list.d/debian.sources: No such file or directory
------
Dockerfile:8
--------------------
   6 |     
   7 |     WORKDIR /app
   8 | >>> RUN sed -i '/Signed-By/d' /etc/apt/sources.list.d/debian.sources && sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources
   9 |     
  10 |     RUN apt update && apt install -y build-essential make openjdk-17-jdk-headless curl docker.io docker-compose psmisc sudo
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i '/Signed-By/d' /etc/apt/sources.list.d/debian.sources && sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources" did not complete successfully: exit code: 2
ERROR: Service 'ToolServerNode' failed to build : Build failed```

**Comment by Shiyao-Huang** [comment]
https://github.com/OpenBMB/XAgent/issues/35#issuecomment-1772025588

**Comment by Umpire2018** [comment]
@Shiyao-Huang 

多谢反馈。

**Comment by CQxiaocaimi** [comment]
所有方法都试过了，各种添加都不行，怎么办啊
