### ISSUE TITLE
执行docker-compose up遇到报错networks.tool-server-network value Additional properties are not allowed ('name' was unexpected)

### ISSUE THREAD

**Issue by youthbupt** [OpenBMB/XAgent#22]
执行docker-compose up遇到报错：
networks.tool-server-network value Additional properties are not allowed ('name' was unexpected)
将docker-compose.yaml中的network name注释掉之后：
networks:
  tool-server-network:
    # name: tool-server-network
    driver: bridge

启动成功，但启动xagent后报错python run.py --task "xxx" --model "gpt-4"

ToolServerManager_1  | Traceback (most recent call last):
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
ToolServerManager_1  |     result = await app(  # type: ignore[func-returns-value]
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
ToolServerManager_1  |     return await self.app(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
ToolServerManager_1  |     await super().__call__(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
ToolServerManager_1  |     await self.middleware_stack(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
ToolServerManager_1  |     raise exc
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
ToolServerManager_1  |     await self.app(scope, receive, _send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
ToolServerManager_1  |     raise exc
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
ToolServerManager_1  |     await self.app(scope, receive, sender)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
ToolServerManager_1  |     raise e
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
ToolServerManager_1  |     await self.app(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
ToolServerManager_1  |     await route.handle(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
ToolServerManager_1  |     await self.app(scope, receive, send)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
ToolServerManager_1  |     response = await func(request)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
ToolServerManager_1  |     raw_response = await run_endpoint_function(
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
ToolServerManager_1  |     return await dependant.call(**values)
ToolServerManager_1  |   File "/app/main.py", line 101, in read_cookie_info
ToolServerManager_1  |     container = docker_client.containers.run(CONFIG['node']['image'],detach=True,network=CONFIG['node']['network'],
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 865, in run
ToolServerManager_1  |     container.start()
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 406, in start
ToolServerManager_1  |     return self.client.api.start(self.id, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
ToolServerManager_1  |     return f(self, resource_id, *args, **kwargs)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/api/container.py", line 1127, in start
ToolServerManager_1  |     self._raise_for_status(res)
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
ToolServerManager_1  |     raise create_api_error_from_http_exception(e) from e
ToolServerManager_1  |   File "/usr/local/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
ToolServerManager_1  |     raise cls(e, response=response, explanation=explanation) from e
ToolServerManager_1  | docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/d1c5f95eafa3b6fe678e43092e1bc8f7535f44b028387a5d9a4de137d3936cc7/start: Not Found ("network tool-server-network not found")

**Comment by luyaxi** [comment]
请汇报平台版本，docker-compose版本，docker版本。您可以尝试升级docker-compose版本或手动创建tool-server-network并将docker-compose中networks.tool-server-network配置为external。

**Comment by youthbupt** [comment]
Docker version 20.10.5+dfsg1, build 55c4c88
docker-compose version 1.25.0, build unknown

**Comment by luyaxi** [comment]
请尝试更新docker和docker-compose再运行

**Comment by yuanzhiyong1999** [comment]
> 执行环境： Docker version 20.10.5+dfsg1, build 55c4c88 docker-compose version 1.25.0, build unknown
> 
> 设置为external之后，执行docker-compose，提示认证失败，具体报错： ToolServerMonitor_1 | Traceback (most recent call last): ToolServerMonitor_1 | File "/app/main.py", line 46, in ToolServerMonitor_1 | asyncio.run(check_nodes_status_loop()) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run ToolServerMonitor_1 | return loop.run_until_complete(main) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete ToolServerMonitor_1 | return future.result() ToolServerMonitor_1 | File "/app/main.py", line 42, in check_nodes_status_loop ToolServerMonitor_1 | await check_nodes_status() ToolServerMonitor_1 | File "/app/main.py", line 12, in check_nodes_status ToolServerMonitor_1 | async for node in nodes: ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 1390, in next ToolServerMonitor_1 | if self.alive and (self._buffer_size() or await self._get_more()): ToolServerMonitor_1 | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run ToolServerMonitor_1 | result = self.fn(*self.args, **self.kwargs) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1179, in _refresh ToolServerMonitor_1 | self.__send_message(q) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1060, in __send_message ToolServerMonitor_1 | response = client._run_operation( ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper ToolServerMonitor_1 | return func(self, *args, **kwargs) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation ToolServerMonitor_1 | return self._retryable_read( ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper ToolServerMonitor_1 | return func(self, *args, **kwargs) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1526, in _retryable_read ToolServerMonitor_1 | with self._conn_from_server(read_pref, server, session) as ( ToolServerMonitor_1 | File "/usr/local/lib/python3.10/contextlib.py", line 135, in **enter** ToolServerMonitor_1 | return next(self.gen) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1324, in _conn_from_server ToolServerMonitor_1 | with self._checkout(server, session) as conn: ToolServerMonitor_1 | File "/usr/local/lib/python3.10/contextlib.py", line 135, in **enter** ToolServerMonitor_1 | return next(self.gen) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1246, in _checkout ToolServerMonitor_1 | with server.checkout(handler=err_handler) as conn: ToolServerMonitor_1 | File "/usr/local/lib/python3.10/contextlib.py", line 135, in **enter** ToolServerMonitor_1 | return next(self.gen) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1598, in checkout ToolServerMonitor_1 | conn = self._get_conn(handler=handler) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1714, in _get_conn ToolServerMonitor_1 | conn = self.connect(handler=handler) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1568, in connect ToolServerMonitor_1 | conn.authenticate() ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1042, in authenticate ToolServerMonitor_1 | auth.authenticate(creds, self, reauthenticate=reauthenticate) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 616, in authenticate ToolServerMonitor_1 | auth_func(credentials, conn) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 521, in _authenticate_default ToolServerMonitor_1 | return _authenticate_scram(credentials, conn, "SCRAM-SHA-1") ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 248, in _authenticate_scram ToolServerMonitor_1 | res = conn.command(source, cmd) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 315, in inner ToolServerMonitor_1 | return func(*args, **kwargs) ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 932, in command ToolServerMonitor_1 | return command( ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/network.py", line 191, in command ToolServerMonitor_1 | helpers._check_command_response( ToolServerMonitor_1 | File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 223, in _check_command_response ToolServerMonitor_1 | raise OperationFailure(errmsg, code, response, max_wire_version) ToolServerMonitor_1 | pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

请问这个问题解决了吗？
