### ISSUE TITLE
使用docker-compose up --build时出现问题

### ISSUE THREAD

**Issue by CQxiaocaimi** [OpenBMB/XAgent#220]
如题，构建镜像时基本都完成了，但最后卡在RUN pip install playwright && playwright install chromium &&  playwright install-deps这里，一直运行着，也不报错，我等了一个多小时还是这样。
我浏览了所有问题，尝试过你们说的各种方法都没能解决，我确认我的网络是没问题的，其他也没问题。

**Comment by Umpire2018** [comment]
请参考 [此链接](https://stackoverflow.com/questions/64804749/why-is-docker-build-not-showing-any-output-from-commands) 中的教程增加详细日志输出来进行问题定位。
