### ISSUE TITLE
XAgent官网在线验收一直卡死不显示

### ISSUE THREAD

**Issue by zgaox2015** [OpenBMB/XAgent#229]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
https://x-agent.net/playground/chat/runshared/a16ffba2bb81499c913fd818dece2b1c

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by ChengFai** [comment]
你好，请问能否详细描述一下在线验收是指？  （x-agent服务器我们近日会尽快部署）
