### ISSUE TITLE
增加本地LLM与Xagent联合使用的案例

### ISSUE THREAD

**Issue by hiDaDeng** [OpenBMB/XAgent#233]
## Feature Description / 功能描述
增加本地LLM与Xagent联合使用的案例

## Goal / 目标
本地离线使用Xagent

## Alternative Solutions / 其他解决方案
例如使用 chatGLM3 本地安装， 构造openai化的接口， 可以直接与Xagent使用。

**Comment by luyaxi** [comment]
我们正式发布了[XAgentGen](https://github.com/OpenBMB/XAgent/tree/main/XAgentGen)以支持本地模型调用，欢迎试用！
