### ISSUE TITLE
关于调用 ernie-bot-4 模型的疑问

### ISSUE THREAD

**Issue by CQxiaocaimi** [OpenBMB/XAgent#235]
我修改了openai.py和obj_generator里的一些内容，以调用ernie-bot-4，运行时出现问题，查看docker-compose报错：
XAgent-Server | KeyError: 'Could not automatically map ernie-bot-4 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
XAgent-Server | INFO: connection closed

我没搞懂哪里出了问题。

**Comment by luyaxi** [comment]
请关注`XAgent/utils.py`中的tokenizer计数问题，需要提供模型的分词器给XAgent以支持Context管理功能。另外，XAgent要求模型具备`function call`功能，请事先确认模型支持这一功能。
