### ISSUE TITLE
必须使用docker运行项目吗？

### ISSUE THREAD

**Issue by xiaog929** [OpenBMB/XAgent#24]
租用的服务器不支持docker操作，可不可以不用docker部署项目呢

**Comment by luyaxi** [comment]
如果不使用docker，您需要承担不稳定运行的风险。我们不鼓励将XAgent部署到裸机运行

**Comment by ZSCDumin** [comment]
> 如果不使用docker，您需要承担不稳定运行的风险。我们不鼓励将XAgent部署到裸机运行

怎么不使用docker在本地运行呢？
