### ISSUE TITLE
这主要是由于网络问题导致的错误，请修改dockerfile中关于设置pypi镜像语句（修改为可以正确连接的镜像源），并重新构建镜像

### ISSUE THREAD

**Issue by Zoom-kai** [OpenBMB/XAgent#241]
这主要是由于网络问题导致的错误，请修改dockerfile中关于设置pypi镜像语句（修改为可以正确连接的镜像源），并重新构建镜像

_Originally posted by @luyaxi in https://github.com/OpenBMB/XAgent/issues/48#issuecomment-1772702380_
            
大佬，我现在也是这个报错，我也想知道这个要怎么修改，修改成什么样的镜像源能够拉到xagent所需要的镜像呢

**Comment by luyaxi** [comment]
请使用最新的代码，执行`docker compose pull`，直接拉取我们预先构建好的镜像
