### ISSUE TITLE
是否支持国产模型呢？GLM6B太弱了，智谱AI好像还不提供函数调用吧

### ISSUE THREAD

**Issue by johnson7788** [OpenBMB/XAgent#243]

**Comment by Peter-Hamster** [comment]
确实，国产化可能挺重要的。
之后能不能用智谱 chatglm_turbo 的 API 呢？
https://open.bigmodel.cn/dev/api#chatglm_turbo

**Comment by Umpire2018** [comment]
您好，当前请使用我们提供的 [XAgenllama](https://huggingface.co/collections/XAgentTeam/xagentllm-655ae4091c419bb072940e74) ,  其余事项我们会在未来考虑。

**Comment by Turingforce** [comment]
> 您好，当前请使用我们提供的 [XAgenllama](https://huggingface.co/collections/XAgentTeam/xagentllm-655ae4091c419bb072940e74) , 其余事项我们会在未来考虑。

XAgentLlama能否通过[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)这种类型的服务进行API接口封装呢，还是只能通过[XAgentGen&docker](https://github.com/OpenBMB/XAgent/blob/dev/XAgentGen/README.md)使用呢？

**Comment by Umpire2018** [comment]
> XAgentLlama能否通过[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)这种类型的服务进行API接口封装呢，还是只能通过[XAgentGen&docker](https://github.com/OpenBMB/XAgent/blob/dev/XAgentGen/README.md)使用呢？

当前暂无计划为其适配Chat前端，其设计目的仅为配合 XAgent 使用，所以是的，只能通过XAgentGen&docker进行使用。

**Comment by Turingforce** [comment]
> > XAgentLlama能否通过[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)这种类型的服务进行API接口封装呢，还是只能通过[XAgentGen&docker](https://github.com/OpenBMB/XAgent/blob/dev/XAgentGen/README.md)使用呢？
> 
> 当前暂无计划为其适配Chat前端，其设计目的仅为配合 XAgent 使用，所以是的，只能通过XAgentGen&docker进行使用。

好的，谢谢
