### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by gonkillu** [OpenBMB/XAgent#244]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
启动服务后，在http://localhost:5173页面用default admin/xagent-admin登陆不了
<img width="758" alt="Screenshot 2023-11-23 at 2 20 58 PM" src="https://github.com/OpenBMB/XAgent/assets/98017139/1cd45135-d263-453c-bc52-8858dc7b9064">

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
**因为端口被占用，所以我修改了端口号。**
ToolServerManager:
    image: tool-server-manager:0.2
    build:
      context: ./
      dockerfile: dockerfiles/ToolServerManager/Dockerfile
    ports:
      - 8800:8800

XAgentServer:
    image: xagent-server:0.3
    build:
      context: ./
      dockerfile: dockerfiles/XAgentServer/Dockerfile
    container_name: XAgent-Server
    env_file:
      - .env
    environment:
      - TOOLSERVER_URL=http://ToolServerManager:8800
    volumes:
      - ./assets:/app/assets:ro
    ports:
      - "5173:5173"
      - "8880:8880"

**然后把对应的dockerfile的端口号也改了**
**ToolServerManager的dockerfile：**

HEALTHCHECK --interval=30s --timeout=5s --start-period=1s --retries=3 CMD ["bash", "-c", "curl -sS 'http://localhost:8800/alive' || exit 1"]

ENTRYPOINT [ "gunicorn", "main:app", "-b","0.0.0.0:8800","--worker-class","uvicorn.workers.UvicornWorker"]

**XAgentServer的dockerfile：**
FROM python:3.10 AS XAgentServer
EXPOSE 8880

**envs.py里**
 port = 8880

**nginx.conf里**
server {
        listen       5173;
        server_name  [服务器ip]; 	# 127.0.0.1
        # This is frontend request
        location / {
            root /app/dist;
			index  index.html;
			try_files $uri $uri/ /index.html;
        }
        # Dynamic request. This is Backend request
        location /api {
            proxy_pass http://[服务器ip]:8880;
            proxy_set_header Host $host;
            rewrite "^/api/(.*)$" /$1 break;
        }
		location ^~ /ws {
	    	proxy_pass http://[服务器ip]:8880/ws;
            proxy_set_header Host $host;
	    	proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
		}

然后走docker-compose up --build
之后启动docker exec XAgent-Server systemctl start nginx
打开http://localhost:5173页面后就会login failed

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：Linux
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by sailaoda** [comment]
您好，默认用户应该是：Guest/xagent 哈，我们确认一下前端页面默认账户是否是admin，如果是的话我们将进行修改。感谢您的issue

**Comment by sailaoda** [comment]
您好，经过确认前端账户默认是 Guest/xagent 哈，您可以重新拉一下镜像看看。
