### ISSUE TITLE
远端请求无响应

### ISSUE THREAD

**Issue by fengyun99** [OpenBMB/XAgent#247]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
在云端部署的项目无法回答问题，本地部署使用可以成功。云端请求发送后，docker出现响应的日志，前端发送的请求未到达云端。想具体问下这个请求需要修改哪部分代码。
## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
![image](https://github.com/OpenBMB/XAgent/assets/46964946/86541c74-250f-4235-a217-2563d52f7ce8)

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
能在在本地访问云端部署的项目后返回结果。

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu 22.04
- Python Version / Python 版本： 3.10.9
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
![image](https://github.com/OpenBMB/XAgent/assets/46964946/d66a0acc-3064-4c2c-b298-40d1cfe920d0)
发送请求后日志停留此处无法继续响应。
## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by sailaoda** [comment]
您好，请问您的云端访问是访问的云端部署的前端还是本地的前端    根据您展示的前端请求的修改需求，您可以在XAgentWeb文件夹下的 .env.*文件夹进行修改对应自己服务器上的后端服务
