### ISSUE TITLE
 error while mounting volume '/var/lib/docker/volumes/toolserverconfig/_data':

### ISSUE THREAD

**Issue by mel2oo** [OpenBMB/XAgent#249]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

docker-compose up后报错： error while mounting volume '/var/lib/docker/volumes/toolserverconfig/_data':

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：ubuntu
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
![image](https://github.com/OpenBMB/XAgent/assets/41185794/1cefe35b-9235-47fb-9f1c-b3d7528901db)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by mel2oo** [comment]
${PWD}/assets/config

**Comment by zhaotaotao3276** [comment]
> ${PWD}/assets/config

what means?

**Comment by mel2oo** [comment]
可能是我系统配置的原因，我修改了docker-compose后可以正常起来了，但好像进行聊天时仍然有报错，不知道是哪边没有配置正确。

![image](https://github.com/OpenBMB/XAgent/assets/41185794/966140d9-baf1-4f39-b30a-84e127dcd483)

**Comment by zhaotaotao3276** [comment]
> 可能是我系统配置的原因，我修改了docker-compose后可以正常起来了，但好像进行聊天时仍然有报错，不知道是哪边没有配置正确。
> 
> ![image](https://user-images.githubusercontent.com/41185794/285406961-966140d9-baf1-4f39-b30a-84e127dcd483.png)

docker-compose修改了哪里呀？

**Comment by mel2oo** [comment]
> > 可能是我系统配置的原因，我修改了docker-compose后可以正常起来了，但好像进行聊天时仍然有报错，不知道是哪边没有配置正确。
> > ![image](https://user-images.githubusercontent.com/41185794/285406961-966140d9-baf1-4f39-b30a-84e127dcd483.png)
> 
> docker-compose修改了哪里呀？

![image](https://github.com/OpenBMB/XAgent/assets/41185794/667e351f-08d1-4cb3-a9df-6bb016e4ed17)

**Comment by zhaotaotao3276** [comment]
> > > 可能是我系统配置的原因，我修改了docker-compose后可以正常起来了，但好像进行聊天时仍然有报错，不知道是哪边没有配置正确。
> > > ![image](https://user-images.githubusercontent.com/41185794/285406961-966140d9-baf1-4f39-b30a-84e127dcd483.png)
> > 
> > 
> > docker-compose修改了哪里呀？
> 
> ![image](https://user-images.githubusercontent.com/41185794/285407722-667e351f-08d1-4cb3-a9df-6bb016e4ed17.png)

感谢大佬！！！

**Comment by mel2oo** [comment]
> > > > 可能是我系统配置的原因，我修改了docker-compose后可以正常起来了，但好像进行聊天时仍然有报错，不知道是哪边没有配置正确。
> > > > ![image](https://user-images.githubusercontent.com/41185794/285406961-966140d9-baf1-4f39-b30a-84e127dcd483.png)
> > > 
> > > 
> > > docker-compose修改了哪里呀？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41185794/285407722-667e351f-08d1-4cb3-a9df-6bb016e4ed17.png)
> 
> 感谢大佬！！！

似乎不用改配置文件，把assets配置文件夹拷贝到ToolServer就可以了，或者在根目录下构建。好像是readme上的有些问题。
