### ISSUE TITLE
网页进不去是咋回事呢？

### ISSUE THREAD

**Issue by xiaog929** [OpenBMB/XAgent#25]
![image](https://github.com/OpenBMB/XAgent/assets/75246377/7795b1cf-8779-46d5-a6cf-f637239413ab)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/87bcbe7d-e4a4-4ada-a8d9-ec9c0fb0fd26)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/b5e1c291-d07d-42d0-b1fc-8199eec2f7fd)
登不进去

**Comment by ChengFai** [comment]
登录提示这个我们会尽快修复，您运行了后端开启了服务吗

**Comment by sailaoda** [comment]
Thanks for your advice, it will work now.You can use "admin" to login in.

**Comment by xiaog929** [comment]
![image](https://github.com/OpenBMB/XAgent/assets/75246377/cef7b020-86c9-435f-9ca4-d8763c10bcdb)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/b6215c49-b35d-4609-b207-2e271855a497)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/86c3398b-9203-4b37-ab36-4d9e98e52882)
![image](https://github.com/OpenBMB/XAgent/assets/75246377/2f08fca3-833f-4733-bd28-1f936f11f2be)
还是登录失败呀，我代码是git的最新的呀

**Comment by sailaoda** [comment]
您好，您看访问 localhost:5173 可以吗

**Comment by sailaoda** [comment]
您好，您看看您的XAgent-Server是否是docker启动的，如果是的话可能需要清除之前的docker镜像重新build
