### ISSUE TITLE
web端聊天报错：AttributeError: 'ToolServerInterface' object has no attribute 'cookies'

### ISSUE THREAD

**Issue by mel2oo** [OpenBMB/XAgent#250]
## Issue Description / 问题描述
docker-compose up启动之后，在web端发起聊天请求，XAgent-Server与xagent-ToolServerManager-1报错

## Environment / 环境信息
- Operating System / 操作系统： ubuntu

## Error Screenshots or Logs / 错误截图或日志

![image](https://github.com/OpenBMB/XAgent/assets/41185794/1458e09b-1e3d-46dd-8ba5-544f9b43c9da)

![image](https://github.com/OpenBMB/XAgent/assets/41185794/198e0fa9-6ab3-45ba-ac30-02901a6718e9)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by mel2oo** [comment]
似乎是readme上所说的进入ToolServer构建，导致目录挂载有问题。

**Comment by Umpire2018** [comment]
Please execute `docker compose up` in root dir. We have updated `README.md`, thanks for report.
