### ISSUE TITLE
Completions.create() got an unexpected keyword argument 'organization'

### ISSUE THREAD

**Issue by wan9wu** [OpenBMB/XAgent#252]
## Issue Description / 问题描述
我根据B站教程：https://www.bilibili.com/video/BV14c41167NL/
配置xagent，进入chat页面后，输入一个请求，一直卡在Outer Loop，过了一会儿提示以下错误。
Completions.create() got an unexpected keyword argument 'organization'

在docker命令行中相关提示的错误如下：
XAgent-Server               | Error in task_handler of 4becc94245684050a345b: Completions.create() got an unexpected keyword argument 'organization'  
XAgent-Server               | Send data to 4becc94245684050a345b:   已发送249c7c9c3baa417aa48cc1节点的数据, 长度：72
XAgent-Server               | Disconnect with client 4becc94245684050a345b:   
XAgent-Server               |   shutdown scheduler
XAgent-Server               |   close db

请问应该如何排查呢？

**Comment by wan9wu** [comment]
等了一会儿又看到了详细错误信息：
Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 91, in interact
XAgent-Server               |     task_handler.outer_loop()
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 82, in outer_loop
XAgent-Server               |     self.plan_agent.initial_plan_generation(
XAgent-Server               |   File "/app/XAgent/workflow/plan_exec.py", line 164, in initial_plan_generation
XAgent-Server               |     new_message , _ = agent.parse(
XAgent-Server               |   File "/app/XAgent/agent/plan_generate_agent/agent.py", line 49, in parse
XAgent-Server               |     return self.generate(
XAgent-Server               |   File "/app/XAgent/agent/base_agent.py", line 121, in generate
XAgent-Server               |     response = objgenerator.chatcompletion(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server               |     return self(f, *args, **kw)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server               |     do = self.iter(retry_state=retry_state)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
XAgent-Server               |     return fut.result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server               |     return self.__get_result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server               |     raise self._exception
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server               |     result = fn(*args, **kwargs)
XAgent-Server               |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 66, in chatcompletion
XAgent-Server               |     raise e
XAgent-Server               |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
XAgent-Server               |     response = self._get_chatcompletion_request_func(request_type)(**kwargs)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server               |     return self(f, *args, **kw)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server               |     do = self.iter(retry_state=retry_state)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
XAgent-Server               |     raise retry_exc.reraise()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
XAgent-Server               |     raise self.last_attempt.result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server               |     return self.__get_result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server               |     raise self._exception
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server               |     result = fn(*args, **kwargs)
XAgent-Server               |   File "/app/XAgent/ai_functions/request/openai.py", line 152, in chatcompletion_request
XAgent-Server               |     completions = client.chat.completions.create(**chatcompletion_kwargs)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
XAgent-Server               |     return func(*args, **kwargs)
XAgent-Server               | TypeError: Completions.create() got an unexpected keyword argument 'organization'
XAgent-Server               | 
XAgent-Server               | The above exception was the direct cause of the following exception:
XAgent-Server               | 
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/application/websockets/base.py", line 324, in task_handler
XAgent-Server               |     server.interact(interaction=interaction)
XAgent-Server               |   File "/app/XAgentServer/server.py", line 93, in interact
XAgent-Server               |     raise XAgentRunningError(str(e)) from e
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentRunningError: Completions.create() got an unexpected keyword argument 'organization'
XAgent-Server               | INFO:     connection closed

**Comment by Umpire2018** [comment]
gpt-4:    
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4
      
 若你不清楚 `organization` 用处，请移除配置文件中该行 `organization: org-xxxxx`.

**Comment by wan9wu** [comment]
> ```yaml
> gpt-4:    
>     - api_key: sk-xxxxx
>       organization: org-xxxxx
>       model: gpt-4
> ```
> 
> 若你不清楚 `organization` 用处，请移除配置文件中该行 `organization: org-xxxxx`.

按此方法解决了，谢谢！
