### ISSUE TITLE
Outlines integration

### ISSUE THREAD

**Issue by rlouf** [OpenBMB/XAgent#255]
Author of Outlines here. I have noticed that you copied verbatim some portions of Outlines' codebase. Outlines is [Apache 2.0 licenced](https://www.apache.org/licenses/LICENSE-2.0) which means that you can only copy the code if you meet the following conditions:

1. You must give any other recipients of the Work or Derivative Works a copy of this License; and
2. You must cause any modified files to carry prominent notices stating that You changed the files; and
3. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
4. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

Unless I am mistaken, none of these conditions are met here. Also if I were you I would import the library, which we are continuously improving, instead of having to maintain all of this.

**Comment by AL-377** [comment]
> Author of Outlines here. I have noticed that you copied verbatim some portions of Outlines' codebase. Outlines is [Apache 2.0 licenced](https://www.apache.org/licenses/LICENSE-2.0) which means that you can only copy the code if you meet the following conditions:
> 
> 1. You must give any other recipients of the Work or Derivative Works a copy of this License; and
> 2. You must cause any modified files to carry prominent notices stating that You changed the files; and
> 3. You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
> 4. If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.
> 
> Unless I am mistaken, none of these conditions are met here. Also if I were you I would import the library, which we are continuously improving, instead of having to maintain all of this.

Sorry，I must extend my apologies for any oversight in the code review process, especially concerning the licensing conditions. Your reminder regarding the Apache 2.0 license was incredibly helpful, and I fully acknowledge the need to adhere strictly to it.

Besides, I wanted to take a moment to express my sincere appreciation for your incredible work on Outlines. It's an exceptional project, and your dedication to its development is truly commendable.

And I'm committed to promptly modify the code and  ensure all necessary attributions.

Your guidance and understanding in this matter are immensely appreciated, and I'm grateful for the opportunity to rectify this oversight. Thank you for your patience and for your invaluable contributions to the open-source community through Outlines.

**Comment by rlouf** [comment]
This can happen. I'm curious to know why you are not importing the library instead?

**Comment by AL-377** [comment]
> This can happen. I'm curious to know why you are not importing the library instead?

It's no exaggeration to say that Outlines can almost handle everything, we really appreciate that. 😊
We modified some modules for the listed reasons: 
1. We noticed that sometimes it will generate some unwanted tokens like json with invalid  escape character or large amounts of '\n'. It is harmful to the function call process, so we modified the json_schema
2. We defined some special function schemas with nested types which may not be supported in the old version of Outlines(0.0.9), so we implemented some in the json_schema.
3. We added some useful extensions like generate params and cache.

Since the latest Outlines has solved many problems above, we believe that maybe there are some redundant modification. 

And We have modified the integration of Outlines 0.0.11，you can check the details here: [FIX:outlines integration](https://github.com/OpenBMB/XAgent/commit/02febc501d49f507e22cd95242ac5520d0808c8e)

Thanks again for the incredible work on Outlines.And once again I would like to express my sincere apologies.

**Comment by rlouf** [comment]
Makes sense! It would make sense to open PRs on Outlines whenever you're fixing something so the entire community can benefit from it 😊
