### ISSUE TITLE
XAgentAuthError: user is not exist!

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [OpenBMB/XAgent#256]
error:

XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
XAgent-Server               |     return self.receive_nowait()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
XAgent-Server               |     raise WouldBlock
XAgent-Server               | anyio.WouldBlock
XAgent-Server               | 
XAgent-Server               | During handling of the above exception, another exception occurred:
XAgent-Server               | 
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
XAgent-Server               |     message = await recv_stream.receive()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
XAgent-Server               |     raise EndOfStream
XAgent-Server               | anyio.EndOfStream
XAgent-Server               | 
XAgent-Server               | During handling of the above exception, another exception occurred:
XAgent-Server               | 
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/application/main.py", line 28, in db_session_middleware
XAgent-Server               |     response = await call_next(request)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
XAgent-Server               |     raise app_exc
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
XAgent-Server               |     await self.app(scope, receive_or_disconnect, send_no_error)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
XAgent-Server               |     raise exc
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
XAgent-Server               |     await self.app(scope, receive, sender)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
XAgent-Server               |     raise e
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
XAgent-Server               |     await self.app(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
XAgent-Server               |     await route.handle(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
XAgent-Server               |     await self.app(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
XAgent-Server               |     response = await func(request)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 264, in app
XAgent-Server               |     solved_result = await solve_dependencies(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 594, in solve_dependencies
XAgent-Server               |     solved = await run_in_threadpool(call, **sub_values)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
XAgent-Server               |     return await anyio.to_thread.run_sync(func, *args)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
XAgent-Server               |     return await get_asynclib().run_sync_in_worker_thread(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
XAgent-Server               |     return await future
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
XAgent-Server               |     result = context.run(func, *args)
XAgent-Server               |   File "/app/XAgentServer/application/routers/conv.py", line 41, in user_is_available
XAgent-Server               |     raise XAgentAuthError("user is not exist!")
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentAuthError: user is not exist!
XAgent-Server               |   XAgent Service Startup Param:
XAgent-Server               |             app: app:app
XAgent-Server               |             prod: False
XAgent-Server               |             base_dir: XAgentServer
XAgent-Server               |             use_redis: False
XAgent-Server               |             recorder_root_dir: running_records
XAgent-Server               |             default_login: True
XAgent-Server               |             check_running: False
XAgent-Server               |             host: 0.0.0.0
XAgent-Server               |             port: 8090
XAgent-Server               |             debug: True
XAgent-Server               |             reload: True
XAgent-Server               |             workers: 1
XAgent-Server               |             share_url: https://x-agent.net/api/conv/community
XAgent-Server               |             DB: <class 'XAgentServer.application.core.envs.XAgentServerEnv.DB'>
XAgent-Server               |             Redis: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Redis'>
XAgent-Server               |             Email: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Email'>
XAgent-Server               |             Upload: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Upload'>
XAgent-Server               | XAgent Service Init Dependence.  
XAgent-Server               | init a thread pool executor, max_workers: 1  
XAgent-Server               | XAgent Service Init Dependence: Complete!  
XAgent-Server               | Default user: Guest, token: xagent, you can use it to login  
XAgent-Server               | XAgent Server Dependences:  
XAgent-Server               |         Python: 3.10+ 
XAgent-Server               |         FastAPI: Http server
XAgent-Server               |         Websocket: long connect with client
XAgent-Server               |         MySQL: save xagent data
XAgent-Server               |         SqlAlchemy: ORM with MySQL
XAgent-Server               |         Redis: save status of interaction
XAgent-Server               |         Threading: run interaction
XAgent-Server               |         APScheduler: send data to client and keep alive
XAgent-Server               |         FastAPI APIRouter: manage websocket route
XAgent-Server               |         XAgentError: XAgentServer.exts.exception_ext
XAgent-Server               | XAgent Server Version:  
XAgent-Server               |         V 1.1.0
XAgent-Server               | Notes:  
XAgent-Server               |         Since V 1.1.0, 
XAgent-Server               |         Local storage will no longer be supported, replaced by Mysql.
XAgent-Server               |         The service depends on Redis and Mysql, 
XAgent-Server               |         so you need to install Redis and Mysql before using it.
XAgent-Server               |         Before you use this service, please ensure that the following services are available:
XAgent-Server               |             1. Redis on docker, port: 6379, you can start it by docker, default password: xagent
XAgent-Server               |             2. Mysql on docker, port: 3306, you can start it by docker
XAgent-Server               |             3. XAgent Tool Server is runnning on port 8080
XAgent-Server               |             4. Port 8090 is not occupied
XAgent-Server               |         
XAgent-Server               | INFO:     127.0.0.1:44680 - "POST /conv/getUserInteractions HTTP/1.0" 401 Unauthorized
XAgent-Server               | INFO:     127.0.0.1:44674 - "POST /conv/getSharedInteractions HTTP/1.0" 401 Unauthorized
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
XAgent-Server               |     return self.receive_nowait()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
XAgent-Server               |     raise WouldBlock
XAgent-Server               | anyio.WouldBlock
XAgent-Server               | 
XAgent-Server               | During handling of the above exception, another exception occurred:
XAgent-Server               | 
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
XAgent-Server               |     message = await recv_stream.receive()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
XAgent-Server               |     raise EndOfStream
XAgent-Server               | anyio.EndOfStream
XAgent-Server               | 
XAgent-Server               | During handling of the above exception, another exception occurred:
XAgent-Server               | 
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/application/main.py", line 28, in db_session_middleware
XAgent-Server               |     response = await call_next(request)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
XAgent-Server               |     raise app_exc
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
XAgent-Server               |     await self.app(scope, receive_or_disconnect, send_no_error)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
XAgent-Server               |     raise exc
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
XAgent-Server               |     await self.app(scope, receive, sender)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
XAgent-Server               |     raise e
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
XAgent-Server               |     await self.app(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
XAgent-Server               |     await route.handle(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
XAgent-Server               |     await self.app(scope, receive, send)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
XAgent-Server               |     response = await func(request)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 264, in app
XAgent-Server               |     solved_result = await solve_dependencies(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 594, in solve_dependencies
XAgent-Server               |     solved = await run_in_threadpool(call, **sub_values)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
XAgent-Server               |     return await anyio.to_thread.run_sync(func, *args)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
XAgent-Server               |     return await get_asynclib().run_sync_in_worker_thread(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
XAgent-Server               |     return await future
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
XAgent-Server               |     result = context.run(func, *args)
XAgent-Server               |   File "/app/XAgentServer/application/routers/conv.py", line 41, in user_is_available
XAgent-Server               |     raise XAgentAuthError("user is not exist!")
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentAuthError: user is not exist!

**Comment by Umpire2018** [comment]
Please first use the "Log out" option in the settings located at the bottom left corner to refresh the browser cache, and then try again.
![image](https://github.com/OpenBMB/XAgent/assets/138990495/f24a06b1-59ae-4eee-9c19-45ecdf30b520)
