### ISSUE TITLE
Set organization in config but get `TypeError: Completions.create() got an unexpected keyword argument 'organization'`

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [OpenBMB/XAgent#258]
error：

XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 91, in interact
XAgent-Server               |     task_handler.outer_loop()
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 82, in outer_loop
XAgent-Server               |     self.plan_agent.initial_plan_generation(
XAgent-Server               |   File "/app/XAgent/workflow/plan_exec.py", line 164, in initial_plan_generation
XAgent-Server               |     new_message , _ = agent.parse(
XAgent-Server               |   File "/app/XAgent/agent/plan_generate_agent/agent.py", line 49, in parse
XAgent-Server               |     return self.generate(
XAgent-Server               |   File "/app/XAgent/agent/base_agent.py", line 121, in generate
XAgent-Server               |     response = objgenerator.chatcompletion(
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server               |     return self(f, *args, **kw)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server               |     do = self.iter(retry_state=retry_state)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
XAgent-Server               |     return fut.result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server               |     return self.__get_result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server               |     raise self._exception
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server               |     result = fn(*args, **kwargs)
XAgent-Server               |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 66, in chatcompletion
XAgent-Server               |     raise e
XAgent-Server               |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
XAgent-Server               |     response = self._get_chatcompletion_request_func(request_type)(**kwargs)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server               |     return self(f, *args, **kw)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server               |     do = self.iter(retry_state=retry_state)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
XAgent-Server               |     raise retry_exc.reraise()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
XAgent-Server               |     raise self.last_attempt.result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server               |     return self.__get_result()
XAgent-Server               |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server               |     raise self._exception
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server               |     result = fn(*args, **kwargs)
XAgent-Server               |   File "/app/XAgent/ai_functions/request/openai.py", line 152, in chatcompletion_request
XAgent-Server               |     completions = client.chat.completions.create(**chatcompletion_kwargs)
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
XAgent-Server               |     return func(*args, **kwargs)
XAgent-Server               | TypeError: Completions.create() got an unexpected keyword argument 'organization'

my config：
![image](https://github.com/OpenBMB/XAgent/assets/144103401/0ca88202-b318-4362-a6b5-99abba13654a)

**Comment by Umpire2018** [comment]
![image](https://github.com/OpenBMB/XAgent/assets/138990495/63dafdb7-84f2-493f-a8ab-4c0fba947993)

@shanmu-raoyunfei Please try again with the lastest code. Shout out to @luyaxi .

**Comment by shanmu-raoyunfei** [comment]
I deleted this configuration item and it's working fine
