### ISSUE TITLE
run.py ModuleNotFoundError: No module named `inputimeout`

### ISSUE THREAD

**Issue by peacerman** [OpenBMB/XAgent#260]
## Issue Description / 问题描述
python run.py --task "My TASK " --model "gpt-4" --config_file "assets/config.yml"  

Traceback (most recent call last):
  File "/workspaces/XAgent/run.py", line 6, in <module>
    from command import CommandLine,CommandLineParam
  File "/workspaces/XAgent/command.py", line 29, in <module>
    from command_input import CommandLineInput
  File "/workspaces/XAgent/command_input.py", line 7, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'

## Steps to Reproduce / 复现步骤
python run.py --task "My TASK " --model "gpt-4" --config_file "assets/config.yml" 

## Environment / 环境信息
codespace 

## Error Screenshots or Logs / 错误截图或日志
![image](https://github.com/OpenBMB/XAgent/assets/49969080/0c95cafe-235c-4c53-bdf0-85380cc16199)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by luyaxi** [comment]
Please install package `inputimeout` and try a again. It seems caused by improper package management and we will keep improve it.
