### ISSUE TITLE
调用WebEnv_search_and_browse功能时会报连接超时错误

### ISSUE THREAD

**Issue by YinSonglin1997** [OpenBMB/XAgent#265]
## Issue Description / 问题描述
XAgent运行时调用WebEnv_search_and_browse功能会显示超时，但是调用WebEnv_browse_website功能成功。

## Steps to Reproduce / 复现步骤
[https://github.com/OpenBMB/XAgent/tree/main/XAgentGen](url)

## Expected Behavior / 预期行为
调用功能成功

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu 20.04.6 LTS
- Python Version / Python 版本：Python 3.10.0
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![1701136033781](https://github.com/OpenBMB/XAgent/assets/90330685/86f732de-8af9-4d3b-838e-85ac81429448)

**Comment by luyaxi** [comment]
如果你的网络不能访问duckduckgo，请申请bing搜索api并使用bing搜索

**Comment by YinSonglin1997** [comment]
> 如果你的网络不能访问duckduckgo，请申请bing搜索api并使用bing搜索

感谢您的回复，您可以详细讲一下具体在哪个位置进行修改bing搜索吗？

**Comment by luyaxi** [comment]
> > 如果你的网络不能访问duckduckgo，请申请bing搜索api并使用bing搜索
> 
> 感谢您的回复，您可以详细讲一下具体在哪个位置进行修改bing搜索吗？

将你的bing搜索api key填入`assets/config/node.yml`，并重启docker服务
