### ISSUE TITLE
关于ToolServerMonitor和xagentllm镜像的两个疑问

### ISSUE THREAD

**Issue by yyliuCecilia** [OpenBMB/XAgent#268]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
**第一个问题是：
https://github.com/OpenBMB/XAgent/blob/main/ToolServer/README_ZH.md 这里提到ToolServer由3个部件组成，但是ToolServerMonitor在928a696e86119a41334d682cb96e55d7e1767380中被移除

第二个问题是：
xagentllm是在需要调用的情况下，才构建或拉取镜像？因此不写在docker-compose.yml中吗？**

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by AL-377** [comment]
非常感谢您的关注和提问，这里主要解释第二个问题：
（1）xagentllm主要为了支持使用本地模型运行XAgent，使用本地模型构建服务，和项目其他模块相对独立
（2）当前xagentllm运行XAgent依赖XAgentGen模块，编译镜像速度较慢，建议使用时直接从docker hub中拉取，详情见[XAgentGen](https://github.com/OpenBMB/XAgent/tree/main/XAgentGen)

**Comment by Umpire2018** [comment]
请 @luyaxi 回答第一个问题。

**Comment by luyaxi** [comment]
ToolServerMonitor 正处于实验性移除阶段

**Comment by yyliuCecilia** [comment]
> 非常感谢您的关注和提问，这里主要解释第二个问题： （1）xagentllm主要为了支持使用本地模型运行XAgent，使用本地模型构建服务，和项目其他模块相对独立 （2）当前xagentllm运行XAgent依赖XAgentGen模块，编译镜像速度较慢，建议使用时直接从docker hub中拉取，详情见[XAgentGen](https://github.com/OpenBMB/XAgent/tree/main/XAgentGen)

需要系统支持GPU，才可以运行XAgentGen镜像？

**Comment by AL-377** [comment]
是的，因为XAgentGen的目标是运行本地模型，支撑模型运行需要GPU
