### ISSUE TITLE
兼职申请——共同推动智能体技术的发展 

### ISSUE THREAD

**Issue by Umpire2018** [OpenBMB/XAgent#27]
请问贵司当前是否开放兼职申请，我的技术栈是 python, and i am ready to help.

**Comment by Umpire2018** [comment]
您好，很抱歉打扰了！

![image](https://github.com/OpenBMB/XAgent/assets/138990495/ba45200a-785b-40ad-841d-331d20b8dff6)

但当前我无法打开此网页，同时发送邮件后仍未得到答复，所以不得不在此反馈。

**Comment by ChengFai** [comment]
不用开梯子试试能不能打开。或者直接发邮件给: 
 xagentteam@gmail.com

**Comment by ChengFai** [comment]
帮您催了，会尽快回您的
