### ISSUE TITLE
request.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=13520): Max retries exceeded with url

### ISSUE THREAD

**Issue by HuntZhaozq** [OpenBMB/XAgent#270]
## Issue Description / 问题描述
request.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=13520): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError (failed to establish a new connection: [Errno 111] Connection refused'))
Constructing an Agent: PlanGenerateAgent.

## Steps to Reproduce / 复现步骤
docker compose up
docker run xagentllama
When I input the sentence in the WebUI. The above error comes. How to solve this ?
By the way, the `python run.py` works using xagentllama. But the WebUI occurs this error....

**Comment by Umpire2018** [comment]
Please attach relevant log.

**Comment by HuntZhaozq** [comment]
-=-=-=-=-=-=-=  GENERATE INITIAL_PLAN -=-=-=-=-=-=-=
Trackback (most recent call last):
 File " /usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
 File " /usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
 File " /usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Trackback (most recent call last):
 File " /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
   response = self._make_request(
 File " /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line  496, in_make_request
   conn.request(
 File " /usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, inrequest
   self.endheaders()
 File " /usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
   ......................
 File " /usr/local/lib/python3.10/site-packages/urllibs/connection.py" line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbf8ec074c>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:
Trackback (most recent call last):
.....
request.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=13520): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError (failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Umpire2018** [comment]
I believe you can do more than that.

**Comment by luyaxi** [comment]
You should not use the address 127.0.0.1:13520 in your config if you are using webui, which is running inside a docker container. This network address will be send to the port inside XAgentServer container, which is not correct at all. To use with webgui, you should attach XAgentGen container to network bridge `tool-server-network` and set the host name in request url to the container's name.

**Comment by HuntZhaozq** [comment]
> You should not use the address 127.0.0.1:13520 in your config if you are using webui, which is running inside a docker container. This network address will be send to the port inside XAgentServer container, which is not correct at all. To use with webgui, you should attach XAgentGen container to network bridge `tool-server-network` and set the host name in request url to the container's name.

How to attach XAgentGen container to network bridge `tool-server-network`. Could you please give more details?  And where to find the  `tool-server-network`.

**Comment by Umpire2018** [comment]
The `tool-server-network`, as a bridge network, acts as a virtual link between Docker containers, is defined in `docker-compose.yml`. You can add `--network tool-server-network` to docker run command to join the network.

**Comment by HuntZhaozq** [comment]
> The `tool-server-network`, as a bridge network, acts as a virtual link between Docker containers, is defined in `docker-compose.yml`. You can add `--network tool-server-network` to docker run command to join the network.

Then, use the `http://0.0.0.0:13520/chat/completions` to request the XAgentGen?
