### ISSUE TITLE
Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by wangjiainchinatelecom** [OpenBMB/XAgent#273]
## Issue Description / 问题描述
执行docker命令后报错

## Steps to Reproduce / 复现步骤
1. docker pull xagentteam/xagentgen:latest
2. 运行docker命令
docker run -it -p 13520:13520  -v /huggingface/models/XAgentLLaMa-34B-preview/:/model:rw --gpus all --ipc=host xagentteam/xagentgen:latest python app.py --model-path /model --port 13520

## Expected Behavior / 预期行为
docker容器正常启动

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu22.04
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:  

## Additional Notes / 其他备注
我的设备上有4块4090
![image](https://github.com/OpenBMB/XAgent/assets/19453231/f7e88051-e75c-42a7-92dd-763b6b3e6caa)

**Comment by Umpire2018** [comment]
Typically indicates a problem with Docker trying to access or use a GPU (Graphics Processing Unit) on your system.
<img width="496" alt="image" src="https://github.com/OpenBMB/XAgent/assets/138990495/fe3ce44b-04ee-41dc-953f-1f6d96d4b543">

**Comment by wangjiainchinatelecom** [comment]
谢谢,安装了nvidia-container-toolkit问题解决

**Comment by Turingforce** [comment]
> Typically indicates a problem with Docker trying to access or use a GPU (Graphics Processing Unit) on your system. <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/138990495/286504670-fe3ce44b-04ee-41dc-953f-1f6d96d4b543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTU4OTMsIm5iZiI6MTcwMTg1NTU5MywicGF0aCI6Ii8xMzg5OTA0OTUvMjg2NTA0NjcwLWZlM2NlNDRiLTA0ZWUtNDFkYy05NTNmLTFmNmQ5NmQ0YjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwOTM5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2ZlMDBkZTE4YTA2Mjc1ODY0ZGFmMWQxNGIwMTA3Yjc1OGE0MzE2MDMyZjUxOTRhM2Y1MDcwM2M0ZjY0N2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.panGmUvm3UdKK8uV_x4RwJHCy53_VkBT8eqKQtoKo3g">

安装了nvidia-container-toolkit还是不行可能是什么原因
![image](https://github.com/OpenBMB/XAgent/assets/82068701/8eff3921-43bc-49bd-bd08-9c6d390e0ab2)
