### ISSUE TITLE
使用全局代理时发生：requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/get_cookie

### ISSUE THREAD

**Issue by YinSonglin1997** [OpenBMB/XAgent#274]
## Issue Description / 问题描述
按照 [https://github.com/OpenBMB/XAgent/tree/main/XAgentGen#-2-use-the-xagent-with-the-customized-model](url) 执行命令python run.py --task "Write a bubble sort in python." --model "xagentllm" --config_file "assets/xagentllama.yml"时报错，但是当我没开代理时是能运行的。

## Steps to Reproduce / 复现步骤
[https://github.com/OpenBMB/XAgent/tree/main/XAgentGen](url)

## Expected Behavior / 预期行为
正确执行

## Environment / 环境信息
- Operating System / 操作系统：Ubuntu 20.04.6 LTS
- Python Version / Python 版本：Python 3.10.0
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![1701244782357](https://github.com/OpenBMB/XAgent/assets/90330685/d50e5440-940e-41e8-9e24-71beb462b0f8)

**Comment by Umpire2018** [comment]
我只能建议关闭全局代理，不要因为代理影响到连接性。

**Comment by YinSonglin1997** [comment]
> 我只能建议关闭全局代理，不要因为代理影响到连接性。

关闭代理运行时，在访问duckduckgo的时候会连接不上，bing的api key也没有，所以想打开代理。也就是说这个问题暂时还没有解决办法吗？
