### ISSUE TITLE
redis.exceptions.AuthenticationError

### ISSUE THREAD

**Issue by LeafTMO** [OpenBMB/XAgent#278]
Issue Description / 问题描述
I'm encountering an authentication error when trying to connect to Redis from my Python application. The error indicates that a password is being used for connection, but no password is set for the default user in Redis. / 在从 Python 应用程序连接到 Redis 时遇到认证错误。错误显示正在使用密码进行连接，但 Redis 中的默认用户没有设置密码。

Steps to Reproduce / 复现步骤
Start the Redis server without setting a password in the configuration. / 启动 Redis 服务器，不在配置中设置密码。
Run the Python application which tries to connect to the Redis server using a password. / 运行尝试使用密码连接到 Redis 服务器的 Python 应用程序。
Expected Behavior / 预期行为
The Python application should successfully connect to the Redis server without requiring a password, as no password is set for the default user in Redis. / Python 应用程序应该能够成功连接到 Redis 服务器，而不需要密码，因为 Redis 中的默认用户没有设置密码。

Environment / 环境信息
Operating System / 操作系统：Macos
Python Version / Python 版本：Python 3.11
Error Screenshots or Logs / 错误截图或日志
![image](https://github.com/OpenBMB/XAgent/assets/150100976/3c2716e0-9f71-4ba7-86f1-1eac81fa9e07)

**Comment by sailaoda** [comment]
hello, according to your log, you could rebuild the redis docker or the all docker. it may be caused by that the redis docker init wrongly on your os.
