### ISSUE TITLE
I need HOW_TO_BUILD_NEW_TOOLS.md, Thanks.

### ISSUE THREAD

**Issue by otakusbear** [OpenBMB/XAgent#279]
## Feature Description / 功能描述
为ToolServer添加自定义工具

## Goal / 目标
可自定义工具集成到ToolServer

## Expected Behavior / 预期行为
提供新增自定义工具的说明文档

## Alternative Solutions / 其他解决方案
无

## Additional Notes / 其他备注
谢谢！

**Comment by Umpire2018** [comment]
@tanz0710 @otakusbear We have updated it in #302 .
