### ISSUE TITLE
[bug]ToolServer和XAgentServer必须要在一个network下面吗？

### ISSUE THREAD

**Issue by youthbupt** [OpenBMB/XAgent#28]
XAgentWeb上一直登陆失败，显示
 ERROR  9:59:48 PM [vite] http proxy error at /login:                                                                              21:59:48
Error: connect ECONNREFUSED 127.0.0.1:8090
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) (x2)

agentserver正常：
[+] Running 1/0
 ✔ Container XAgent-Server  Created                                                                                                     0.0s 
Attaching to XAgent-Server
XAgent-Server  | INFO:     Uvicorn running on http://0.0.0.0:16204 (Press CTRL+C to quit)
XAgent-Server  | INFO:     Started parent process [1]
XAgent-Server  | INFO:     Started server process [8]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [15]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [13]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [9]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [12]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [10]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [11]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Started server process [14]
XAgent-Server  | INFO:     Waiting for application startup.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.
XAgent-Server  | INFO:     Application startup complete.

**Comment by sailaoda** [comment]
Thanks for your advice, it will work now.
