### ISSUE TITLE
运行报错：TypeError: Completions.create() got an unexpected keyword argument 'api_type'

### ISSUE THREAD

**Issue by zhaotaotao3276** [OpenBMB/XAgent#286]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
运行报错：TypeError: Completions.create() got an unexpected keyword argument 'api_type'
## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
docker compose up
![Uploading 1701397702700.png…]()
run.py
![1701397580897](https://github.com/OpenBMB/XAgent/assets/104298381/a3a2cae3-2b37-4ff8-9cb3-3d6bbbb1fbb5)
![1701397510420](https://github.com/OpenBMB/XAgent/assets/104298381/2e4428ad-7993-491e-ab47-ce1ffcc0d346)
![1701397598871](https://github.com/OpenBMB/XAgent/assets/104298381/5a3b9c8e-222d-435d-8698-f8c9cd2f84a5)

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
正常运行
## Environment / 环境信息
- Operating System / 操作系统：windows10，WSL2 ubuntu on windows
- Python Version / Python 版本：python3.12
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by glayyiyi** [comment]
看起来这个问题是由于config.yml里的配置造成的，请修改assetts/config.yml，去掉 api_type=xxxx这一行，然后再build后再重新尝试。

**Comment by zhaotaotao3276** [comment]
> 看起来这个问题是由于config.yml里的配置造成的，请修改assetts/config.yml，去掉 api_type=xxxx这一行，然后再build后再重新尝试。

这种方式我也尝试过，然后报错的参数会变成version，如果也去掉，那么会变成engine。如果都去掉，会404。

**Comment by glayyiyi** [comment]
> > 看起来这个问题是由于config.yml里的配置造成的，请修改assetts/config.yml，去掉 api_type=xxxx这一行，然后再build后再重新尝试。
> 
> 这种方式我也尝试过，然后报错的参数会变成version，如果也去掉，那么会变成engine。如果都去掉，会404。
我留意到你使用的是azure的API，请尝试按下面格式修改一下assetts/config.yml 再试下，注意把model去掉。
gpt-3.5-turbo-16k:
    - api_key: sk-xxxxx
      api_base: https://example.com
      api_type: azure
      api_version: 2023-07-01-preview
      engine: GPT-35-Turbo-16k

**Comment by sailaoda** [comment]
您好，已最新进行适配，您可以拉取最新代码采用您的原config进行使用。 具体可以参考 azure 参数或者 issue#303 的参数格式
