### ISSUE TITLE
outer loop无法显示

### ISSUE THREAD

**Issue by jfo888** [OpenBMB/XAgent#288]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
聊天界面无法输出内容，outer loop一直运行中
## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
![image](https://github.com/OpenBMB/XAgent/assets/120291659/2cc8af99-96aa-4963-a621-4ecf68a93f9a)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
请贴出相关的日志以及运行环境帮助我们定位问题。
