### ISSUE TITLE
项目代码不完整

### ISSUE THREAD

**Issue by siiia** [OpenBMB/XAgent#29]
一步步的改代码改到最后能成功跑起来，XAgentServer也能成功跑起来，然后又出现两个错：

- 使用数据库模式启动：给的mysql初始化创建表文件有字段缺失，初始化表后，查询报错
- 使用本地存储模式启动：部分接口方法未实现

感觉就是项目代码不完整

**Comment by thunlp-zp** [comment]
您好，数据库的部署脚本昨天已经更新了，请拉取最新的代码后重试，目前我们提供了mysql的部署脚本，其余数据库脚本可能需要根据语法需要进行适当修改；
至于本地存储模式下，我们并没有全量使用基类中的接口，只对本地存储环境中必要的接口进行了实现；
希望可以帮到您！
