### ISSUE TITLE
localhost 修改

### ISSUE THREAD

**Issue by av8dtop** [OpenBMB/XAgent#290]
## Issue Description / 问题描述
我想請問一下如果不使用localhost 正確的步驟修改以及build的方式該怎麼修，我是用docker-compose，但是是架設在另外一台上，還麻煩告知一下如果改相關的參數，謝謝

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
请参见[此处](https://xagent-doc.readthedocs.io/en/latest/source/XAgent/FAQ.html#how-to-provide-xagent-service-for-others-to-use-over-the-network).
