### ISSUE TITLE
使用XAgentGen运行遇到了 APIError:HTTP response code was 404

### ISSUE THREAD

**Issue by wangjiainchinatelecom** [OpenBMB/XAgent#298]
## Issue Description / 问题描述
使用XAgentGen运行XAgentLLaMa-34B-preview,然后使用openai的库调用时报错/v1/chat/completions not found

## Steps to Reproduce / 复现步骤
1.将xagentteam/xagentgen:latest中的app.py里的tensor_parallel_size参数值改成4
2.docker run -it -p 13520:13520  -v /huggingface/models/XAgentLLaMa-34B-preview/:/model:rw --gpus all --ipc=host xagentteam/xagentgen:1204 python app.py --model-path /model --port 13520
3.客户端使用openai的示例代码调用docker提供的服务
import openai
openai.api_key = "YOUR_API_KEY"
openai.api_base = "http://localhost:13520/v1"
chat_completion = openai.ChatCompletion.create(model="agentllama", messages=[{"role": "user", "content": "Hello world"}])
print(chat_completion)

## Expected Behavior / 预期行为
预期可以得到正常回复

## Environment / 环境信息
- Operating System / 操作系统：ubuntu22.04
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：docker

## Error Screenshots or Logs / 错误截图或日志
客户端报错
openai.error.APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)
服务端报错
![image](https://github.com/OpenBMB/XAgent/assets/19453231/846ee146-f401-4ef5-92e1-fb8a01d2b362)

**Comment by wangjiainchinatelecom** [comment]
将/v1去掉可以调用了,但是后端报错ValueError: Can't patch loop of type <class 'uvloop.Loop'>

**Comment by AL-377** [comment]
> tensor_parallel_size

目前XAgentGen仅支持tensor_parallel_size为1的设定，正在进行多卡支持开发，尽情期待！
