### ISSUE TITLE
max retries exceed with url:/v1/chat/completions(caused by sslError

### ISSUE THREAD

**Issue by momaek2023** [OpenBMB/XAgent#301]
## Issue Description / 问题描述
现阶段执行脚本遇到如下报错（api访问故障）
HTTPSConnectionPool(host:'api.openai.com',port:443):max retries exceed with url:/v1/chat/completions(caused by sslError(SSLError(1,'[SSL:WRONG_VERSION_NUMBER))) wrong version number(_ssl.c:992)

## Steps to Reproduce / 复现步骤
执行 python run.py --task "task2" --model "gpt-4"

## Expected Behavior / 预期行为
run脚本

## Environment / 环境信息
- Operating System / 操作系统：Linux
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![ssl截图](https://github.com/OpenBMB/XAgent/assets/151289865/c407bf87-98bf-4571-9720-793edf47480b)

**Comment by momaek2023** [comment]
无法访问openai的接口

**Comment by glayyiyi** [comment]
请先检查下部署和运行XAgent的这台机器是否可以访问openai的接口，测试方式直接命令行 curl https://api.openai.com/v1/chat/completions 看是否能够访问，如果不能，请尝试科学上网或Proxy的访问方式。

**Comment by momaek2023** [comment]
感谢回复，当前这个链接可curl通，且显示需要openai的key，请问是否有api_key的获取教程，让我尝试跑通demo呢。

**Comment by Umpire2018** [comment]
您好，请参照Openai或其他教程给出的获取key方法。
