### ISSUE TITLE
openai 访问不通，显示配额超限。

### ISSUE THREAD

**Issue by momaek2023** [OpenBMB/XAgent#306]
## Feature Description / 功能描述
Please describe the feature you would like to see added or improved. / 请描述您希望添加或改进的功能。
在填写api_key，删除organization后，使用gpt-3.5-turbo-16k进行预测，但显示配额超限。

## Goal / 目标
Explain the goal you hope to achieve with this feature. / 请说明您希望通过这个功能实现的目标。
脚本成功执行

## Expected Behavior / 预期行为
Describe the behavior you expect from this feature. / 请描述您期望的功能行为

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。
请问如何操作，才可以成功访问openai 的api呢，是否有相关的教程，能够支撑跑成功demo。

**Comment by momaek2023** [comment]
报错如下：
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
chatcompletition error : You exceeded your current quota, please check your plan and billing details.

**Comment by Umpire2018** [comment]
请首先在 Openai 方面查看您的限制与用量，参考Openai的帮助文档。
