### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443)

### ISSUE THREAD

**Issue by QZH-777** [OpenBMB/XAgent#310]
## Issue Description / 问题描述
<img width="905" alt="image" src="https://github.com/OpenBMB/XAgent/assets/67227342/2a8ab163-190a-4fd2-847e-6570ab0c02f9">

## Steps to Reproduce / 复现步骤
我在执行docker compose up的时候遇到这个问题。我在终端设置了代理，可以curl google.com。

## Environment / 环境信息
macOS

**Comment by Umpire2018** [comment]
目前只能建议您尝试不同的代理来改善网络环境，参考 [此处](https://www.google.com/search?q=openaipublic.blob.core.windows.net) ，其他项目如 AutoGPT 的用户也反馈遇到了同样的问题，但他们也并没有解决。同时，我在执行 `docker compose up` 时虽然也使用了全局代理，但并没有遇到这个问题。
