### ISSUE TITLE
assets中的config.yml能否添加非openai官方的key

### ISSUE THREAD

**Issue by itq5** [OpenBMB/XAgent#312]
## Issue Description / 问题描述
assets中的config.yml能否添加非openai官方的key,是否可以支持one api项目出来的sk,需要如何配置？

## Steps to Reproduce / 复现步骤
assets中的config.yml能否添加非openai官方的key,是否可以支持one api项目出来的sk,需要如何配置？

**Comment by Umpire2018** [comment]
<img width="370" alt="image" src="https://github.com/OpenBMB/XAgent/assets/138990495/c55e1985-d096-44a4-a209-0961f33c876c">

首先项目当前支持 azure 与 openai, 后者可为第三方镜像地址，需配置参数有 `model`, `api_base`.
