### ISSUE TITLE
希望增加代理选项，方便在本地部署

### ISSUE THREAD

**Issue by wyl2003** [OpenBMB/XAgent#315]
## Feature Description / 功能描述
Please describe the feature you would like to see added or improved. / 请描述您希望添加或改进的功能。
在配置文件内增加代理设置。

## Goal / 目标
Explain the goal you hope to achieve with this feature. / 请说明您希望通过这个功能实现的目标。
调用WebEnv_search_and_browse功能时，需要访问duckduckgo.com。本机部署后并不容易处理容器内的代理，希望可以在配置文件内增加代理选项。方便设置代理。

## Expected Behavior / 预期行为
Describe the behavior you expect from this feature. / 请描述您期望的功能行为。
本机部署时可以正常调用WebEnv_search_and_browse

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。
或者可以使用别的搜索模块代替duckduckgo_search

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by Umpire2018** [comment]
首先请您参考 [此处](https://xagent-doc.readthedocs.io/en/latest/source/XAgent/FAQ.html#i-got-connecttimeout-when-calling-webenv-search-and-browse-how-to-fix-it).
