### ISSUE TITLE
部署后，使用网页访问5173端口登录失败，XAgentServer中打印upstream:"http://127.0.0.1:8090/user/login"

### ISSUE THREAD

**Issue by itq5** [OpenBMB/XAgent#316]
## Issue Description / 问题描述
部署后，使用网页访问5173端口登录失败，XAgentServer中打印upstream:"http://127.0.0.1:8090/user/login"
XAgentServer中未启动8090监听

## Steps to Reproduce / 复现步骤
浏览器登录5173，登录时报错“Login failed”，F12获取http://xxxxx:5173/api/user/login 状态502 Bad Gateway

## Error Screenshots or Logs / 错误截图或日志

![image](https://github.com/OpenBMB/XAgent/assets/42521985/b140a01b-3f24-4ca1-a40c-a77ed622897a)
![image](https://github.com/OpenBMB/XAgent/assets/42521985/d8d2db78-a218-4e25-bd48-5edd8cbd81c0)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by itq5** [comment]
docker logs XAgentServer 会报如下错误：
![image](https://github.com/OpenBMB/XAgent/assets/42521985/fa22d06f-1719-493b-bac9-a47c998aa1ef)

**Comment by itq5** [comment]
mysql版本是8.2.0的，不清楚和mysql版本有没有关系

**Comment by Umpire2018** [comment]
快速解决方法：重启 `XAgent-Server` 容器。我们会尽快针对此问题进行修复。

**Comment by itq5** [comment]
> 快速解决方法：重启 `XAgent-Server` 容器。我们会尽快针对此问题进行修复。

重启后问题依旧存在

**Comment by Umpire2018** [comment]
好的，我们会在推送更新后通知您。
