### ISSUE TITLE
回答简单问题时一直重复，并且step中的内容一直为空

### ISSUE THREAD

**Issue by 605296722** [OpenBMB/XAgent#317]
## Issue Description / 问题描述
如题
![image](https://github.com/OpenBMB/XAgent/assets/43992350/610b807a-5224-490a-a936-2fcd3915fa49)

## Steps to Reproduce / 复现步骤
please write an ahk script which can messagebox "你好"

## Expected Behavior / 预期行为
输出一个非常简单脚本

## Environment / 环境信息
- Operating System / 操作系统：win11 x64
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
beautiful_goldberg          | INFO:     127.0.0.1:53038 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:53046 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:53054 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:53070 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56288 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56304 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56306 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56320 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56326 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56336 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56348 - "GET / HTTP/1.1" 200 OK
XAgent-Server               | Executing AI Function: summarize_action
XAgent-Server               |   chatcompletion: using gpt-3.5-turbo-16k
XAgent-Server               | Send data to 99f3e7322d0a40699b3f2f301e1213dd:   Send ede3342dc794442193856c7a278b6002data to client, length: 902.
XAgent-Server               | Action summarized in 118 tokens
beautiful_goldberg          | INFO:     127.0.0.1:56350 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:56358 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58750 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58756 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58760 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58764 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58776 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58788 - "GET / HTTP/1.1" 200 OK
xagent-ToolServerManager-1  | [2023-12-06 07:07:34 +0000] [8] [INFO] Request to node: http://172.18.0.9:31942/execute_tool
beautiful_goldberg          | INFO:     172.18.0.6:56792 - "POST /execute_tool HTTP/1.1" 200 OK
xagent-ToolServerManager-1  | [2023-12-06 07:07:34 +0000] [8] [INFO] Response from node: 200
beautiful_goldberg          | INFO:     127.0.0.1:58794 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58810 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58816 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:58822 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:49374 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:49388 - "GET / HTTP/1.1" 200 OK
beautiful_goldberg          | INFO:     127.0.0.1:49390 - "GET / HTTP/1.1" 200 OK
XAgent-Server               | Executing AI Function: actions_reflection
XAgent-Server               |   chatcompletion: using gpt-3.5-turbo-16k
XAgent-Server               | -=-=-=-=-=-=-=Recorder Start-=-=-=-=-=-=-=
XAgent-Server               |   Current: 1.1 Node: tool_server_pair 27
XAgent-Server               | -=-=-=-=-=-=-=Data -=-=-=-=-=-=-=
XAgent-Server               |   {
XAgent-Server               |     "url": "execute_tool",
XAgent-Server               |     "payload": {
XAgent-Server               |         "tool_name": "FileSystemEnv_print_filesys_struture",
XAgent-Server               |         "arguments": {
XAgent-Server               |             "return_root": true
XAgent-Server               |         }
XAgent-Server               |     },
XAgent-Server               |     "response_status_code": 200,
XAgent-Server               |     "tool_output": "Global Root Work Directory: /app/workspace/\n- /\n    - test.ahk\n    - script.ahk\n"
XAgent-Server               | }
XAgent-Server               | -=-=-=-=-=-=-=Recorder End-=-=-=-=-=-=-=
XAgent-Server               |   chatcompletion: using gpt-3.5-turbo-16k
xagent-ToolServerManager-1  | [2023-12-06 07:07:41 +0000] [7] [INFO] Request to node: http://172.18.0.9:31942/execute_tool
beautiful_goldberg          | INFO:     172.18.0.6:42332 - "POST /execute_tool HTTP/1.1" 200 OK
xagent-ToolServerManager-1  | [2023-12-06 07:07:41 +0000] [7] [INFO] Response from node: 200
xagent-ToolServerManager-1  | [2023-12-06 07:07:41 +0000] [7] [INFO] Request to node: http://172.18.0.9:31942/download_workspace
beautiful_goldberg          | INFO:     172.18.0.6:42336 - "POST /download_workspace HTTP/1.1" 200 OK
xagent-ToolServerManager-1  | [2023-12-06 07:07:41 +0000] [7] [INFO] Response from node: 200
XAgent-Server               | Warning: Detect tool call without reasoning
XAgent-Server               | NEXT ACTION:   COMMAND: FileSystemEnv_write_to_file
XAgent-Server               | ARGUMENTS:
XAgent-Server               | {'filepath': 'script.ahk', 'content': "; This AHK script displays a messagebox with the message '你好'\n\nMsgBox, 你好"}
XAgent-Server               | -=-=-=-=-=-=-=Recorder Start-=-=-=-=-=-=-=
XAgent-Server               |   Current: 1.1 Node: tool_server_pair 28
XAgent-Server               | -=-=-=-=-=-=-=Data -=-=-=-=-=-=-=
XAgent-Server               |   {
XAgent-Server               |     "url": "execute_tool",
XAgent-Server               |     "payload": {
XAgent-Server               |         "tool_name": "FileSystemEnv_write_to_file",
XAgent-Server               |         "arguments": {
XAgent-Server               |             "filepath": "script.ahk",
XAgent-Server               |             "content": "; This AHK script displays a messagebox with the message '你好'\n\nMsgBox, 你好"
XAgent-Server               |         }
XAgent-Server               |     },
XAgent-Server               |     "response_status_code": 200,
XAgent-Server               |     "tool_output": "    1: MsgBox, 你好\n    2: MsgBox, 你好\n    3: ExitApp\n    4: MsgBox, 你好\n    5: `/* This AHK script displays a messagebox with the message '你好' */\n    6: \n    7: MsgBox, 你好\n    8: MsgBox, 你好\n    9: MsgBox, 你好\n   10: MsgBox, 你好\n   11: MsgBox, 你好\n   12: ExitApp\n   13: MsgBox, 你好\n   14: MsgBox, 你好\n   15: MsgBox, 你好\n   16: MsgBox, 你好\n   17: ExitApp\n   18: ; This AHK script displays a messagebox with the message '你好'\n   19: \n   20: MsgBox, 你好\n"
XAgent-Server               | }
XAgent-Server               | -=-=-=-=-=-=-=Recorder End-=-=-=-=-=-=-=
XAgent-Server               | SYSTEM:   Command FileSystemEnv_write_to_file returned:     1: MsgBox, 你好
XAgent-Server               |     2: MsgBox, 你好
XAgent-Server               |     3: ExitApp
XAgent-Server               |     4: MsgBox, 你好
XAgent-Server               |     5: `/* This AHK script displays a messagebox with the message '你好' */
XAgent-Server               |     6:
XAgent-Server               |     7: MsgBox, 你好
XAgent-Server               |     8: MsgBox, 你好
XAgent-Server               |     9: MsgBox, 你好
XAgent-Server               |    10: MsgBox, 你好
XAgent-Server               |    11: MsgBox, 你好
XAgent-Server               |    12: ExitApp
XAgent-Server               |    13: MsgBox, 你好
XAgent-Server               |    14: MsgBox, 你好
XAgent-Server               |    15: MsgBox, 你好
XAgent-Server               |    16: MsgBox, 你好
XAgent-Server               |    17: ExitApp
XAgent-Server               |    18: ; This AHK script displays a messagebox with the message '你好'
XAgent-Server               |    19:
XAgent-Server               |    20: MsgBox, 你好
XAgent-Server               |
XAgent-Server               | TOOL STATUS CODE:   TOOL_CALL_SUCCESS
XAgent-Server               | -=-=-=-=-=-=-=Recorder Start-=-=-=-=-=-=-=
XAgent-Server               |   Current: 1.1 Node: tool_call 13
XAgent-Server               | -=-=-=-=-=-=-=Data -=-=-=-=-=-=-=
XAgent-Server               |   {
XAgent-Server               |     "tool_name": "FileSystemEnv_write_to_file",
XAgent-Server               |     "tool_input": {
XAgent-Server               |         "filepath": "script.ahk",
XAgent-Server               |         "content": "; This AHK script displays a messagebox with the message '你好'\n\nMsgBox, 你好"
XAgent-Server               |     },
XAgent-Server               |     "tool_output": "    1: MsgBox, 你好\n    2: MsgBox, 你好\n    3: ExitApp\n    4: MsgBox, 你好\n    5: `/* This AHK script displays a messagebox with the message '你好' */\n    6: \n    7: MsgBox, 你好\n    8: MsgBox, 你好\n    9: MsgBox, 你好\n   10: MsgBox, 你好\n   11: MsgBox, 你好\n   12: ExitApp\n   13: MsgBox, 你好\n   14: MsgBox, 你好\n   15: MsgBox, 你好\n   16: MsgBox, 你好\n   17: ExitApp\n   18: ; This AHK script displays a messagebox with the message '你好'\n   19: \n   20: MsgBox, 你好\n",
XAgent-Server               |     "tool_status_code": "TOOL_CALL_SUCCESS",
XAgent-Server               |     "thought": {
XAgent-Server               |         "thought": {
XAgent-Server               |             "properties": {}
XAgent-Server               |         },
XAgent-Server               |         "content": ""
XAgent-Server               |     }
XAgent-Server               | }
XAgent-Server               | -=-=-=-=-=-=-=Recorder End-=-=-=-=-=-=-=
XAgent-Server               | -=-=-=-=-=-=-= THOUGHTS, REASONING, PLAN AND CRITICISM WILL NOW BE VERIFIED BY AGENT -=-=-=-=-=-=-=

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by ChengFai** [comment]
您好，可以试试用命令行交互，看下是否依然重复
