### ISSUE TITLE
执行脚本，出现ssl异常，但curl openai的域名是可以curl通的

### ISSUE THREAD

**Issue by momaek2023** [OpenBMB/XAgent#318]
## Feature Description / 功能描述
Please describe the feature you would like to see added or improved. / 请描述您希望添加或改进的功能。
执行脚本，显示ssl error

## Goal / 目标
Explain the goal you hope to achieve with this feature. / 请说明您希望通过这个功能实现的目标。
脚本正常运行

## Expected Behavior / 预期行为
Describe the behavior you expect from this feature. / 请描述您期望的功能行为。

## Alternative Solutions / 其他解决方案
If you have considered any alternative solutions, please provide them here. / 如果您已经考虑了其他解决方案，请在此处提供。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

1. ssl问题报错
![ssl问题](https://github.com/OpenBMB/XAgent/assets/151289865/a6ceeab0-e674-4648-8916-011ab59a3c20)
2. curl curl https://api.openai.com/v1/chat/completions 可以访问通过
![curl通](https://github.com/OpenBMB/XAgent/assets/151289865/98e69fbe-a8e2-4664-ac8e-1ff3fc15a25a)

**Comment by Umpire2018** [comment]
请参考 [此处](https://github.com/OpenBMB/XAgent/issues/310#issuecomment-1841908495).
