### ISSUE TITLE
Seems backend service dependencies is not well managed

### ISSUE THREAD

**Issue by Jeffwan** [OpenBMB/XAgent#32]
backend service
```
XAgent-Server  | WARNING:  Unsupported upgrade request.
XAgent-Server  | WARNING:  No supported WebSocket library detected. Please use "pip install 'uvicorn[standard]'", or install 'websockets' or 'wsproto' manually.
XAgent-Server  |   pong broadcast for active connections: 0
```

![image](https://github.com/OpenBMB/XAgent/assets/4739316/6cc393a0-3314-4e80-a44c-7aed2341516c)

![image](https://github.com/OpenBMB/XAgent/assets/4739316/69b92eb9-c6cb-4a57-9c08-a5fd5ac39769)

**Comment by sailaoda** [comment]
Hello, run "pip install websockets" would solve it, and thanks for your notice, we just added it in the requirements.txt.

**Comment by YinSonglin1997** [comment]
> Hello, run "pip install websockets" would solve it, and thanks for your notice, we just added it in the requirements.txt.

I installed websockets, but this problem still occurs.

**Comment by YinSonglin1997** [comment]
我修改了[XAgent](https://github.com/OpenBMB/XAgent/tree/main)/[XAgentWeb](https://github.com/OpenBMB/XAgent/tree/main/XAgentWeb)/[src](https://github.com/OpenBMB/XAgent/tree/main/XAgentWeb/src)/[api](https://github.com/OpenBMB/XAgent/tree/main/XAgentWeb/src/api)
/backend.ts中const BACKEND_URL_LOCALDEPLOY = 'http://localhost:8090' 的localhost为服务器ip地址后upload成功。
