### ISSUE TITLE
执行脚本，ToolAgent使用网页搜索 https://duckduckgo.com 报错

### ISSUE THREAD

**Issue by momaek2023** [OpenBMB/XAgent#320]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
执行脚本，ToolAgent使用网页搜索报错（https://duckduckgo.com） 
TOOL STATUS CODE : TOOL_CALL_FAILED
https 访问报错，但是本地curl http是可以通过的，请问有什么解决办法

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
执行run脚本，选择gpt3.5的模型

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：linux
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
1. curl -v http://duckduckgo.com 可curl通

2. curl -v https://duckduckgo.com 报错
![不通过](https://github.com/OpenBMB/XAgent/assets/151289865/3081aa4d-acaf-416b-9b2f-a5896f7f860c)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

我在更换代理后，在浏览器工具调用时显示： httperror [Error99] can not assign requested address。（可以wget成功，但是curl不通）

**Comment by Umpire2018** [comment]
同时请您参考 [此处](https://xagent-doc.readthedocs.io/en/latest/source/XAgent/FAQ.html#i-got-connecttimeout-when-calling-webenv-search-and-browse-how-to-fix-it) 来使用 bing 替换 duckduckgo.

**Comment by momaek2023** [comment]
> 同时请您参考 [此处](https://xagent-doc.readthedocs.io/en/latest/source/XAgent/FAQ.html#i-got-connecttimeout-when-calling-webenv-search-and-browse-how-to-fix-it) 来使用 bing 替换 duckduckgo.

你好，请问有没有不需要密钥的浏览器设置呢

**Comment by Umpire2018** [comment]
可以了解下使用全局代理来改善网络环境。
