### ISSUE TITLE
Unknown model name gpt-4-1106-preview

### ISSUE THREAD

**Issue by QiTk** [OpenBMB/XAgent#323]
## Issue Description / 问题描述
 我在github上的codespace里面新建项目，通过终端能正常运行。但在本地运行就提示  无该模型
codespace 可以正常运行
![image](https://github.com/OpenBMB/XAgent/assets/25889714/d6ccb9b8-f87c-42fd-a55b-5503eac4ca56)

本地提示无该模型 
![image](https://github.com/OpenBMB/XAgent/assets/25889714/a06136b6-b811-4075-ab13-19531735f1ac)

**Comment by kcolemangt** [comment]
@QiTk gpt 4 turbo support is a new addition to xagent. The codespace probably works because it's using the new xagent. Update your local xagent and it should also work.
