### ISSUE TITLE
配置调用后显示api key无效

### ISSUE THREAD

**Issue by 2Red1Blue** [OpenBMB/XAgent#325]
在assets/config.yml下配置如下：(转发api)，添加了api_base,可以帮我看下哪里的配置不对吗
![20231208-115409](https://github.com/OpenBMB/XAgent/assets/73513320/26409c23-a98e-4729-8579-9fd6f1cf7af3)
运行后：
![image](https://github.com/OpenBMB/XAgent/assets/73513320/9b86e621-bc23-442a-9c89-b9d8f21a1a4a)
使用http测试api-key调用正常：
![image](https://github.com/OpenBMB/XAgent/assets/73513320/90636ac1-6b38-4171-8ceb-4882ee3d5027)

**Comment by sailaoda** [comment]
您好，看起来您第一个3.5-turbo的 key 配置不太对，既有 api version（azure openai key 的设置） 又是 openai 的 api type 类型，请按照您能正常使用的 http 的key设置进行配置，不需要多余的参数。

**Comment by Umpire2018** [comment]
> 您好，看起来您第一个3.5-turbo的 key 配置不太对，既有 api version（azure openai key 的设置） 又是 openai 的 api type 类型，请按照您能正常使用的 http 的key设置进行配置，不需要多余的参数。

@2Red1Blue 也就是第一个区域为 azure 专用设置，不应在这个区域进行设置。应在下方的区域设置，同时删除上方的区域。
