### ISSUE TITLE
Upload feature is not working

### ISSUE THREAD

**Issue by Jeffwan** [OpenBMB/XAgent#33]
Upload feature is not working at all

![image](https://github.com/OpenBMB/XAgent/assets/4739316/d5ea18c1-9091-40ce-a6c4-9d3df09974dc)

![image](https://github.com/OpenBMB/XAgent/assets/4739316/46e7078e-7842-4c29-8540-9ea3809eed64)

![image](https://github.com/OpenBMB/XAgent/assets/4739316/88b6b137-cf1d-49ff-84f5-43633e27691c)

**Comment by sailaoda** [comment]
Thanks for your advice, the upload feature has just been fixed.
