### ISSUE TITLE
请问可以将XAgentLlama在前端运行吗？

### ISSUE THREAD

**Issue by YinSonglin1997** [OpenBMB/XAgent#339]
## Issue Description / 问题描述
[https://github.com/OpenBMB/XAgent/blob/main/XAgentGen/README.md](url)能够在后端运行，如何在前端运行呢？有具体操作步骤或说明文档吗？

**Comment by Umpire2018** [comment]
当前 XAgentllama 不支持使用 Chat 前端，其设计目的仅为搭配 XAgent 进行使用。但同时欢迎你的贡献。
