### ISSUE TITLE
Start the servers using docker and process on a remote server

### ISSUE THREAD

**Issue by Jeffwan** [OpenBMB/XAgent#34]
Just a FYI. If you like to start the entire XAgent (tool, agent backend, agent frontend) in a remote machine and visit the UI service locally. You would need such changes. Otherwise, it won't work. I will try to make some configuration changes for users like me (laptop + remote dev machine)

![image](https://github.com/OpenBMB/XAgent/assets/4739316/a06eb39b-9870-4a0f-8e57-2f8711780ee9)

`34.216.99.75` is the IP of my remote dev machine

**Comment by zhpeng1996** [comment]
Please replace localhost in vue baseURL with your remote host IP. In this case, you need to ensure that port 8090 of your remote host is accessible. Another way is that if you use vscode to connect remotely for development, this situation will not exist.Hope this helps you.
