### ISSUE TITLE
终端运行失败

### ISSUE THREAD

**Issue by water2027** [OpenBMB/XAgent#341]
报错：Error in task_handler of 32945d8be3ef4d6399e070c68d37b966: 'str' object has no attribute 'model_dump'  

是我的api设置有问题吗？
api_keys:
  gpt-4:    
    - api_key: sk-xxx
      api_base: https://api.xxx
      model: gpt-4
  gpt-4-32k:
    - api_key: sk-xxx
      api_base: https://api.xxx
      model: gpt-4-32k

如果想用gpt-4-turbo的话该怎么设置？设置为gpt-4-1106-preview有相同的报错

**Comment by Umpire2018** [comment]
1. 请贴出完整的 log 。
2. 此 endpoint 是否可用？

**Comment by water2027** [comment]
问题解决了，换成openai的api成功运行。可能是中转api的问题，虽然感觉很奇怪。我在chatgpt-next-web上使用这个中转api是可以的，但是在xagent似乎不行。

**Comment by water2027** [comment]
问题解决了，换成openai的api成功运行。可能是中转api的问题，虽然感觉很奇怪。我在chatgpt-next-web上使用这个中转api是可以的，但是在xagent似乎不行。
