### ISSUE TITLE
xagent-ToolServerNode-1 | ERROR: Application startup failed. Exiting.

### ISSUE THREAD

**Issue by weinaike** [OpenBMB/XAgent#344]
[+] Running 6/0
 ✔ Container xagent-db-1                 Created                                                                                                                                                                           0.0s
 ✔ Container xagent-ToolServerManager-1  Created                                                                                                                                                                           0.0s
 ✔ Container xagent-xagent-redis-1       Created                                                                                                                                                                           0.0s
 ✔ Container xagent-xagent-mysql-1       Created                                                                                                                                                                           0.0s
 ✔ Container xagent-ToolServerNode-1     Created                                                                                                                                                                           0.0s
 ✔ Container XAgent-Server               Created                                                                                                                                                                           0.0s
Attaching to XAgent-Server, xagent-ToolServerManager-1, xagent-ToolServerNode-1, xagent-db-1, xagent-xagent-mysql-1, xagent-xagent-redis-1
xagent-xagent-redis-1       | 1:C 15 Dec 2023 06:20:14.287 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause faiures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1 for this to take effect.
xagent-xagent-redis-1       | 1:C 15 Dec 2023 06:20:14.287 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
xagent-xagent-redis-1       | 1:C 15 Dec 2023 06:20:14.287 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
xagent-xagent-redis-1       | 1:C 15 Dec 2023 06:20:14.287 * Configuration loaded
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.288 * monotonic clock: POSIX clock_gettime
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.288 * Running mode=standalone, port=6379.
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.288 * Server initialized
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * Loading RDB produced by version 7.2.3
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * RDB age 5 seconds
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * RDB memory usage when created 0.92 Mb
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * Done loading RDB, keys loaded: 1, keys expired: 0.
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * DB loaded from disk: 0.000 seconds
xagent-xagent-redis-1       | 1:M 15 Dec 2023 06:20:14.289 * Ready to accept connections tcp
xagent-xagent-mysql-1       | 2023-12-15 06:20:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
xagent-xagent-mysql-1       | 2023-12-15 06:20:14+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
xagent-xagent-mysql-1       | 2023-12-15 06:20:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.650+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"main","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVerson":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":21},"outgoing":{"minWireVersion":6,"maxWireVersion":21},"isInternalClient":true}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.650+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocol 'none'"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.650+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer,tcpFastOpenClient, and tcpFastOpenQueueSize."}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorSerice","namespace":"config.tenantMigrationDonors"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"main","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipienService","namespace":"config.tenantMigrationRecipients"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"main","msg":"Multi threading initialized"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"TENANT_M", "id":7091600, "ctx":"main","msg":"Starting TenantMigrationAccessBlockerRegistry"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architectre":"64-bit","host":"2c4585b443cb"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"7.0.4","gitVersion":"38f3e37057a4d2e9f41a39142681a76062d582e","openSSLVersion":"OpenSSL 3.0.2 15 Mar 2022","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2204","distarch":"x86_64","target_arch":"x86_64"}}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"22.04"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.652+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"securit":{"authorization":"enabled"}}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.653+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","strageEngine":"wiredTiger"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.653+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage ngine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:14.653+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=31480M,session_max=3300,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,remove=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time600,close_scan_interval=10,close_handle_minimum=2000),statistics_log=(wait=0),json_output=(error,message),verbose=[recovery_progress:1,checkpoint_progress:1,compact_progress:1,backup:0,checkpoint:0,compact:0,evict:0,historystore:0,recovery:0,rts:0,salvage:0,tiered:0,timestamp:0,transaction:0,verify:0,log:0],"}}
xagent-xagent-mysql-1       | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [1] [INFO] Starting gunicorn 21.2.0
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Booting worker with pid: 7
xagent-xagent-mysql-1       | 2023-12-15T06:20:14.885162Z 0 [System] [MY-015015] [Server] MySQL Server - start.
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.077825Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instea.
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.078811Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.2.0) starting as process 1
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.083752Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Booting worker with pid: 8
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.176922Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.334+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":681}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.334+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":,"i":0}}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.339+00:00"},"s":"W",  "c":"CONTROL",  "id":5123300, "ctx":"initandlisten","msg":"vm.max_map_count is too low","attr":{"currentValue":65530,"recommendedMinimum:1677720,"maxConns":838860},"tags":["startupWarnings"]}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.342+00:00"},"s":"I",  "c":"NETWORK",  "id":4915702, "ctx":"initandlisten","msg":"Updated wire specification","attr":{"oldSpec":{"incomingExternalClient":{"minireVersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":21},"outgoing":{"minWireVersion":6,"maxWireVersion":21},"isInternalClient":true},"newSpec":{"incomingExternalClient":{"minWireersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":21,"maxWireVersion":21},"outgoing":{"minWireVersion":21,"maxWireVersion":21},"isInternalClient":true}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.342+00:00"},"s":"I",  "c":"REPL",     "id":5853300, "ctx":"initandlisten","msg":"current featureCompatibilityVersion value","attr":{"featureCompatibilityVersin":"7.0","context":"startup"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.342+00:00"},"s":"I",  "c":"STORAGE",  "id":5071100, "ctx":"initandlisten","msg":"Clearing temp directory"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.344+00:00"},"s":"I",  "c":"CONTROL",  "id":6608200, "ctx":"initandlisten","msg":"Initializing cluster server parameters from disk"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.344+00:00"},"s":"I",  "c":"CONTROL",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.345+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/dat/db/diagnostic.data"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.347+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisable","oldState":"ConfigPreStart"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.348+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.353+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.353+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.353+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.384241Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.384262Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.385379Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a diferent directory.
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.398385Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
xagent-xagent-mysql-1       | 2023-12-15T06:20:15.398405Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.2.0'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server  GPL.
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Database connected
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Docker client connected
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Started server process [7]
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Waiting for application startup.
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.694+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40674","uuid":{"uuid":{"$uuid":"4495ad2-ea68-4718-894d-b60a5656c16f"}},"connectionId":1,"connectionCount":1}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.694+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.18.0.6:40674","client":"conn1","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.696+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40680","uuid":{"uuid":{"$uuid":"99131d8-6af3-4dd2-a87b-6df684c2abc4"}},"connectionId":2,"connectionCount":2}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.696+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40676","uuid":{"uuid":{"$uuid":"deef765-be77-4790-ba9c-9cfd89d3a43d"}},"connectionId":3,"connectionCount":3}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.697+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.18.0.6:40680","client":"conn2","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.697+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"172.18.0.6:40676","client":"conn3","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.701+00:00"},"s":"I",  "c":"ACCESS",   "id":6788604, "ctx":"conn2","msg":"Auth metrics report","attr":{"metric":"acquireUser","micros":0}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.724+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn2","msg":"Successfully authenticated","attr":{"client":"172.18.0.6:40680","isSpeculative":true,isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"admin","db":"admin","result":0,"metrics":{"conversation_duration":{"micros":23444,"summary":{"0":{"step":1,"step_total":2,"duration_micros":101},"1":{"step":2,"steptotal":2,"duration_micros":42}}}},"extraInfo":{}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.725+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn2","msg":"Received first command on ingress connection since session start or auth handshake","ttr":{"elapsedMillis":0}}
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Database connected
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Docker client connected
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Nodes status checker started.
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [7] [INFO] Application startup complete.
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Started server process [8]
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Waiting for application startup.
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.800+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40686","uuid":{"uuid":{"$uuid":"d42542e-b296-41af-9dbc-0b270f43c941"}},"connectionId":4,"connectionCount":4}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.800+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"172.18.0.6:40686","client":"conn4","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.802+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40698","uuid":{"uuid":{"$uuid":"f3522e3-ef5c-4dc5-bac8-cefd97eb3ddb"}},"connectionId":5,"connectionCount":5}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.802+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"172.18.0.6:40698","client":"conn5","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.802+00:00"},"s":"I",  "c":"ACCESS",   "id":6788604, "ctx":"conn5","msg":"Auth metrics report","attr":{"metric":"acquireUser","micros":0}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.802+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.6:40702","uuid":{"uuid":{"$uuid":"bbfb0ad-af4a-4e44-9f7d-a7efc5db4d7d"}},"connectionId":6,"connectionCount":6}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.803+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"172.18.0.6:40702","client":"conn6","doc":{"driver"{"name":"PyMongo|Motor","version":"4.6.1|3.3.2"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.15.0-88-generic"},"platform":"CPython 3.10.13.final.0|asyncio"}}}
xagent-ToolServerNode-1     | INFO:     Started server process [1]
xagent-ToolServerNode-1     | INFO:     Waiting for application startup.
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.811+00:00"},"s":"I",  "c":"ACCESS",   "id":5286306, "ctx":"conn5","msg":"Successfully authenticated","attr":{"client":"172.18.0.6:40698","isSpeculative":true,isClusterMember":false,"mechanism":"SCRAM-SHA-256","user":"admin","db":"admin","result":0,"metrics":{"conversation_duration":{"micros":8596,"summary":{"0":{"step":1,"step_total":2,"duration_micros":105},"1":{"step":2,"step_otal":2,"duration_micros":69}}}},"extraInfo":{}}}
xagent-db-1                 | {"t":{"$date":"2023-12-15T06:20:15.811+00:00"},"s":"I",  "c":"NETWORK",  "id":6788700, "ctx":"conn5","msg":"Received first command on ingress connection since session start or auth handshake","ttr":{"elapsedMillis":0}}
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Nodes status checker started.
xagent-ToolServerManager-1  | [2023-12-15 06:20:15 +0000] [8] [INFO] Application startup complete.
xagent-ToolServerNode-1     | Starting Docker: docker.
xagent-ToolServerNode-1     | INFO:     Register env PythonNotebook with 2 tools!
xagent-ToolServerNode-1     | WARNING:  Bing API key is not provided, rollback to duckduckgo.
xagent-ToolServerNode-1     | ERROR:    Traceback (most recent call last):
xagent-ToolServerNode-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
xagent-ToolServerNode-1     |     async with self.lifespan_context(app) as maybe_state:
xagent-ToolServerNode-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
xagent-ToolServerNode-1     |     await self._router.startup()
xagent-ToolServerNode-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in startup
xagent-ToolServerNode-1     |     handler()
xagent-ToolServerNode-1     |   File "/app/main.py", line 32, in startup
xagent-ToolServerNode-1     |     app.tool_register = ToolRegister()
xagent-ToolServerNode-1     |   File "/app/core/register/register.py", line 54, in __init__
xagent-ToolServerNode-1     |     self.check_and_register(attr)
xagent-ToolServerNode-1     |   File "/app/core/register/register.py", line 80, in check_and_register
xagent-ToolServerNode-1     |     env = attr(config=self.config.dict())
xagent-ToolServerNode-1     |   File "/app/core/envs/web.py", line 25, in __init__
xagent-ToolServerNode-1     |     self.client = httpx.AsyncClient(headers=self.headers,verify=False,timeout=30.0,http2=True)
xagent-ToolServerNode-1     |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1389, in __init__
xagent-ToolServerNode-1     |     raise ImportError(
xagent-ToolServerNode-1     | ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.
xagent-ToolServerNode-1     |
xagent-ToolServerNode-1     | ERROR:    Application startup failed. Exiting.
xagent-ToolServerNode-1 exited with code 3
XAgent-Server               | INFO:     Will watch for changes in these directories: ['/app']
XAgent-Server               | INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
XAgent-Server               | INFO:     Started reloader process [1] using StatReload
XAgent-Server               | INFO:     Started server process [33]
XAgent-Server               | INFO:     Waiting for application startup.
XAgent-Server               | INFO:     Application startup complete.

最新的代码， 执行以下两步
1. sudo docker compose build 
2. sudo docker compose up
出现
xagent-ToolServerNode-1     | ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.
xagent-ToolServerNode-1     |
xagent-ToolServerNode-1     | ERROR:    Application startup failed. Exiting.
xagent-ToolServerNode-1 exited with code 3
这个是什么问题

**Comment by ttran1904** [comment]
Need to make sure httpx[http2] is installed in the docker build, not just the local computer.

Go to these files and fix `httpx` into` httpx[http2]` to these files:

1. ToolServer > ToolServerManager > requirements.txt: `httpx[http2]`
2. ToolServer > ToolServerNOde > requirements.txt: `httpx[http2]`
Then just run `docker compose build` to build a new image with http with h2 component in it.

**Comment by sailaoda** [comment]
> Need to make sure httpx[http2] is installed in the docker build, not just the local computer.
> 
> Go to these files and change `httpx` to` httpx[http2]` to these files:
> 
> 1. ToolServer > ToolServerManager > requirements.txt: `httpx[http2]`
> 2. ToolServer > ToolServerNOde > requirements.txt: `httpx[http2]`
>    Then just run `docker compose build` to build a new image with http with h2 component in it.

Yes, doing so will fix the internal issues with this ToolServerNode
