### ISSUE TITLE
增加LLM扩展接口

### ISSUE THREAD

**Issue by mrb957600057** [OpenBMB/XAgent#349]
## Feature Description / 功能描述
支持自定义LLM接入，不仅限于是gpt-4系列

## Goal / 目标
有统一接口，自定义，在配置中切换

**Comment by Umpire2018** [comment]
当前我们认为GPT4以外的模型并不能满足 XAgent 的要求，所以目前暂时未进行适配。同时，可查看 [XAgentllama](https://github.com/OpenBMB/XAgent/tree/main/XAgentGen#-introduction-of-xagentgen) 获取本地化部署信息。
