### ISSUE TITLE
docker 镜像报错

### ISSUE THREAD

**Issue by ZSCDumin** [OpenBMB/XAgent#35]
415.4 E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openjdk-17/openjdk-17-jdk-headless_17.0.8%2b7-1%7edeb12u1_amd64.deb  Connection failed [IP: 146.75.114.132 80]
415.4 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
415.4 Fetched 128 MB in 6min 45s (315 kB/s)
------
failed to solve: process "/bin/sh -c apt update && apt install -y build-essential make openjdk-17-jdk-headless curl docker.io docker-compose psmisc sudo" did not complete successfully: exit code: 100

mac book pro, Docker version 24.0.6, Docker Compose version v2.22.0-desktop.2

**Comment by tom832** [comment]
same issue with linux

**Comment by luyaxi** [comment]
please check your network connection

**Comment by ZSCDumin** [comment]
> please check your network connection

是镜像源的问题吗？有没有什么解法，试了几次都不行

**Comment by luyaxi** [comment]
可以在`ToolServer/dockerfiles/ToolServer*/Dockerfile`中在apt执行前添加换源命令以避免网络问题，例如添加以下内容在 `RUN apt update *`之前（未验证正确性）：
```bash
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
```
请参阅互联网资料获得详细信息
