### ISSUE TITLE
本地离线环境运行XAgent，403 Client Error: Forbidden for url: http://172.18.52.54:8080/get_available_tools

### ISSUE THREAD

**Issue by liyoung1992** [OpenBMB/XAgent#359]
```

XAgent-Server        | INFO:     ('172.18.44.28', 42668) - "WebSocket /ws/base/6c0d1dadefc34305996734fa8dd5c750?user_id=guest&token=xagent&description=1+1=?" [accepted]
XAgent-Server        | INFO:     connection open
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:07 +0000] [8] [INFO] Node created: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:07 +0000] [8] [INFO] Node created 222222: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [7] [INFO] Node da5d19f00551 status updated: running -> exited
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [7] [INFO] Node da5d19f00551 health updated: starting -> unhealthy
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [8] [INFO] Node da5d19f00551 status updated: running -> exited
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [8] [INFO] Node da5d19f00551 health updated: starting -> unhealthy
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:37 +0000] [8] [WARNING] Node status detection timeout: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
XAgent-Server        | Exception in thread Thread-1 (task_handler):
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgent/toolserver_interface.py", line 195, in get_available_tools
XAgent-Server        |     response.raise_for_status()
XAgent-Server        |   File "/python/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
XAgent-Server        |     raise HTTPError(http_error_msg, response=self)
XAgent-Server        | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://toolservermanager:8080/get_available_tools
XAgent-Server        | 
XAgent-Server        | During handling of the above exception, another exception occurred:
XAgent-Server        | 
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgentServer/server.py", line 53, in interact
XAgent-Server        |     xagent_core.build(xagent_param, interaction=interaction)
XAgent-Server        |   File "/app/XAgent/core.py", line 209, in build
XAgent-Server        |     subtask_functions, self.tool_functions_description_list = self.function_handler.get_functions(
XAgent-Server        |   File "/app/XAgent/function_handler.py", line 128, in get_functions
XAgent-Server        |     output = self.toolserver_interface.get_available_tools()
XAgent-Server        |   File "/app/XAgent/toolserver_interface.py", line 206, in get_available_tools
XAgent-Server        |     raise Exception(f"Error when fetching available tools: {e}")
XAgent-Server        | Exception: Error when fetching available tools: 403 Client Error: Forbidden for url: http://toolservermanager:8080/get_available_tools
XAgent-Server        | 
XAgent-Server        | The above exception was the direct cause of the following exception:
XAgent-Server        | 
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgentServer/server.py", line 106, in interact
XAgent-Server        |     raise XAgentRunningError(str(e)) from e
XAgent-Server        | XAgentServer.exts.exception_ext.XAgentRunningError: Error when fetching available tools: 403 Client Error: Forbidden for url: http://toolservermanager:8080/get_available_tools
XAgent-Server        | 
XAgent-Server        | During handling of the above exception, another exception occurred:
XAgent-Server        | 
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/python/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
XAgent-Server        |     self.run()
XAgent-Server        |   File "/python/lib/python3.10/threading.py", line 946, in run
XAgent-Server        |     self._target(*self._args, **self._kwargs)
XAgent-Server        |   File "/app/XAgentServer/application/websockets/base.py", line 324, in task_handler
XAgent-Server        |     server.interact(interaction=interaction)
XAgent-Server        |   File "/app/XAgentServer/server.py", line 109, in interact
XAgent-Server        |     xagent_core.close()
XAgent-Server        |   File "/app/XAgent/core.py", line 223, in close
XAgent-Server        |     self.toolserver_interface.download_all_files()
XAgent-Server        |   File "/app/XAgent/toolserver_interface.py", line 166, in download_all_files
XAgent-Server        |     response.raise_for_status()
XAgent-Server        |   File "/python/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
XAgent-Server        |     raise HTTPError(http_error_msg, response=self)
XAgent-Server        | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://toolservermanager:8080/download_workspace


```

**Comment by liyoung1992** [comment]
添加报错日志：
XAgent-Server        | INFO:     127.0.0.1:33450 - "POST /conv/init_conv_env HTTP/1.0" 200 OK
XAgent-Server        | INFO:     ('172.18.44.28', 42668) - "WebSocket /ws/base/6c0d1dadefc34305996734fa8dd5c750?user_id=guest&token=xagent&description=1+1=?" [accepted]
XAgent-Server        | INFO:     connection open
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:07 +0000] [8] [INFO] Node created: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:07 +0000] [8] [INFO] Node created 222222: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [7] [INFO] Node da5d19f00551 status updated: running -> exited
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [7] [INFO] Node da5d19f00551 health updated: starting -> unhealthy
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [8] [INFO] Node da5d19f00551 status updated: running -> exited
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:08 +0000] [8] [INFO] Node da5d19f00551 health updated: starting -> unhealthy
ToolServerManager_1_570b33bd4700 | [2023-12-26 10:16:37 +0000] [8] [WARNING] Node status detection timeout: da5d19f00551349225521a007bcb97d509a840f9d8a49a42c9ef8b3c7ee37205
XAgent-Server        | Exception in thread Thread-1 (task_handler):
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgent/toolserver_interface.py", line 195, in get_available_tools
XAgent-Server        |     response.raise_for_status()
XAgent-Server        |   File "/python/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
XAgent-Server        |     raise HTTPError(http_error_msg, response=self)
XAgent-Server        | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://toolservermanager:8080/get_available_tools
Docker ps：
CONTAINER ID   IMAGE                                            COMMAND                  CREATED             STATUS                    PORTS                                                                                  NAMES
d2aac47914e1   xagentteam/xagent-server:latest                  "python start_server…"   16 minutes ago      Up 16 minutes             0.0.0.0:5173->5173/tcp, :::5173->5173/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   XAgent-Server
2225b4f8bb2f   xagentteam/toolserver-manager:latest             "gunicorn main:app -…"   51 minutes ago      Up 16 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              xagent-main_ToolServerManager_1_570b33bd4700
b42eac2d63e5   xagentteam/toolserver-node:latest                "uvicorn main:app --…"   About an hour ago   Up 16 minutes             31942/tcp                                                                              xagent-main_ToolServerNode_1_714f6f4ece12
bb7488c9e48e   172.18.30.144:8083/xagentteam/xagentgen:latest   "/opt/nvidia/nvidia_…"   9 hours ago         Up 9 hours                0.0.0.0:13520->13520/tcp, :::13520->13520/tcp                                          funny_galileo
299d0f749957   172.18.30.144:8083/redis                         "docker-entrypoint.s…"   24 hours ago        Up 16 minutes (healthy)   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                              xagent-main_xagent-redis_1_34d4b5f0821e
1d04927a58c9   172.18.30.144:8083/mongo                         "docker-entrypoint.s…"   24 hours ago        Up 16 minutes             27017/tcp                                                                              xagent-main_db_1_7f8d1c958f42
7c8cdaa3bbc5   172.18.30.144:8083/mysql                         "docker-entrypoint.s…"   24 hours ago        Up 16 minutes (healthy)   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                   xagent-main_xagent-mysql_1_1b7208bebf92
进入docker内部执行：
docker exec -it 2225b4f8bb2f /bin/bash
root@2225b4f8bb2f:/app# curl   http://toolservermanager:8080/alive
"alive"
root@2225b4f8bb2f:/app#

**Comment by liyoung1992** [comment]
最新进展，toolserver创建了一个node，为啥node看不到，这个172.21.0.9应该就是新的node节点：
**```
ToolServerManager_1_58489b52730d | [2023-12-27 02:08:52 +0000] [7] [INFO] Node created: 5f3762cfc1bc400c045d3dde9a67d338821e24456f2b82e16e0eadc82cf64536
ToolServerManager_1_58489b52730d | [2023-12-27 02:08:52 +0000] [7] [INFO] Request to node: http://172.21.0.9:31942/get_available_tools
```**

**Comment by allen781105** [comment]
绕过本地运行可能遇到的端口和docker compose问题，直接从codespace上映射，然后在本地debug的配置过程：
[XAgent在本地以命令行方式Debug的配置过程.pdf](https://github.com/OpenBMB/XAgent/files/13776530/XAgent.Debug.pdf)

**Comment by liyoung1992** [comment]
感谢，我的试验场景可能和这个稍微有点不同。我在尝试把XAgent在完全离线的环境部署，去除openai、bing、rapidapi等依赖，结合toolbench运行自定义的api和工具。

**Comment by allen781105** [comment]
可能是容器化的方式，导致项目要剥离成本地化的环境部署比较困难；
我只是在尝试能在本地对项目进行debug，也遇到不少问题；
然后只能尝试这种方式，虽然可以进行debug，但是在debug过程中也还是会报错；

**Comment by liyoung1992** [comment]
@allen781105 是的~，容器化部署方便，但是遇到问题调试起来比较麻烦。

**Comment by liyoung1992** [comment]
搞定了，docker配置问题。关闭

**Comment by TangSB** [comment]
@liyoung1992  搞定了，docker配置问题 ，遇到同样 请问是怎么解决的修改了哪里的配置
