### ISSUE TITLE
命令行运行XAgent，报错redis.exceptions.AuthenticationError

### ISSUE THREAD

**Issue by hurun** [OpenBMB/XAgent#365]
## Issue Description / 问题描述
按照文档步骤流程，命令行运行XAgent，报错redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set

## Steps to Reproduce / 复现步骤
1. python run.py --task "calculate 7+8="  --config-file "assets/gpt-3.5-turbo_config.yml"
2. gpt-3.5-turbo_config.yml配置如下
  ```bash
     api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-xxxx(测试可直接调用)
      model: gpt-3.5-turbo-16k
```

## Expected Behavior / 预期行为
正常执行输出结果

## Environment / 环境信息
- Operating System / 操作系统：windows 10
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
![微信截图_20231229161128](https://github.com/OpenBMB/XAgent/assets/25788042/349b7f98-3623-43a7-b473-95638dc19426)

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by hurun** [comment]
排查测试问题出在dockers redis，运行的redis容器有设置xagent密码，但在python中使用密码连接redis 容器出现问题所述的报错。
解决方法，找到如下代码第17行，删除password=XAgentServerEnv.Redis.redis_password
XAgentServer/exts/redis_ext.py

**Comment by ShiFangJuMie** [comment]
> 排查测试问题出在dockers redis，运行的redis容器有设置xagent密码，但在python中使用密码连接redis 容器出现问题所述的报错。 解决方法，找到如下代码第17行，删除password=XAgentServerEnv.Redis.redis_password XAgentServer/exts/redis_ext.py

可以通过环境变量或配置文件，指定redis的密码是什么吗？
已经运行了一个redis实例，再运行一个也是浪费
