### ISSUE TITLE
[question]这个web UI的一直提示端口8080没有开启？

### ISSUE THREAD

**Issue by shalimujiang** [OpenBMB/XAgent#39]
【1】
XAgent-Server  |   "default_completion_kwargs": {
XAgent-Server  |     "model": "gpt-3.5-turbo-16k",
XAgent-Server  |     "temperature": 0.5,
XAgent-Server  |     "request_timeout": 60
XAgent-Server  |   },
XAgent-Server  |   "enable_summary": true,
XAgent-Server  |   "summary": {
XAgent-Server  |     "single_action_max_length": 8192,
XAgent-Server  |     "max_return_length": 18432
XAgent-Server  |   },
XAgent-Server  |   "use_selfhost_toolserver": true,
XAgent-Server  |   "selfhost_toolserver_url": "http://localhost:8080",
XAgent-Server  |   "max_retry_times": 3,
XAgent-Server  |   "max_subtask_chain_length": 20,
XAgent-Server  |   "max_plan_refine_chain_length": 3,
XAgent-Server  |   "max_plan_tree_depth": 3,
XAgent-Server  |   "max_plan_tree_width": 5,
XAgent-Server  |   "max_plan_length": 8192,
XAgent-Server  |   "rapidapi_retrieve_tool_count": 0,
XAgent-Server  |   "enable_ask_human_for_help": false
XAgent-Server  | }
XAgent-Server  | Human-In-The-Loop  False
XAgent-Server  | ERROR:    Exception in ASGI application
XAgent-Server  | Traceback (most recent call last):
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
XAgent-Server  |     sock = connection.create_connection(
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
XAgent-Server  |     raise err
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
XAgent-Server  |     sock.connect(sa)
XAgent-Server  | ConnectionRefusedError: [Errno 111] Connection refused
XAgent-Server  |
XAgent-Server  | The above exception was the direct cause of the following exception:
XAgent-Server  |
XAgent-Server  | Traceback (most recent call last):
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
XAgent-Server  |     response = self._make_request(
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
XAgent-Server  |     conn.request(
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
XAgent-Server  |     self.endheaders()
XAgent-Server  |   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
XAgent-Server  |     self._send_output(message_body, encode_chunked=encode_chunked)
XAgent-Server  |   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
XAgent-Server  |     self.send(msg)
XAgent-Server  |   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
XAgent-Server  |     self.connect()
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
XAgent-Server  |     self.sock = self._new_conn()
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
XAgent-Server  |     raise NewConnectionError(
XAgent-Server  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f859c02b580>: Failed to establish a new connection: [Errno 111] Connection refused
XAgent-Server  |
XAgent-Server  | The above exception was the direct cause of the following exception:
XAgent-Server  |
XAgent-Server  | Traceback (most recent call last):
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
XAgent-Server  |     resp = conn.urlopen(
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
XAgent-Server  |     retries = retries.increment(
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
XAgent-Server  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
XAgent-Server  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f859c02b580>: Failed to establish a new connection: [Errno 111] Connection refused'))
XAgent-Server  |
XAgent-Server  | During handling of the above exception, another exception occurred:
XAgent-Server  |
XAgent-Server  | Traceback (most recent call last):
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
XAgent-Server  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
XAgent-Server  |     return await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
XAgent-Server  |     await super().__call__(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
XAgent-Server  |     await self.middleware_stack(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
XAgent-Server  |     await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
XAgent-Server  |     await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 26, in __call__
XAgent-Server  |     await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
XAgent-Server  |     raise exc
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
XAgent-Server  |     await self.app(scope, receive, sender)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
XAgent-Server  |     raise e
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
XAgent-Server  |     await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
XAgent-Server  |     await route.handle(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
XAgent-Server  |     await self.app(scope, receive, send)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 88, in dispatch
XAgent-Server  |     raise exc
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 80, in dispatch
XAgent-Server  |     await self.on_receive(websocket, data)
XAgent-Server  |   File "/app/app.py", line 628, in on_receive
XAgent-Server  |     await asyncio.create_task(self.do_running_long_task(parameter))
XAgent-Server  |   File "/app/app.py", line 688, in do_running_long_task
XAgent-Server  |     await task
XAgent-Server  |   File "/app/XAgentServer/server.py", line 64, in interact
XAgent-Server  |     toolserver_interface.lazy_init(config=config)
XAgent-Server  |   File "/app/XAgent/tool_call_handle.py", line 63, in lazy_init
XAgent-Server  |     response = requests.post(f'{self.url}/get_cookie',)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
XAgent-Server  |     return request("post", url, data=data, json=json, **kwargs)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
XAgent-Server  |     return session.request(method=method, url=url, **kwargs)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
XAgent-Server  |     resp = self.send(prep, **send_kwargs)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
XAgent-Server  |     r = adapter.send(request, **kwargs)
XAgent-Server  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
XAgent-Server  |     raise ConnectionError(e, request=request)
XAgent-Server  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f859c02b580>: Failed to establish a new connection: [Errno 111] Connection refused'))
XAgent-Server  | INFO:     connection closed
【2】
![image](https://github.com/OpenBMB/XAgent/assets/75249643/ac0a9de7-f756-4f6c-92e9-e4adb2f4fd93)
【3】
What part of the code should I fix?

**Comment by sailaoda** [comment]
Hello, please make sure that the ToolServer docker is running. If the ToolServer docker is not running,it will happen like this.

**Comment by ChengFai** [comment]
您好，您能进入XAgentWeb npm run dev 进入图形界面吗

**Comment by shalimujiang** [comment]
> 您好，您能进入XAgentWeb npm run dev 进入图形界面吗您好，您可以进入XAgentWeb npm run dev 进入图形界面吗

可以进入，登录页面如下图所示：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/33513365-065f-47aa-bc86-1ac909512dea)
XAgentServer登录后->后端情况如下图所示：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/e48f2581-08e6-4117-9d49-45c8938e93fe)
XAgentWeb登录如下图所示：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/18ebb452-97f7-4a80-8ee2-dcff63b3dd31)
ToolServer登录如下图所示：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/faf6fdb3-65ee-4ded-8833-9f86a8145b6e)

但是，选择了选项和输入以后就会出现改问题：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/40fabd70-fd8b-4713-b72d-0d1fe001cbf2)
![image](https://github.com/OpenBMB/XAgent/assets/75249643/7c4179d8-06cf-48ff-8685-0fdc3cbd1446)
![image](https://github.com/OpenBMB/XAgent/assets/75249643/5e7ef9b5-7e98-4165-ad49-48a7fff48c39)
![image](https://github.com/OpenBMB/XAgent/assets/75249643/abe80a97-c506-4d56-a8f0-5d9655fdcee7)

**Comment by luyaxi** [comment]
请尝试以裸机模式运行XAgentServer，该部分代码正在紧急修正

**Comment by shalimujiang** [comment]
> 请尝试以裸机模式运行XAgentServer，该部分代码正在紧急修正

好的好的，我以为是我的问题，等你们，辛苦了！

**Comment by luyaxi** [comment]
感谢支持！
