### ISSUE TITLE
Excessive reflection leading to crazy high token expenditura

### ISSUE THREAD

**Issue by pedrocacintra** [OpenBMB/XAgent#42]
For some reason it is spending crazy a lot of resources on the this reflection thing and burning money:

-=-=-=-=-=-=-= THOUGHTS, REASONING, PLAN AND CRITICISM WILL NOW BE VERIFIED BY AGENT -=-=-=-=-=-=-= 
Executing AI Function: summarize_action 
using gpt-4
Action summarized in 131 tokens 
Executing AI Function: actions_reflection 
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
None
THOUGHTS:  After correcting the IndentationError in the Flask server script, it is crucial to re-run the script to verify that the error has indeed been rectified and the application works as expected.
REASONING:  Performing this action is essential to ensure the health of the application. By running the application, we can confirm that the previous issues have been resolved and that the application can perform its intended functionalities. This action also allows for the identification of any other potential errors that may have been overlooked previously.
PLAN:
-  Test the project again to verify that it works as expected after rectifying the indentation error.
CRITICISM:  While this action is necessary, there is a potential risk that other unforeseen errors may still exist in the Flask server script, especially considering the complexity of the Gradio interface integration. It is therefore recommended to thoroughly review the code for possible errors after running the script.
NEXT ACTION:  COMMAND: shell_command_executor ARGUMENTS: {'command': 'python app/server.py', 'run_async': True}
SYSTEM:  Command shell_command_executor returned: {'shell_id': 2, 'display': '\nstderr:\n File "/app/workspace/app/server.py", line 26\n iface = gr.Interface(fn=image_upload_predict, inputs=\'imagebox\', outputs=\'image\')\n ^\nIndentationError: expected an indented block after \'if\' statement on line 25\n', 'status': 'shell still running, no return code'}
TOOL STATUS CODE:  TOOL_CALL_SUCCESS
-=-=-=-=-=-=-= THOUGHTS, REASONING, PLAN AND CRITICISM WILL NOW BE VERIFIED BY AGENT -=-=-=-=-=-=-= 
Executing AI Function: summarize_action 
using gpt-4
Action summarized in 179 tokens 
Executing AI Function: actions_reflection 
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
max context length reached, retrying with gpt-4-32k
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
max context length reached, retrying with gpt-4-32k
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4
using gpt-4

**Comment by luyaxi** [comment]
It's seems like to occur due to request error due to maximum context error, we will fix this soon

**Comment by luyaxi** [comment]
It seems that it retries request due to network error or context error, please submit your running_records to xagentteam@gmail.com. We will solve this
