### ISSUE TITLE
Cannot access the web UI

### ISSUE THREAD

**Issue by yinfangchen** [OpenBMB/XAgent#45]
I use docker to start up the web as instructed in the README, but cannot access the web UI via either 127.0.01:8090, 0.0.0.0:8090 or localhost:8090

I check the log: 
`Failed to load resource: the server responded with a status of 404 (Not Found) :8090/favicon.ico:1`

So I suppose the icon image is missing. But I use a random image to replace this /favicon in the root dir, it still returns me the `{"detail":"Not Found"}`.

This issue is related to #36 
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                 PORTS                    NAMES
7ffbcb7e91cc   xagent-server:0.1         "python start_server…"   21 minutes ago   Up 21 minutes          0.0.0.0:8090->8090/tcp   XAgent-Server
ff8a3223e589   tool-server-monitor:0.1   "python main.py"         2 hours ago      Up 2 hours             8180/tcp                 toolserver-ToolServerMonitor-1
0b5e79dc5061   tool-server-node:0.2      "uvicorn main:app --…"   2 hours ago      Up 2 hours (healthy)   31942/tcp                toolserver-ToolServerNode-1
ae79e03e9125   mongo                     "docker-entrypoint.s…"   2 hours ago      Up 2 hours             27017/tcp                toolserver-db-1
```

version: 2ea7b77df40bf5a57e8e5ada92941fb41a4c3b10
Docker Compose version v2.20.2-desktop.1

**Comment by yinfangchen** [comment]
I did the delta debugging. This 1e8a0795 commit will have the HTTP 404 error; while its parent commit 7b5d0689564387f498e5b70b384e3fdfb6768812 will have the `This site can’t be reached. localhost refused to connect. ERR_CONNECTION_REFUSED`

**Comment by yinfangchen** [comment]
I can see the login page by using the npm way:
```
cd ../XAgentWeb
npm install
npm run dev
```

but the login failed with log:
```

 ERROR  1:35:17 AM [vite] http proxy error at /login:                                                                                                  01:35:17
Error: connect ECONNREFUSED 127.0.0.1:8090
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)

 ERROR  1:35:32 AM [vite] http proxy error at /login:                                                                                                  01:35:32
Error: connect ECONNREFUSED 127.0.0.1:8090
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) (x2)
```

**Comment by siiia** [comment]
获取到http 500错误说明你的请求到了XAgentServer端，你可以把docker里面的报错日志也贴出来看看

**Comment by sailaoda** [comment]
Hello, we have merge web ui front and back ends into one docker, and now you could try to run "docker compose up" under /XAgentServer, and make the nginx runing. You could visit "http://localhost:5173" to use web ui.
