### ISSUE TITLE
Basically you guys are taking a raw LLM and creating a system for it to help a user in managing and doing various tasks on his/her local machine ? 

### ISSUE THREAD

**Issue by KartikeyBartwal** [OpenBMB/XAgent#49]

**Comment by Alexander5421** [comment]
In my opinion, just an advanced way to use LLM  rather than stick to conversation bot style. You are the boss, the LLM will try it's best to finish the task you give to it. During that time, it may need to use various tools like internet, a environment can run python,etc

**Comment by KartikeyBartwal** [comment]
I see
