### ISSUE TITLE
是否支持使用本地部署的大模型？比如开源的Qwen-14B或llama-70B?

### ISSUE THREAD

**Issue by LOGIC-10** [OpenBMB/XAgent#5]
是否支持使用本地部署的大模型？比如开源的Qwen-14B或llama-70B?
本地已构建多个开源大模型本地化部署的API接口，能否类似langchain直接调用？

**Comment by White-Friday** [comment]
同问

**Comment by tokyo2006** [comment]
同问

**Comment by thuqinyj16** [comment]
我们会在两周左右release一个agent任务效果接近GPT-4的本地模型，并支持本地模型的调用哈～

**Comment by LOGIC-10** [comment]
> 我们会在两周左右release一个agent任务效果接近GPT-4的本地模型，并支持本地模型的调用哈～

哇！好赞！期待期待

**Comment by Jeffwan** [comment]
@thuqinyj16 本地模型是weights形式提供，还是会提供训练的细节？

**Comment by kevio33** [comment]
> 我们会在两周左右release一个agent任务效果接近GPT-4的本地模型，并支持本地模型的调用哈～

请问本地部署对GPU等硬件有要求吗

**Comment by Hezhexi2002** [comment]
> 我们会在两周左右release一个agent任务效果接近GPT-4的本地模型，并支持本地模型的调用哈～

请问到时候这个本地模型对硬件要求怎么样，学生党没有卡真的很难受😭

**Comment by HuntZhaozq** [comment]
> 我们会在两周左右release一个agent任务效果接近GPT-4的本地模型，并支持本地模型的调用哈～

请问是AgentLM吗

**Comment by SmellyBones** [comment]
yyo i translated everything and im hyped!!!! cant wait for the release ill be check daily :D

**Comment by qazwsx042** [comment]
期待

**Comment by milomoon** [comment]
ChatGLM3吗？期待中。。

**Comment by neocao123** [comment]
> ChatGLM3吗？期待中。。

好像已经出了

**Comment by joseph16388** [comment]
**最好能提供对开源大模型的统一接口哈**

**Comment by jackiezhangcn** [comment]
> > ChatGLM3吗？期待中。。
> 
> 好像已经出了
where Can I find the tutorial?

**Comment by miandai** [comment]
ChatGLM3 怎么用在 XAgent 中，万分期待！

**Comment by menkeyi001** [comment]
现在本地大模型支持的进度如何了?

**Comment by dzfish** [comment]
这个出来了么

**Comment by Umpire2018** [comment]
参见 #162
