### ISSUE TITLE
提问没有反馈

### ISSUE THREAD

**Issue by zhlei07** [OpenBMB/XAgent#57]
http://localhost:5173这个网页可以打开,但是提问以后没有反馈
<img width="1148" alt="image" src="https://github.com/OpenBMB/XAgent/assets/40599435/037ef801-4e8b-436b-8780-2e9fa665f241">
XAgent-Server  |   "default_completion_kwargs": {
XAgent-Server  |     "model": "gpt-4",
XAgent-Server  |     "temperature": 0.2,
XAgent-Server  |     "request_timeout": 60
XAgent-Server  |   },
XAgent-Server  |   "enable_summary": true,
XAgent-Server  |   "summary": {
XAgent-Server  |     "single_action_max_length": 2048,
XAgent-Server  |     "max_return_length": 12384
XAgent-Server  |   },
XAgent-Server  |   "use_selfhost_toolserver": true,
XAgent-Server  |   "selfhost_toolserver_url": "http://localhost:8090",
XAgent-Server  |   "max_retry_times": 3,
XAgent-Server  |   "max_subtask_chain_length": 15,
XAgent-Server  |   "max_plan_refine_chain_length": 3,
XAgent-Server  |   "max_plan_tree_depth": 3,
XAgent-Server  |   "max_plan_tree_width": 5,
XAgent-Server  |   "max_plan_length": 8192,
XAgent-Server  |   "rapidapi_retrieve_tool_count": 0,
XAgent-Server  |   "enable_ask_human_for_help": false,
XAgent-Server  |   "tool_blacklist": [
XAgent-Server  |     "FileSystemEnv_print_filesys_struture"
XAgent-Server  |   ],
XAgent-Server  |   "record_dir": null
XAgent-Server  | }
XAgent-Server  | Human-In-The-Loop  False

**Comment by VectorZhao** [comment]
一样的问题

**Comment by ChengFai** [comment]
检查一下是不是没启动工具服务器

**Comment by VectorZhao** [comment]
cd ToolServer
docker-compose up

已经执行过了

<img width="948" alt="image" src="https://github.com/OpenBMB/XAgent/assets/16644993/7caacae7-5632-496f-ac71-933a937fc4cc">

node这个容器处于停止状态，手动启动还是停止。

**Comment by shalimujiang** [comment]
> cd ToolServer docker-compose up
> 
> 已经执行过了
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/16644993/277095139-7caacae7-5632-496f-ac71-933a937fc4cc.png">
> node这个容器处于停止状态，手动启动还是停止。
我的也是：node这个容器处于停止状态

**Comment by zhlei07** [comment]
> 检查一下是不是没启动工具服务器

这个也已经启动了

**Comment by zhlei07** [comment]
> I encountered the same problem and couldn't run run.py smoothly when calling it from the command line.
> I want to know if there is any information I can provide to help you identify the problem？

how you solve the problem

**Comment by zhlei07** [comment]
> cd ToolServer docker-compose up
> 
> 已经执行过了
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/16644993/277095139-7caacae7-5632-496f-ac71-933a937fc4cc.png">
> node这个容器处于停止状态，手动启动还是停止。

我跟你的问题一样, 你解决了吗

**Comment by zhlei07** [comment]
> 检查一下是不是没启动工具服务器

确实有一个一直启动不了toolserver-ToolServerNode-1

**Comment by VectorZhao** [comment]
> > 检查一下是不是没启动工具服务器
> 
> 确实有一个一直启动不了toolserver-ToolServerNode-1

还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题

**Comment by shalimujiang** [comment]
> > cd ToolServer docker-compose up
> > 已经执行过了
> > <img alt="image" width="948" src="https://user-images.githubusercontent.com/16644993/277095139-7caacae7-5632-496f-ac71-933a937fc4cc.png">
> > node这个容器处于停止状态，手动启动还是停止。
> 
> 我跟你的问题一样, 你解决了吗

![image](https://github.com/OpenBMB/XAgent/assets/75249643/ccf1ef20-56c9-4cc5-bc0a-a8480d323863)
这样注释掉就可以启动了，狗头
![image](https://github.com/OpenBMB/XAgent/assets/75249643/8719f3f0-3c79-4f31-9a2b-32b07478c3ba)

现在帮我解决一下这个问题，谢谢：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5)
![image](https://github.com/OpenBMB/XAgent/assets/75249643/89e49a03-5f30-48b2-b520-1ff44847b975)

**Comment by shalimujiang** [comment]
> > > 检查一下是不是没启动工具服务器
> > 
> > 
> > 确实有一个一直启动不了toolserver-ToolServerNode-1
> 
> 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题

![image](https://github.com/OpenBMB/XAgent/assets/75249643/ccf1ef20-56c9-4cc5-bc0a-a8480d323863)
这样注释掉就可以启动了，狗头
![image](https://github.com/OpenBMB/XAgent/assets/75249643/8719f3f0-3c79-4f31-9a2b-32b07478c3ba)

现在帮我解决一下这个问题，谢谢：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5)
![image](https://github.com/OpenBMB/XAgent/assets/75249643/89e49a03-5f30-48b2-b520-1ff44847b975)

**Comment by zhlei07** [comment]
> > > > 检查一下是不是没启动工具服务器
> > > 
> > > 
> > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > 
> > 
> > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> 
> ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> 
> 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)

我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题

**Comment by shalimujiang** [comment]
> > > > > 检查一下是不是没启动工具服务器
> > > > 
> > > > 
> > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > 
> > > 
> > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> 
> 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题

加油，我也不懂。这个问题从项目开始到现在还没解决，狗头，项目负责人一直在修复别的，就没看到这个问题。我现在在求助GPT-4，看能不能找得到问题，嘤嘤嘤

**Comment by zhlei07** [comment]
> > > > > > 检查一下是不是没启动工具服务器
> > > > > 
> > > > > 
> > > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > > 
> > > > 
> > > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> > 
> > 
> > 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题
> 
> 加油，我也不懂。这个问题从项目开始到现在还没解决，狗头，项目负责人一直在修复别的，就没看到这个问题。我现在在求助GPT-4，看能不能找得到问题，嘤嘤嘤

你也是m1的mac么
这个不知道比metagpt好用多少, 我之前metagpt一下就弄好了, 也是比较好用的

**Comment by shalimujiang** [comment]
> > > > > > > 检查一下是不是没启动工具服务器
> > > > > > 
> > > > > > 
> > > > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > > > 
> > > > > 
> > > > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > > > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> > > 
> > > 
> > > 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题
> > 
> > 
> > 加油，我也不懂。这个问题从项目开始到现在还没解决，狗头，项目负责人一直在修复别的，就没看到这个问题。我现在在求助GPT-4，看能不能找得到问题，嘤嘤嘤
> 
> 你也是m1的mac么 这个不知道比metagpt好用多少, 我之前metagpt一下就弄好了, 也是比较好用的

不是，我的系统是windows，用的是WSL2，WSL2里用的是Ubuntu系统。你看vscode的左下角就行
OK，到时我试试看metagpt，我没怎么玩过。
我之前看过有人提issue，然后他可以运行这个项目，不知道问题出在哪儿了？

**Comment by shalimujiang** [comment]
> > > > > 检查一下是不是没启动工具服务器
> > > > 
> > > > 
> > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > 
> > > 
> > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> 
> 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题

你试试看改一下这个，不过GPT-4还是恢复不了：
![image](https://github.com/OpenBMB/XAgent/assets/75249643/3ab9bbd7-2a07-4ae9-bc8b-fedc9ff18fcd)

这个问题又出现在哪儿了？

**Comment by zhlei07** [comment]
> > > > > > 检查一下是不是没启动工具服务器
> > > > > 
> > > > > 
> > > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > > 
> > > > 
> > > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> > 
> > 
> > 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题
> 
> 你试试看改一下这个，不过GPT-4还是恢复不了： ![image](https://user-images.githubusercontent.com/75249643/277118621-3ab9bbd7-2a07-4ae9-bc8b-fedc9ff18fcd.png)
> 
> 这个问题又出现在哪儿了？

我放弃了, 按照你的方法注释掉可以解决服务不能启动的问题, 但是提问还是没反馈. Human-In-The-Loop  False
2023-10-22 01:00:42 XAgent-Server  | ToolServer connected in  http://ToolServerManager:8080
2023-10-22 01:00:42 XAgent-Server  |   Start outer loop async
2023-10-22 01:00:42 XAgent-Server  | -=-=-=-=-=-=-= BEGIN QUERY SOVLING -=-=-=-=-=-=-= 
2023-10-22 01:00:42 XAgent-Server  | Role 
2023-10-22 01:00:43 XAgent-Server  | Task  what your name
2023-10-22 01:00:43 XAgent-Server  | -=-=-=-=-=-=-= GENERATE INITIAL_PLAN -=-=-=-=-=-=-=

**Comment by zhlei07** [comment]
> > > > > > 检查一下是不是没启动工具服务器
> > > > > 
> > > > > 
> > > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > > 
> > > > 
> > > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> > 
> > 
> > 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题
> 
> 你试试看改一下这个，不过GPT-4还是恢复不了： ![image](https://user-images.githubusercontent.com/75249643/277118621-3ab9bbd7-2a07-4ae9-bc8b-fedc9ff18fcd.png)
> 
> 这个问题又出现在哪儿了？

也可能是国内网络的问题?

**Comment by shalimujiang** [comment]
> > > > > > > 检查一下是不是没启动工具服务器
> > > > > > 
> > > > > > 
> > > > > > 确实有一个一直启动不了toolserver-ToolServerNode-1
> > > > > 
> > > > > 
> > > > > 还没解决，按照readme一步步操作，所以现在也不知道是哪个环节出了问题
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/75249643/277116997-ccf1ef20-56c9-4cc5-bc0a-a8480d323863.png) 这样注释掉就可以启动了，狗头 ![image](https://user-images.githubusercontent.com/75249643/277117014-8719f3f0-3c79-4f31-9a2b-32b07478c3ba.png)
> > > > 现在帮我解决一下这个问题，谢谢： ![image](https://user-images.githubusercontent.com/75249643/277117082-dc581dc8-2f2f-4ec1-82ee-0e46e170ebe5.png) ![image](https://user-images.githubusercontent.com/75249643/277117115-89e49a03-5f30-48b2-b520-1ff44847b975.png)
> > > 
> > > 
> > > 我在ToolServerNode里手动运行main.py提示是config.yml路径的问题, 因为config.py里面用的是相对路径, 但是我改成绝对路径之后又提示config.yml里面缺少toolregister值, 会不会下载下来的config.yml文件有问题
> > 
> > 
> > 你试试看改一下这个，不过GPT-4还是恢复不了： ![image](https://user-images.githubusercontent.com/75249643/277118621-3ab9bbd7-2a07-4ae9-bc8b-fedc9ff18fcd.png)
> > 这个问题又出现在哪儿了？
> 
> 也可能是国内网络的问题?

我一直用着tz，应该不会吧

**Comment by VectorZhao** [comment]
我是直接国外vps部署，所以这种不响应的问题不是网络问题

**Comment by shalimujiang** [comment]
> 我是直接国外vps部署，所以这种不响应的问题不是网络问题

如果这个问题解决，回复一下解决办法，嘤嘤嘤

**Comment by VectorZhao** [comment]
> > 我是直接国外vps部署，所以这种不响应的问题不是网络问题
> 
> 如果这个问题解决了，回复一下解决办法，谢谢

好的，现在还未解决

**Comment by luyaxi** [comment]
请查看XAgentServer的日志信息，未响应大概率是因为配置的api key无效

**Comment by zhlei07** [comment]
> 请查看XAgentServer的日志信息，未响应大概率是因为配置的api key无效

api key没问题,这个key我其他程序也在用

**Comment by VectorZhao** [comment]
> 请查看XAgentServer的日志信息，未响应大概率是因为配置的api key无效
## config.yml
```
openai_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-ETk47BQZyxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      api_base: https://api.xxx.xxx
      model: gpt-3.5-turbo-16k
      # you can use any kwargs supported by openai.ChatCompletion here

default_completion_kwargs:
  model: gpt-3.5-turbo-16k
  temperature: 0.5
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 8192
  max_return_length: 18432

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 3
max_subtask_chain_length: 20
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False
```

## docker logs XAgent-Server
```
INFO:     Stopping reloader process [1]
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
  XAgent Service Startup Param:
            app: app:app
            prod: False
            base_dir: XAgentServer
            use_redis: False
            recorder_root_dir: running_records
            default_login: True
            check_running: False
            host: 0.0.0.0
            port: 8090
            debug: True
            reload: True
            workers: 1
            DB: <class 'XAgentServer.envs.XAgentServerEnv.DB'>
            Redis: <class 'XAgentServer.envs.XAgentServerEnv.Redis'>
            Email: <class 'XAgentServer.envs.XAgentServerEnv.Email'>
            Upload: <class 'XAgentServer.envs.XAgentServerEnv.Upload'>
  init websocket_queue
XAgentServer is running on 0.0.0.0:8090  
Default user: admin, token: xagent-admin, you can use it to login  
  Create task for pong broadcast
init a websocket manager  
init a thread pool executor, max_workers: 1  
  pong broadcast for active connections: 0
  init localstorage connection: users.json
  init localstorage connection: interaction.json
  pong broadcast for active connections: 0
  pong broadcast for active connections: 0
  pong broadcast for active connections: 0
INFO:     127.0.0.1:50214 - "POST /login HTTP/1.0" 200 OK
```

**Comment by luyaxi** [comment]
如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态

**Comment by VectorZhao** [comment]
> 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态

不太清楚具体该如何操作

**Comment by zhlei07** [comment]
现在访问进去是没问题,只是提问后没响应

**Comment by VectorZhao** [comment]
> 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态

![image](https://github.com/OpenBMB/XAgent/assets/16644993/711151d3-8a75-4031-8c7d-7c3eed76d575)

**Comment by VectorZhao** [comment]
> 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态

那么应该如何使8090端口被forward

**Comment by luyaxi** [comment]
> > 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态
> 
> ![image](https://user-images.githubusercontent.com/16644993/277262674-711151d3-8a75-4031-8c7d-7c3eed76d575.png)

如果您使用vscode访问远程服务器，请在端口选项页中添加端口8090

**Comment by VectorZhao** [comment]
> > > 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16644993/277262674-711151d3-8a75-4031-8c7d-7c3eed76d575.png)
> 
> 如果您使用vscode访问远程服务器，请在端口选项页中添加端口8090

我是项目部署在远程VPS，然后本地访问ip:5173

**Comment by tyrone2015** [comment]
> > > > 如果你在远程访问xagent，确保端口8090也被forward。使用浏览器开发者工具（默认F12）确认请求状态
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/16644993/277262674-711151d3-8a75-4031-8c7d-7c3eed76d575.png)
> > 
> > 
> > 如果您使用vscode访问远程服务器，请在端口选项页中添加端口8090
> 
> 我是项目部署在远程VPS，然后本地浏览器访问ip:5173

这个问题可以修改文件XAgentWeb/src/api/backend.ts中的BACKEND_URL_LOCALDEPLOY地址到当前服务器IP就可以了，可惜我还是没有在远程docker中跑起来。。现在问题还是有点多

**Comment by Umpire2018** [comment]
请各位不要在同一 issue 中讨论不同的问题，并注意文本格式以方便阅读。
