### ISSUE TITLE
I am running command line, python runpy --task "my task" --model "gpt-4"

### ISSUE THREAD

**Issue by satyaveerendra** [OpenBMB/XAgent#58]
the task was running successfully and i am also able to see that the running_records folder getting updated, but local_workspace is always empty not sure may i know what would be the reason or rather i want to know what happened to all the generated content 

<img width="280" alt="Screenshot 2023-10-21 at 3 58 09 AM" src="https://github.com/OpenBMB/XAgent/assets/13285371/8d86c3e1-b4b9-477e-b346-de1673ef5de6">

local_workspace empty
<img width="1440" alt="Screenshot 2023-10-21 at 4 03 09 AM" src="https://github.com/OpenBMB/XAgent/assets/13285371/4e85af40-5b2e-4707-8ad2-ae37d8377162">

Task completion screenshot from terminal
<img width="458" alt="Screenshot 2023-10-21 at 4 02 24 AM" src="https://github.com/OpenBMB/XAgent/assets/13285371/d8e32450-9fa0-4987-819b-9eb327b927f7">

**Comment by luyaxi** [comment]
local_workspace currently is used to store the temporal files, you can get your entire workspace in the running_records/<your record id>/workspace.zip at this time. We will work on to fix that

**Comment by satyaveerendra** [comment]
hey @luyaxi thanks for the comment but unfortunately i don't see the `workspace.zip` inside running_records  also i have checked the enitre local repo there is no such zip file

**Comment by satyaveerendra** [comment]
sorry ignore this comment i can see it now thank you @luyaxi for the update
