### ISSUE TITLE
Bug - Grammar mistake in README.md

### ISSUE THREAD

**Issue by ayushrakesh** [OpenBMB/XAgent#61]
I have noticed one small grammar mistake in **README.md** file inside section "**XAgent**".

"**also collaborate with human to solve tasks.**" should be "**also collaborate with humans to solve tasks.**"

Below I have attached the screenshot of it.

![Screenshot (82)](https://github.com/OpenBMB/XAgent/assets/115995339/0f1b08a0-bdeb-4963-9ead-c28d02477e4d)

**Comment by ayushrakesh** [comment]
Please assign this task to me.

**Comment by ChengFai** [comment]
OK， we will correct it.
