### ISSUE TITLE
collection issue

### ISSUE THREAD

**Issue by georgehu0815** [OpenBMB/XAgent#64]
"conn9","msg":"Received first command on ingress connection since session start or auth handshake","attr":{"elapsedMillis":0}}
agitated_kowalevski             | INFO:     Shutting down
agitated_kowalevski             | INFO:     Waiting for application shutdown.
agitated_kowalevski             | INFO:     Application shutdown complete.
agitated_kowalevski             | INFO:     Finished server process [1]
XAgent-Server                   | ERROR:    Exception in ASGI application
XAgent-Server                   | Traceback (most recent call last):
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
XAgent-Server                   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
XAgent-Server                   |     return await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-pack

XAgent-Server                   |   "summary": {
XAgent-Server                   |     "single_action_max_length": 2048,
XAgent-Server                   |     "max_return_length": 12384
XAgent-Server                   |   },
XAgent-Server                   |   "use_selfhost_toolserver": true,
XAgent-Server                   |   "selfhost_toolserver_url": "http://ToolServerManager:8080",
XAgent-Server                   |   "max_retry_times": 3,
XAgent-Server                   |   "max_subtask_chain_length": 15,
XAgent-Server                   |   "max_plan_refine_chain_length": 3,
XAgent-Server                   |   "max_plan_tree_depth": 3,
XAgent-Server                   |   "max_plan_tree_width": 5,
XAgent-Server                   |   "max_plan_length": 8192,
XAgent-Server                   |   "rapidapi_retrieve_tool_count": 0,
XAgent-Server                   |   "enable_ask_human_for_help": false,
XAgent-Server                   |   "tool_blacklist": [
XAgent-Server                   |     "FileSystemEnv_print_filesys_struture"
XAgent-Server                   |   ],

agitated_kowalevski             | INFO:     Waiting for application startup.
agitated_kowalevski             | Starting Docker: docker.
agitated_kowalevski             | INFO:     Register env FileSystemEnv with 3 tools!
agitated_kowalevski             | WARNING:  Bing API key is not provided, rollback to duckduckgo.
agitated_kowalevski             | INFO:     Register env WebEnv with 2 tools!
agitated_kowalevski             | INFO:     Register env PythonNotebook with 2 tools!
agitated_kowalevski             | INFO:     Register tool shell_command_executor!
agitated_kowalevski             | INFO:     Loaded 8 tools and 3 envs!
agitated_kowalevski             | INFO:     Application startup complete.
agitated_kowalevski             | INFO:     Uvicorn running on http://0.0.0.0:31942 (Press CTRL+C to quit)
agitated_kowalevski             | INFO:     127.0.0.1:43506 - "GET / HTTP/1.1" 200 OK
agitated_kowalevski             | INFO:     172.20.0.6:41754 - "POST /get_available_tools HTTP/1.1" 200 OK
XAgent-Server                   | ToolServer connected in  http://ToolServerManager:8080
XAgent-Server                   |   Start outer loop async
XAgent-Server                   | -=-=-=-=-=-=-= BEGIN QUERY SOVLING -=-=-=-=-=-=-= 
XAgent-Server                   | Role

**Comment by georgehu0815** [comment]
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                    PORTS                                            NAMES
a7bbd3bbdc7b   tool-server-monitor:0.1   "python main.py"         48 minutes ago   Up 45 seconds             8180/tcp                                         toolserver-ToolServerMonitor-1
1f5113c893fb   tool-server-manager:0.2   "gunicorn main:app -…"   48 minutes ago   Up 45 seconds (healthy)   0.0.0.0:8080->8080/tcp                           toolserver-ToolServerManager-1
f438347872db   mongo                     "docker-entrypoint.s…"   48 minutes ago   Up 46 seconds             27017/tcp                                        toolserver-db-1
df4b06941ec8   xagent-server:0.3         "python start_server…"   48 minutes ago   Up 45 seconds             0.0.0.0:5173->5173/tcp, 0.0.0.0:8090->8090/tcp   XAgent-Server
bochuxt@george-nv:/mnt/a/XAgent$

**Comment by georgehu0815** [comment]
all container started success, gpt license works fine, but when access GUI, it says socket issue : XAgent-Server | ERROR: Exception in ASGI application

[+] Stopping 5/5
 ✔ Container toolserver-ToolServerManager-1  Stopped                                                          1.0s 
 ✔ Container toolserver-ToolServerNode-1     Stopped                                                          0.0s 
 ✔ Container XAgent-Server                   Stopped                                                          1.1s 
 ✔ Container toolserver-ToolServerMonitor-1  Stopped                                                         10.4s 
 ✔ Container toolserver-db-1                 Stopped                                                          0.5s 
canceled

**Comment by luyaxi** [comment]
Please pull latest code, rebuild the services and rerun to help us locate the problem.
