### ISSUE TITLE
need support AzureOpenAI api and key

### ISSUE THREAD

**Issue by georgehu0815** [OpenBMB/XAgent#65]
the default is support opanai key, we need support Azure openai key as well.

import openai
from langchain.agents import create_spark_dataframe_agent
from langchain.chat_models import ChatOpenAI
openai.api_type = "azure"
openai.api_base = "https://domain.openai.azure.com/"
openai.api_key ="***"
openai.model_name = "gpt-4"
openai.deployment_name= "dev" 

openai.api_version = "2023-07-01-preview"
chat = ChatOpenAI(
    openai_api_key=openai.api_key,
    model_name= "gpt-4",#openai.model_name, 
    engine =openai.deployment_name,
    temperature=0, )
from langchain.schema import AIMessage, HumanMessage, SystemMessage
messages = [
    SystemMessage(
        content="You are a helpful assistant that translates English to French."
    ),
    HumanMessage(
        content="who are you"
    ),
]
chat(messages)

**Comment by georgehu0815** [comment]
Agent-Server                   |   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
XAgent-Server                   |     raise self.handle_error_response(
XAgent-Server                   | openai.error.AuthenticationError: Incorrect API key provided: 0********************dc77. You can find your API key at https://platform.openai.com/account/api-keys.
XAgent-Server                   | INFO:     connection closed

**Comment by georgehu0815** [comment]
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
XAgent-Server                   |     return session.request(method=method, url=url, **kwargs)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
XAgent-Server                   |     resp = self.send(prep, **send_kwargs)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
XAgent-Server                   |     r = adapter.send(request, **kwargs)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
XAgent-Server                   |     raise ConnectionError(e, request=request)
XAgent-Server                   | requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0da41a1810>: Failed to establish a new connection: [Errno 111] Connection refused'))
XAgent-Server                   | INFO:     connection closed

**Comment by luyaxi** [comment]
Azure key has been supported by default, just fill your key in the config.yml. For the second error, please check you have started ToolServer
