### ISSUE TITLE
Upload txt file does not work on the local web service

### ISSUE THREAD

**Issue by Zephyruswind** [OpenBMB/XAgent#69]
Upload txt file does not work on the local web service. After choose the file, the web page hangs without response for a long time.

**Comment by ChengFai** [comment]
Do you see any notification text after uploading？

**Comment by Zephyruswind** [comment]
No notifcation. Just hang without any response

**Comment by sailaoda** [comment]
Hello, could you fetch to the latest project and try again, and notice the logs in the XAgent-Server docker whether the "/upload" would run
