### ISSUE TITLE
Unexpected error hangs in running time

### ISSUE THREAD

**Issue by Zephyruswind** [OpenBMB/XAgent#71]
XAgent-Server                   | PLAN MODIFY STATUS CODE:  PLAN_REFINE_EXIT
XAgent-Server                   |   close io connection
affectionate_bohr               | INFO:     172.18.0.2:53590 - "POST /download_workspace HTTP/1.1" 200 OK
affectionate_bohr               | INFO:     Shutting down
affectionate_bohr               | INFO:     Waiting for application shutdown.
affectionate_bohr               | INFO:     Application shutdown complete.
affectionate_bohr               | INFO:     Finished server process [1]
XAgent-Server                   | ERROR:    Exception in ASGI application
XAgent-Server                   | Traceback (most recent call last):
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
XAgent-Server                   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
XAgent-Server                   |     return await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
XAgent-Server                   |     await super().__call__(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
XAgent-Server                   |     await self.middleware_stack(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
XAgent-Server                   |     await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
XAgent-Server                   |     await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 26, in __call__
XAgent-Server                   |     await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
XAgent-Server                   |     raise exc
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
XAgent-Server                   |     await self.app(scope, receive, sender)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
XAgent-Server                   |     raise e
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
XAgent-Server                   |     await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
XAgent-Server                   |     await route.handle(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
XAgent-Server                   |     await self.app(scope, receive, send)
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 88, in dispatch
XAgent-Server                   |     raise exc
XAgent-Server                   |   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 80, in dispatch
XAgent-Server                   |     await self.on_receive(websocket, data)
XAgent-Server                   |   File "/app/app.py", line 612, in on_receive
XAgent-Server                   |     args, agent, mode, file_list = await self.check_receive_data(data)
XAgent-Server                   |   File "/app/app.py", line 651, in check_receive_data
XAgent-Server                   |     raise XAgentIOWebSocketReceiveError(
XAgent-Server                   | XAgentIO.exception.XAgentIOWebSocketReceiveError: mode is not exist! Only auto and manual are allowed!
affectionate_bohr exited with code 0
affectionate_bohr exited with code 0
XAgent-Server                   | INFO:     connection closed
toolserver-ToolServerMonitor-1  | INFO:  Stopping node: bbe9189d813880b32e174d8cffc454529368cef00d2b0d2f2805eb3512de7d94  due to idling time used up
pensive_tesla exited with code 0
toolserver-ToolServerMonitor-1  | INFO:  Stopping node: 0695b074a68d17b83065718e1a1809dab21cb852e00f40933758239155671937  due to idling time used up
jovial_pascal exited with code 0
toolserver-ToolServerMonitor-1  | INFO:  Stopping node: 750261a94c68b5275710b138070bd429d3bfe3d266af8a2ced372fa1f5527b3c  due to idling time used up
optimistic_fermat exited with code 0

**Comment by luyaxi** [comment]
Can you upload your running records and logs in XAgent/XAgentServer/localstorage/interact_records/2023-xxx/xxx to help us identify the problem? Make sure you remove all sensitive infomation!
