### ISSUE TITLE
websocket use localhost

### ISSUE THREAD

**Issue by av8dtop** [OpenBMB/XAgent#72]
目前只用docker-compose部屬
但是我是遠端操控
所以會遇到ws://localhost : fail
可以改成使用 ip or domain?

**Comment by yhyu13** [comment]
需要port forward 8090吧。vscode里面remote connection，之后port forward挺方便的

**Comment by buptweixin** [comment]
给别人体验的话还得让他ssh上服务器还是很麻烦， 可以直接开放可接入ip 为 0.0.0.0 这样吗?想要实现的效果是有局域网ip就能访问。

**Comment by Umpire2018** [comment]
@buptweixin https://github.com/OpenBMB/XAgent/issues/57#issuecomment-1774604080

**Comment by VectorZhao** [comment]
不知道现在进展如何？可以远端部署了吗
