### ISSUE TITLE
load running_recorder failed

### ISSUE THREAD

**Issue by georgehu0815** [OpenBMB/XAgent#83]
**ENV:** 
Windows11 WSL

**Reproduce:**
1) start tool server from cli: gunicorn --workers=1  --worker-class=uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 main:app
2) start xagentserver from cli: python start_server.py
3) sent request from  cli: python run.py --task "tell me a joke" --model "gpt-4" --config_file "assets/config.yml"

init interaction: 6aaf6a6f6e424234b7e6e4dd899ba55c
  Register logger into interaction of 6aaf6a6f6e424234b7e6e4dd899ba55c, done!
  Register io into interaction of 6aaf6a6f6e424234b7e6e4dd899ba55c, done!
  Register db into interaction of 6aaf6a6f6e424234b7e6e4dd899ba55c, done!
  Register logger into XAgentServer of 6aaf6a6f6e424234b7e6e4dd899ba55c, done!
  Start a new thread to run interaction of 6aaf6a6f6e424234b7e6e4dd899ba55c, done!
record_root_dir: ./running_records/2023_10_22_14_29_3016084250
Constructing an AgentDispatcher:  XAgentDispatcher
==args: {'description': 'XAgent-Test', 'role_name': 'Assistant', 'download_files': [], 'file_list': None, 'record_dir': '/mnt/a/XAgent/running_records', 'goal': 'tell me a joke', 'mode': 'auto', 'plan': [], 'max_wait_seconds': 600}
==interaction.base  {
  "interaction_id": "6aaf6a6f6e424234b7e6e4dd899ba55c",
  "user_id": "admin",
  "create_time": "2023-10-22 14:29:30",
  "description": "XAgent-Test",
  "agent": "XAgent",
  "mode": "auto",
  "file_list": null,
  "recorder_root_dir": "/mnt/a/XAgent/running_records",
  "status": "waiting",
  "message": "waiting...",
  "current_step": "34cbda2161274e5db276d22a5bc2d315",
  "update_time": "2023-10-22 14:29:30",
  "is_deleted": false
}
load from a disk record, overwrite all the existing config-info  /mnt/a/XAgent/running_records

Traceback (most recent call last):
  File "/mnt/a/XAgent/run.py", line 56, in <module>
    cmd.start(
  File "/mnt/a/XAgent/command.py", line 163, in start
    self.run({
  File "/mnt/a/XAgent/command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mnt/a/XAgent/XAgentServer/server.py", line 50, in interact
    raise e
  File "/mnt/a/XAgent/XAgentServer/server.py", line 43, in interact
    recorder.load_from_disk(interaction.base.recorder_root_dir)
  File "/mnt/a/XAgent/XAgent/running_recorder.py", line 257, in load_from_disk
    raise NotImplementedError
NotImplementedError

**Comment by luyaxi** [comment]
We have just update the recorder, the old records may result in failure when loading.
