### ISSUE TITLE
chatcompletion error: Object of type InvalidRequestError is not JSON serializable  

### ISSUE THREAD

**Issue by SmellyBones** [OpenBMB/XAgent#84]
i put an api key and org  in the config.yml in each one. both for the top and bottom in each model. i also went into the gpt4 config and gpt3.5 config and added keys there. i keep getting this error though. xagent is running and actually formulating but right before it gets to the end i get this 

chatcompletion error: Object of type InvalidRequestError is not JSON serializable

also i noticed once it creates a tool-server-node02 in the the docker container. however even when i stop xagent everything in the containter will stop except this and it keeps running and was actaully racking up a bill on my api key. why does it get stuck into a death loop of what seems to be calling my api key but not actually doing anything?

**Comment by luyaxi** [comment]
Can you show the traceback info? It should be printed before this line. Also Tool-Server-Node may failed to exit due to irregular cancel, the Tool-Server-Monitor will close it after 30mins. You can also manually close it. And Tool-Server-Node does not use openai api at all. If you find bill related problem, try to kill all xagent promgram

**Comment by SmellyBones** [comment]
the last image is of tool-server-node:02 this is what keeps running and even if i shut everything else off this always some how gets left on. there is also a pic of the traceback thank you for your help!



![code](https://github.com/OpenBMB/XAgent/assets/148628888/3da9266c-bcab-4095-a7fd-7b3aa0e196e0)
![4 of 11](https://github.com/OpenBMB/XAgent/assets/148628888/35adbf7b-ec35-4c21-894b-60000d6c1247)
![blac](https://github.com/OpenBMB/XAgent/assets/148628888/f5e761e6-aa64-40a7-a8e0-a36ac553d8e2)

**Comment by luyaxi** [comment]
it seems that you got errors due to log error, we've just post a fix for this. Could you plz have another try with latest code?

**Comment by SmellyBones** [comment]
the new code fixed it!! ty ty. @lu
