### ISSUE TITLE
配置文件需要先修改

### ISSUE THREAD

**Issue by zhangp365** [OpenBMB/XAgent#86]
文档上让先构建ToolServer的镜像并启动，后修改配置文件。实际呢，镜像应该是打包了配置文件，修改配置文件需要删除镜像重新打包。
config.yml中 organization 给了示例，但没有组织的，不用填，也不说明。
这个挺让人无语的。。。
后面的人注意一下吧

**Comment by luyaxi** [comment]
已修正该问题，现在assets文件夹会以read only模式被映射到docker容器中
