### ISSUE TITLE
[Feature] Add a stop button to the conversation.

### ISSUE THREAD

**Issue by GOWxx** [OpenBMB/XAgent#88]
## Feature Description / 功能描述

为运行的对话加**停止按钮**。
Add a **stop button** to the running conversation.

## Goal / 目标

**停止**对话生成。
**Stop** generating dialogue.

## Expected Behavior / 预期行为

点击**停止按钮**，对话**停止**生成。
Click the **stop button** to **stop** the conversation generation.

## Additional Notes / 其他备注

进阶想法：
增加**暂停**按钮，可以人为的修改当前的信息，引导对话走向。
Advanced idea:
Add a **pause button** that allows manual modification of the current information to guide the direction of the conversation.

**Comment by SmellyBones** [comment]
this would be a really cool feature!

**Comment by ChengFai** [comment]
we'll consider supporting this feature in next upgrade
