### ISSUE TITLE
Failed to log in when self-host

### ISSUE THREAD

**Issue by iamlockelightning** [OpenBMB/XAgent#9]
Thank you for publishing such a powerful tool!!

But after downloading this repo and trying to host it on my Mac, I can't log in to the localhost:8000 (within the real email and token info, which is available at https://x-agent.net/). The whole deployment seems fine.
 
1. Does that mean even if I host XAgent locally, I still need to register my info to openBMB?
2. Is there any virtual(or test) account that I can use?

<img width="2096" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/77803b1b-8c23-4839-9adc-be902e5b43ce">

**Comment by infinitezxc** [comment]
Default user: admin, token: xagent-admin, you can use it to login.

**Comment by iamlockelightning** [comment]
Thanks for the fast reply!

Pity, I am still not able to log in. I guess there are some CROS problems but I don't know how to handle them.

<img width="1381" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/1ce7c4c9-ad0d-4a13-a054-f3e39becbb7c">

I reviewed the README.md. The XAgentServer log is a little different.

<img width="1128" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/d8ef1196-a881-42ad-96c2-d7e4a22bd95e">

and the `npm run dev` port is different also. (http://localhost:5173/)
