### ISSUE TITLE
[BUG] docker can't stop

### ISSUE THREAD

**Issue by GOWxx** [OpenBMB/XAgent#90]
## Issue Description / 问题描述

docker can't stop.

## Steps to Reproduce / 复现步骤

run `docker-compose up`
then `control + c` or click stop button at docker GUI.

## Expected Behavior / 预期行为

docker stop.

## Environment / 环境信息
- Operating System / 操作系统：macos
- Python Version / Python 版本：Python 3.11.5

## Error Screenshots or Logs / 错误截图或日志
![image](https://github.com/OpenBMB/XAgent/assets/12870715/1f5f9b28-6054-4d80-acc7-23b6b065b1d7)

![image](https://github.com/OpenBMB/XAgent/assets/12870715/ebe7ac18-80a2-4b16-a734-224fb6a94933)

<img width="693" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12870715/cd60cb6b-eaa2-43a7-91c9-eacdb18496f7">

<img width="679" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12870715/1dcb96a9-4cff-45ae-8e05-97f7668a39e6">

**Comment by luyaxi** [comment]
It's not a `bug`, it's a `feature`. The `ToolServerNode` would not stop unless `ToolServerManager` receive close request. We design this to avoid the unexcepted failure of `ToolServerManager`. If your node is not stopped, you can delete them manually.

**Comment by GOWxx** [comment]
But I have stoped the containers in the paths of ToolServer and XAgnetServer.

This will prevent the entire container from stopping properly.

Or do I have any way to stop the entire container from running?

**Comment by luyaxi** [comment]
Try to use `docker compose down` or `docker compose stop`

**Comment by GOWxx** [comment]
## Run `docker compose stop`

<img width="767" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12870715/381ef98b-7ea3-4d36-9d33-d0f5eae8ed6e">
<img width="777" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12870715/b0a11d92-8a27-4782-b60c-95effe632bf4">

## Result
![image](https://github.com/OpenBMB/XAgent/assets/12870715/1fb6de44-27c3-4964-8b00-244d78967199)

I still need to manually delete the services (`heuristic_noyce`) that cannot be stopped now.

## Test reRun docker without `dock-compose buiild`

![image](https://github.com/OpenBMB/XAgent/assets/12870715/70393326-5cd6-46b5-b565-996ec31bbebd)

Obviously, this will be problematic.

<img width="862" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12870715/ebd413b0-cf55-48ed-b614-c6367a7cada0">

So, manually deleting the container is not a good solution. The docker command cannot properly shut down the container, it can only delete it.

Running the command `docker-compose build` every time is not a good idea.

## Expectation

Use the command to gracefully stop the running of a Docker container.

**Comment by luyaxi** [comment]
We are not planning to change this feature right now. If you have better solution to maintain the node's content while avoid manager failure problem, you can create a pull request or open a discussion.
