### ISSUE TITLE
docker compose up命令提示pymongo错误。

### ISSUE THREAD

**Issue by why2012physics** [OpenBMB/XAgent#93]
xagent-ToolServerMonitor-1  | Traceback (most recent call last):
xagent-ToolServerMonitor-1  |   File "/app/main.py", line 46, in <module>
xagent-ToolServerMonitor-1  |     asyncio.run(check_nodes_status_loop())
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
xagent-ToolServerMonitor-1  |     return loop.run_until_complete(main)
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
xagent-ToolServerMonitor-1  |     return future.result()
xagent-ToolServerMonitor-1  |   File "/app/main.py", line 42, in check_nodes_status_loop
xagent-ToolServerMonitor-1  |     await check_nodes_status()
xagent-ToolServerMonitor-1  |   File "/app/main.py", line 12, in check_nodes_status
xagent-ToolServerMonitor-1  |     async for node in nodes:
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 1390, in next
xagent-ToolServerMonitor-1  |     if self.alive and (self._buffer_size() or await self._get_more()):
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
xagent-ToolServerMonitor-1  |     result = self.fn(*self.args, **self.kwargs)
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1153, in _refresh
xagent-ToolServerMonitor-1  |     self.__session = self.__collection.database.client._ensure_session()
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
xagent-ToolServerMonitor-1  |     return self.__start_session(True, causal_consistency=False)
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
xagent-ToolServerMonitor-1  |     self._topology._check_implicit_session_support()
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
xagent-ToolServerMonitor-1  |     self._check_session_support()
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 599, in _check_session_support
xagent-ToolServerMonitor-1  |     self._select_servers_loop(
xagent-ToolServerMonitor-1  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
xagent-ToolServerMonitor-1  |     raise ServerSelectionTimeoutError(
xagent-ToolServerMonitor-1  | pymongo.errors.ServerSelectionTimeoutError: db:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 653623d92057d186eb15f037, topology_type: Unknown, servers: [<ServerDescription ('db', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('db:27017: timed out')>]>

(xagent) wanghy@gpuserver:/amax/home/wanghy/softwares/XAgent$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS                   PORTS                                                                                  NAMES
c71761a9e3a4   xagent-server:0.3         "python start_server…"   3 minutes ago   Up 3 minutes             0.0.0.0:5173->5173/tcp, :::5173->5173/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   XAgent-Server
160e3008c699   tool-server-manager:0.2   "gunicorn main:app -…"   8 minutes ago   Up 3 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              xagent-ToolServerManager-1
e5d2715970e3   mongo                     "docker-entrypoint.s…"   8 minutes ago   Up 3 minutes             27017/tcp                                                                              xagent-db-1

**Comment by why2012physics** [comment]
docker compose build成功了，但是docker compose up就提示pymongo.errors.ServerSelectionTimeoutError。
 
 mongo --host IP_Address --port 27017可以连接成功。
 
 运行docker exec XAgent-Server systemctl start nginx没反应，http://localhost:5173/这个也打不开

**Comment by luyaxi** [comment]
请确认`.env`文件中默认mongodb的账号密码被正确读取，服务依赖该文件中环境变量配置访问数据库

**Comment by why2012physics** [comment]
> 请确认`.env`文件中默认mongodb的账号密码被正确读取，服务依赖该文件中环境变量配置访问数据库

谢谢, .env文件里是这样：
DB_USERNAME=admin
DB_PASSWORD=xagentmongodb
DB_COLLECTION=TSM
CONFIG_FILE=assets/config.yml

请问如何确认被正确读取

**Comment by luyaxi** [comment]
尝试` docker exec -it xagent-db-1 bin/bash`进入shell，并打印环境变量
```bash
echo $MONGO_INITDB_ROOT_USERNAME && echo $MONGO_INITDB_ROOT_PASSWORD
```
如果同样的，你可以检查ToolServerManager与ToolServerMonitor服务是否正确获取的环境变量。如果都没有问题，请尝试重新build镜像

**Comment by why2012physics** [comment]
root@aff40a54971b:/# echo $MONGO_INITDB_ROOT_USERNAME && echo $MONGO_INITDB_ROOT_PASSWORD
admin
xagentmongodb

wanghy@gpuserver:~$ docker exec -it xagent-ToolServerManager-1 bin/bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "bin/bash": stat bin/bash: no such file or directory: unknown

**Comment by luyaxi** [comment]
能否提供mongodb镜像的运行日志，目前无法确定问题的根源

**Comment by why2012physics** [comment]
mongodb镜像中faillog和lastlog里都没内容
root@7c1da0a61de3:/var/log# ls
alternatives.log  apt  bootstrap.log  btmp  dpkg.log  faillog  lastlog  mongodb  wtmp
root@7c1da0a61de3:/var/log# cat faillog
root@7c1da0a61de3:/var/log# cat lastlog


root@7c1da0a61de3:/var/log# cat *.log | grep problem
dpkg: base-passwd: dependency problems, but configuring anyway as you requested:
dpkg: regarding .../base-files_12ubuntu4_amd64.deb containing base-files, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: base-files: dependency problems, but configuring anyway as you requested:
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: dpkg: dependency problems, but configuring anyway as you requested:
dpkg: libc6:amd64: dependency problems, but configuring anyway as you requested:
dpkg: regarding .../perl-base_5.34.0-3ubuntu1_amd64.deb containing perl-base, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: perl-base: dependency problems, but configuring anyway as you requested:
dpkg: regarding .../bash_5.1-6ubuntu1_amd64.deb containing bash, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../bsdutils_1%3a2.37.2-4ubuntu3_amd64.deb containing bsdutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../coreutils_8.32-4.1ubuntu1_amd64.deb containing coreutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../coreutils_8.32-4.1ubuntu1_amd64.deb containing coreutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../coreutils_8.32-4.1ubuntu1_amd64.deb containing coreutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../coreutils_8.32-4.1ubuntu1_amd64.deb containing coreutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../dpkg_1.21.1ubuntu2_amd64.deb containing dpkg, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../e2fsprogs_1.46.5-2ubuntu1_amd64.deb containing e2fsprogs, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../e2fsprogs_1.46.5-2ubuntu1_amd64.deb containing e2fsprogs, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../e2fsprogs_1.46.5-2ubuntu1_amd64.deb containing e2fsprogs, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../e2fsprogs_1.46.5-2ubuntu1_amd64.deb containing e2fsprogs, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../e2fsprogs_1.46.5-2ubuntu1_amd64.deb containing e2fsprogs, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../findutils_4.8.0-1ubuntu3_amd64.deb containing findutils, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../grep_3.7-1build1_amd64.deb containing grep, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libpam-modules_1.4.0-11ubuntu2_amd64.deb containing libpam-modules:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libsystemd0_249.11-0ubuntu3_amd64.deb containing libsystemd0:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libsystemd0_249.11-0ubuntu3_amd64.deb containing libsystemd0:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libsystemd0_249.11-0ubuntu3_amd64.deb containing libsystemd0:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libsystemd0_249.11-0ubuntu3_amd64.deb containing libsystemd0:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../libsystemd0_249.11-0ubuntu3_amd64.deb containing libsystemd0:amd64, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../login_1%3a4.8.1-2ubuntu2_amd64.deb containing login, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../login_1%3a4.8.1-2ubuntu2_amd64.deb containing login, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../login_1%3a4.8.1-2ubuntu2_amd64.deb containing login, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../login_1%3a4.8.1-2ubuntu2_amd64.deb containing login, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../login_1%3a4.8.1-2ubuntu2_amd64.deb containing login, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../mount_2.37.2-4ubuntu3_amd64.deb containing mount, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../mount_2.37.2-4ubuntu3_amd64.deb containing mount, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../mount_2.37.2-4ubuntu3_amd64.deb containing mount, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../mount_2.37.2-4ubuntu3_amd64.deb containing mount, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../ncurses-bin_6.3-2_amd64.deb containing ncurses-bin, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../perl-base_5.34.0-3ubuntu1_amd64.deb containing perl-base, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../sed_4.8-1ubuntu2_amd64.deb containing sed, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../sed_4.8-1ubuntu2_amd64.deb containing sed, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../tar_1.34+dfsg-1build3_amd64.deb containing tar, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../tar_1.34+dfsg-1build3_amd64.deb containing tar, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!
dpkg: regarding .../util-linux_2.37.2-4ubuntu3_amd64.deb containing util-linux, pre-dependency problem:
dpkg: warning: ignoring pre-dependency problem!

**Comment by luyaxi** [comment]
请确认使用了最新的docker-compose.yml并且所有服务都挂载在默认的tool-server-network下

**Comment by Zhang-ze-peng** [comment]
我遇到了相同的问题，请问您解决了吗？
