### ISSUE TITLE
docker-compose build error: failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by jingshuangliu22** [OpenBMB/XAgent#98]
## Issue Description / 问题描述
docker-compose build error: failed to solve with frontend dockerfile.v0

## Steps to Reproduce / 复现步骤
run docker-compose build

## Environment / 环境信息
Linux version 4.18.0-338.el8.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Fri Aug 27 17:32:14 UTC 2021
## Error Screenshots or Logs / 错误截图或日志
<img width="1436" alt="image" src="https://github.com/OpenBMB/XAgent/assets/6778976/555fea37-37b5-4884-96a5-289932ac711f">

**Comment by Umpire2018** [comment]
I think this is another connectivity issue with the docker registry. I suggest using alternative docker registry mirrors such as:

- Docker Hub's official mirror: https://registry-1.docker.io
- Google Container Registry (GCR): https://gcr.io
- Azure Container Registry: https://mcr.microsoft.com
- Alibaba Cloud Container Registry: https://cr.aliyun.com
- Tencent Cloud Container Registry: https://ccr.ccs.tencentyun.com
Please ensure you're using the appropriate region-specific endpoints if necessary.

**Comment by jingshuangliu22** [comment]
> * https://gcr.io

Thanks for your help. I changed the docker registry by the first three mirrors, however nothing changed. **The error** is still there.

And here is how I changed the docker registry:
``` sudo vim /etc/docker/daemon.json```
<img width="591" alt="image" src="https://github.com/OpenBMB/XAgent/assets/6778976/32235611-006d-4e55-907a-f9582cae2edd">
```sudo systemctl daemon-reload```
```sudo service docker restart ```

**Comment by Umpire2018** [comment]
I think there's no other way but to improve the network environment. I have no choice but to close this issue.
