### ISSUE TITLE
Remote CentOS 7 "Run XAgent with GUI" cmd has no log

### ISSUE THREAD

**Issue by iamlockelightning** [OpenBMB/XAgent#99]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

I execute the command "Run XAgent with GUI" as described in README in a CentOS 7 server. (All dependency is installed)
`docker exec XAgent-Server systemctl stop nginx`
But there is no log as the [screenshot](https://camo.githubusercontent.com/386aa7d58fb2f54fed5d94733f55032972a386d5af680c9bfc63a2185c1c5688/68747470733a2f2f67697465652e636f6d2f7361696c616f64612f706963322f7261772f6d61737465722f323032332f3230323330393237323132333432342e706e67) shows.

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

Run `docker exec XAgent-Server systemctl stop nginx`, and I get nothing:
<img width="908" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/ade910fb-ca27-4a09-8490-f3c5e1eb332d">

Run `curl` in the remote server seems fine:
<img width="2021" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/8d3c9e30-d3ed-4dc1-860d-060166776210">

When assessing the URL through a local browser, not work:
<img width="1208" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/6fa51b6b-71ad-471e-98ff-1e85d4e2e111">

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：CentOS 7
- Python Version / Python 版本：3.11
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

`ps -ef | grep nginx`
<img width="1032" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/4b075947-8aa6-42ef-b34a-e688867d6e71">

`lsof -i:5173`
<img width="638" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/32c3d470-d9bd-4d9a-8ebf-016978ff31ee">

``

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by luyaxi** [comment]
if you are using remote server, please make sure you add port forward for both 5173 and 8090 ports

**Comment by iamlockelightning** [comment]
Thanks!! 👍

**Comment by iamlockelightning** [comment]
Sorry to interrupt again! @luyaxi 

I added one forward rule from 80 -> 5173, and then I am able to browse the index.html and log in.
```shell
firewall-cmd --zone=public --add-forward-port=port=80:proto=tcp:toport=5173 --permanent
```
<img width="700" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/21e761d5-9849-4439-920c-b28ad9d5ebd3">


But after submitting the question, the web hangs.
<img width="1936" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/caa008d3-a344-49ad-8763-6e863b8b3acc">

I guess I should forward port=8090 also. But I don't know how to forward. Should I change the `nginx.conf`? And then execute `firewall-cmd --zone=public --add-forward-port=port=8090:proto=tcp:toport=ANY_OTHER_PORT --permanent`?
<img width="686" alt="image" src="https://github.com/OpenBMB/XAgent/assets/12706469/d0528d65-ba89-4c5e-8b71-34ea55448eb8">

**Comment by luyaxi** [comment]
You should use port 8090:
```bash
firewall-cmd --zone=public --add-forward-port=port=8090:proto=tcp:toport=8090 --permanent
```
